### ISSUE TITLE
monitoring does not always record task_time_running and hostname fields (on short jobs?)

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1011]
I see missing hostname and task_time_running for the first task, `create_empty_repo`, which runs extremely fast.

```
sqlite> select run_id, task_func_name, hostname, task_time_submitted, task_time_running, task_time_returned from task;
37cb5ae7-f4f9-40a7-86ec-9457760344f7|create_empty_repo||2019-06-04 04:13:31.476801||2019-06-04 04:13:31.553611
37cb5ae7-f4f9-40a7-86ec-9457760344f7|install_transmission_curves|cori06|2019-06-04 04:13:31.554481|2019-06-04 04:13:31.644297|2019-06-04 04:13:36.155113
37cb5ae7-f4f9-40a7-86ec-9457760344f7|import_ci_hsc|cori06|2019-06-04 04:13:31.560238|2019-06-04 04:13:31.650255|2019-06-04 04:18:30.889769
37cb5ae7-f4f9-40a7-86ec-9457760344f7|pccd_show|cori06|2019-06-04 04:18:30.891500|2019-06-04 04:18:30.989590|2019-06-04 04:18:49.810345
37cb5ae7-f4f9-40a7-86ec-9457760344f7|pccd_process|cori06|2019-06-04 04:18:30.898264|2019-06-04 04:18:31.031377|2019-06-04 05:26:59.966683
37cb5ae7-f4f9-40a7-86ec-9457760344f7|makeDiscreteSkyMap|cori06|2019-06-04 05:26:59.968017|2019-06-04 05:27:00.054919|2019-06-04 05:27:08.146285
```

**Comment by ZhuozhaoLi** [comment]
The two fields are from the first message from the monitoring wrapper of task. I guess the task is too short - so there is not enough time to run `psutil` and send message to hub.

**Comment by TomGlanzman** [comment]
I also am seeing this issue.  Don't know whether it is related or not, but I also see situations where SLURM (at NERSC) claims a job has been running for 5-10 minutes, but there is not yet any confirming information in the monitoring DB.

**Comment by ZhuozhaoLi** [comment]
@benclifford Not sure what the ideal fix here is. How about adding mechanism to guarantee the monitoring wrapper sends out the first message?

**Comment by benclifford** [comment]
I think making the code always send start and end messages would be a good thing

**Comment by ZhuozhaoLi** [comment]
@TomGlanzman Not quite sure this is related. I think this issue only happens to the tasks that are very short (like a no-op). If the DB does not receive that message, then there might be some other issues though. Could you please post the runinfo dir?

**Comment by benclifford** [comment]
Make a new issue for the slurm related problem - that probably isn't this one.
