### ISSUE TITLE
Worker doesn't communicate with controller - slurm

### ISSUE THREAD

**Issue by MatthewBM** [Parsl/parsl#1025]
Hello,

Here is what I'm running on a CentOS system, I'm using the request package to get my public IP:

```

from parsl.channels import SSHChannel
#from parsl.channels import SSHInteractiveLoginChannel
from parsl.providers import SlurmProvider
from parsl.launchers import SrunLauncher
from parsl.providers import KubernetesProvider
#from parsl.launchers import SimpleLauncher

from parsl.config import Config
from parsl.executors.ipp import IPyParallelExecutor
from parsl.executors.ipp_controller import Controller

# This is an example config, make sure to
#        replace the specific values below with the literal values
#          (e.g., 'USERNAME' -> 'your_username')


    #SDSC
from requests import get
ip = get('https://api.ipify.org').text
config_sdsc = Config(
    executors=[
        IPyParallelExecutor(
            label='comet_ipp_multinode',
            provider=SlurmProvider(
                'debug',
                channel=SSHChannel(
                    hostname='comet.sdsc.xsede.org',
                    username='mmadany',     # Please replace USERNAME with your username
                    password=,
                    script_dir='/home/mmadany/parsl_scripts',    # Please replace USERNAME with your username
                ),
                launcher=SrunLauncher(),
                scheduler_options='',     # Input your scheduler_options if needed
                worker_init='source /home/mmadany/.bashrc; conda activate parsl',     # Input your worker_init if needed
                walltime="00:10:00",
                init_blocks=1,
                max_blocks=1,
                nodes_per_block=1,
            ),
            controller=Controller(public_ip=ip,port_range="62000,65000"),    # Please replace PUBLIC_IP with your public ip
        )

    ],
)

import parsl
parsl.clear()
parsl.load(config_sdsc)

from parsl.app.app import python_app, bash_app

@bash_app
def generate(outputs=[]):
    touch /home/mmadany/fromparsl_test
    return "test write success"

print(generate())

```
and this is what I get from the engine job log:

> 
> (parsl) [mmadany@comet-ln2 026]$ tail -f engine_logs/parsl.auto.1560064011.8623514.log
> 2019-06-09 00:05:25.330 [IPEngineApp] Loading url_file 'runinfo/026/ipengine.acb21e24-9e1f-446e-bba3-3bd8729d5a0d.json'
> 2019-06-09 00:05:25.360 [IPEngineApp] Registering with controller at tcp://67.58.56.44:63105
> 2019-06-09 00:05:30.366 [IPEngineApp] CRITICAL | Registration timed out after 5.0 seconds
>

**Comment by benclifford** [comment]
The correct address to use isn't necessarily the address that comes back from that `ipify.org` service - it depends on the network setup of your system. 

Parsl has a module `parsl.addresses` with a few different ways of finding a suitable address. See below. There isn't one which works in all situations though.

What you need is an address that a slurm worker node can connect to your submitting system where you are running parsl. From looking at your setup, I guess that you are running on some personal computer somewhere on a university network; it might be that the kind of network connection this needs isn't even possible due to firewalls, and in that case you might do better to run on a comet login node.

```
import parsl.addresses

ip = address_by_query() # makes the same api.ipify.org call that you have already

ip = address_by_route() # finds a public address by looking for a default route to google

ip = address_by_hostname() # uses the system local hostname rather than an ip

ip = address_by_interface(interface_name) # uses the ip address assigned to a named network interface
```

**Comment by MatthewBM** [comment]
Hi @benclifford, thanks for your response.

I'm hesitant to use the login node because:
1) I'd like to try and configure other clusters
2) it goes down sometimes
3) my initial installation attempt of parsl on the node failed due to a libc incompability

I can confirm the port is open now, and I added a check in my worker_init:
`worker_init='echo "hello comet"; source /home/mmadany/.bashrc; conda activate parsl; nc -z -v -w5 <host address> <port>'
and I can see in the port is open in stdout:
> [mmadany@comet-ln3 ~]$ cat parsl_scripts/parsl.auto.1560310181.9417555.submit.stdout
> hello comet
> Connection to <host address> <port> port [tcp/*] succeeded!
> Found cores : 24
> Found nodes : 1
> Done
> 
now the output in the run_engine logs is:
> 
> 2019-06-11 20:41:36.665 [IPEngineApp] Loading url_file 'runinfo/054/ipengine.9b0589ef-5cc0-4fa2-988b-419f9f0c08ba.json'
> 2019-06-11 20:41:36.695 [IPEngineApp] Registering with controller at tcp://<host address> <port>
> 2019-06-11 20:41:36.744 [IPEngineApp] Starting to monitor the heartbeat signal from the hub every 3010 ms.
> 2019-06-11 20:41:36.749 [IPEngineApp] Completed registration with id 3
> 2019-06-11 20:41:42.768 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (1 time(s) in a row).
> 2019-06-11 20:41:45.778 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (2 time(s) in a row).
> 2019-06-11 20:41:48.787 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (3 time(s) in a row).
> 2019-06-11 20:41:51.798 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (4 time(s) in a row).
> 2019-06-11 20:41:54.808 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (5 time(s) in a row).
> 2019-06-11 20:41:57.818 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (6 time(s) in a row).
> 2019-06-11 20:42:00.828 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (7 time(s) in a row).
> 2019-06-11 20:42:03.838 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (8 time(s) in a row).
> 2019-06-11 20:42:06.848 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (9 time(s) in a row).
> 2019-06-11 20:42:09.857 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (10 time(s) in a row).
> 2019-06-11 20:42:12.868 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (11 time(s) in a row).
> 2019-06-11 20:42:15.878 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (12 time(s) in a row).
> 2019-06-11 20:42:18.888 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (13 time(s) in a row).
> 2019-06-11 20:42:21.898 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (14 time(s) in a row).
> 2019-06-11 20:42:24.908 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (15 time(s) in a row).
> 2019-06-11 20:42:27.917 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (16 time(s) in a row).
> 2019-06-11 20:42:30.928 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (17 time(s) in a row).
> 2019-06-11 20:42:33.938 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (18 time(s) in a row).
> 2019-06-11 20:42:36.948 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (19 time(s) in a row).
> 2019-06-11 20:42:39.957 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (20 time(s) in a row).
> 2019-06-11 20:42:42.968 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (21 time(s) in a row).
> 2019-06-11 20:42:45.978 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (22 time(s) in a row).
> 2019-06-11 20:42:48.988 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (23 time(s) in a row).
> 2019-06-11 20:42:51.998 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (24 time(s) in a row).
> 2019-06-11 20:42:55.008 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (25 time(s) in a row).
> 2019-06-11 20:42:58.018 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (26 time(s) in a row).
> 2019-06-11 20:43:01.028 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (27 time(s) in a row).
> 2019-06-11 20:43:04.038 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (28 time(s) in a row).
> 2019-06-11 20:43:07.048 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (29 time(s) in a row).
> 2019-06-11 20:43:10.058 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (30 time(s) in a row).
> 2019-06-11 20:43:13.068 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (31 time(s) in a row).
> 2019-06-11 20:43:16.078 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (32 time(s) in a row).
> 2019-06-11 20:43:19.088 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (33 time(s) in a row).
> 2019-06-11 20:43:22.098 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (34 time(s) in a row).
> 2019-06-11 20:43:25.108 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (35 time(s) in a row).
> 2019-06-11 20:43:28.118 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (36 time(s) in a row).
> 2019-06-11 20:43:31.128 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (37 time(s) in a row).
> 2019-06-11 20:43:34.138 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (38 time(s) in a row).
> 2019-06-11 20:43:37.148 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (39 time(s) in a row).
> 2019-06-11 20:43:40.157 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (40 time(s) in a row).
> 2019-06-11 20:43:43.168 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (41 time(s) in a row).
> 2019-06-11 20:43:46.178 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (42 time(s) in a row).
> 2019-06-11 20:43:49.188 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (43 time(s) in a row).
> 2019-06-11 20:43:52.198 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (44 time(s) in a row).
> 2019-06-11 20:43:55.208 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (45 time(s) in a row).
> 2019-06-11 20:43:58.218 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (46 time(s) in a row).
> 2019-06-11 20:44:01.228 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (47 time(s) in a row).
> 2019-06-11 20:44:04.237 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (48 time(s) in a row).
> 2019-06-11 20:44:07.248 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (49 time(s) in a row).
> 2019-06-11 20:44:10.258 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (50 time(s) in a row).
> 2019-06-11 20:44:10.258 [IPEngineApp] CRITICAL | Maximum number of heartbeats misses reached (50 times 3010 ms), shutting down.
> ERROR:root:Invalid alias: The name clear can't be aliased because it is another magic command.
> ERROR:root:Invalid alias: The name more can't be aliased because it is another magic command.
> ERROR:root:Invalid alias: The name less can't be aliased because it is another magic command.
> ERROR:root:Invalid alias: The name man can't be aliased because it is another magic command.
>

**Comment by yadudoc** [comment]
Hi @MatthewBM ,

From your log paste above, it does look like an ipengine is able to connect back to the ipcontroller. If you haven't updated your test script already, the issue might be that you invoke a `bash_app` and then don't wait for it's result. Parsl programs exit unless you explicitly wait for the results of apps, and this would also terminate the ipcontroller to which workers connect resulting in workers dying due to missed heartbeats.  Secondly, `bash_apps` are special python functions that are written like they would return a bash script. When execution is complete `bash_apps` will return the exit code. Could you try updating your script like this :

```python
@bash_app
def generate(outputs=[]):
    return """touch /home/mmadany/fromparsl_test 
    """

@python_app
def platform_check():
    import platform
    return platform.uname()

gen_future = generate()
print("Waiting for ", gen_future) # You will print a 
print("generate is now done with exit code: ", gen_future.result())

# For python app:
print("Python app ran on: ", platform_check().result())
```

As for config, here's what I just tested with from a remote node, please note that I'm using our new `HighThroughputExecutor` rather than the `IPyParallelExecutor` which is on its way to getting deprecated.

```python
from parsl.config import Config
from parsl.channels import SSHChannel
from parsl.launchers import SrunLauncher
from parsl.providers import SlurmProvider
from parsl.executors import HighThroughputExecutor
from parsl.addresses import address_by_query


config = Config(
    executors=[
        HighThroughputExecutor(
            label='Comet_HTEX_multinode',
            address=address_by_query(),
            worker_logdir_root='/home/yadunand/parsl_workdir', # <--- Update here
            provider=SlurmProvider(
                'debug',
                channel=SSHChannel(
                    hostname='comet.sdsc.xsede.org',
                    username='yadunand',                                  # <--- Update here
                    script_dir='/home/yadunand/parsl_scripts',   # <--- Update here
                ),
                launcher=SrunLauncher(),
                # string to prepend to #SBATCH blocks in the submit                                                                                                                                                                            
                # script to the scheduler                                                                                                                                                                                                      
                scheduler_options='',
                # Command to be run before starting a worker, such as:                                                                                                                                                                         
                # 'module load Anaconda; source activate parsl_env'.                                                                                                                                                                           
                worker_init='source activate parsl_0.8.0a0_py3.6',    # <--- Update here to how you setup your env
                walltime='00:10:00',
                init_blocks=1,
                max_blocks=1,
                nodes_per_block=2,
            ),
        )
    ]
)

```

**Comment by MatthewBM** [comment]
Hi @yadudoc ,

I don't have worker_logdir_root as an option for HighThroughputExectutor.
I tried commenting it out and running what you sent, and got this from stderr:
```

> 
> (base) [mmadany@comet-ln3 parsl_scripts]$ cat parsl.auto.1560317655.2157164.submit.stderr
> nc: connect to host port 63105 (tcp) failed: Connection refused
> 0: Traceback (most recent call last):
> 0:   File "/home/mmadany/miniconda3/envs/parsl/bin/process_worker_pool.py", line 476, in <module>
> 0:     os.makedirs(os.path.join(args.logdir, args.uid))
> 0:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 0:     makedirs(head, mode, exist_ok)
> 0:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 0:     makedirs(head, mode, exist_ok)
> 0:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 0:     makedirs(head, mode, exist_ok)
> 0:   [Previous line repeated 1 more time]
> 0:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 220, in makedirs
> 0:     mkdir(name, mode)
> 0: PermissionError: [Errno 13] Permission denied: '/home//user'
> 1: Traceback (most recent call last):
> 1:   File "/home/mmadany/miniconda3/envs/parsl/bin/process_worker_pool.py", line 476, in <module>
> 1:     os.makedirs(os.path.join(args.logdir, args.uid))
> 1:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 1:     makedirs(head, mode, exist_ok)
> 1:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 1:     makedirs(head, mode, exist_ok)
> 1:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 210, in makedirs
> 1:     makedirs(head, mode, exist_ok)
> 1:   [Previous line repeated 1 more time]
> 1:   File "/home/mmadany/miniconda3/envs/parsl/lib/python3.6/os.py", line 220, in makedirs
> 1:     mkdir(name, mode)
> 1: PermissionError: [Errno 13] Permission denied: '/home/user'
> srun: error: comet-14-02: task 0: Exited with exit code 1
> srun: error: comet-14-03: task 1: Exited with exit code 1
> 

```

**Comment by MatthewBM** [comment]
I haven't been able to get the HighThroughPut worker to connect, but I'm seeing the controller communicating fine with this script, but it just hangs:
```

config_sdsc_ipy = Config(
    executors=[
        IPyParallelExecutor(
            label='comet_ipp_multinode',
            provider=SlurmProvider(
                'debug',
                channel=SSHChannel(
                    hostname='comet.sdsc.xsede.org',
                    username='mmadany',     # Please replace USERNAME with your username
                    script_dir='/home/mmadany/parsl_scripts',    # Please replace USERNAME with your username
                ),
                launcher=SrunLauncher(),
                scheduler_options='',     # Input your scheduler_options if needed
                worker_init='echo "hello comet"; source /home/mmadany/.bashrc; conda activate parsl; nc -z -v -w5 pestilence.crbs.ucsd.edu 63105',     # Input your worker_init if needed
                walltime="00:10:00",
                init_blocks=1,
                max_blocks=1,
                nodes_per_block=1,
            ),
            controller=Controller(public_ip=ip,port="63105"),    # Please replace PUBLIC_IP with your public ip
        )

    ],
)


from parsl.app.app import python_app, bash_app
import parsl
parsl.clear()
parsl.load(config_sdsc_ipy)

@bash_app
def generate(outputs=[]):
    return """touch /home/mmadany/fromparsl_testfile
    """
    
gen_fut = generate()
print(" Wait: ", gen_fut)
print(" Finished: ", gen_fut.result())

```

**Comment by MatthewBM** [comment]
Hi @yadudoc 

I'm realizing I'm not grasping the abstractions surrounding bash apps, data, and cluster configs. I'm going to do the binder tutorials and come back if I have further questions.
