### ISSUE TITLE
CPU User Time plot is strangely cumulative

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1033]
The CPU User Time plot looks like it shows something like: cumulative CPU time for tasks that are running right now (but not tasks that have finished).

That plot might more interestingly show cumulative CPU time for all task that are running right now, or were running at some point in the past - something that better approximates the CPU time used by the workflow as a whole, over time.

![newplot (1)](https://user-images.githubusercontent.com/280107/59189807-a1de3780-8b6a-11e9-93f5-b6e9746bd04a.png)

**Comment by annawoodard** [comment]
> That plot might more interestingly show cumulative CPU time for all task that are running right now, or were running at some point in the past - something that better approximates the CPU time used by the workflow as a whole, over time.

Agreed. 

I think we should build plots with the questions in mind they are trying to answer. For example: what is the resource bottleneck for my workflow? How many total resources is my workflow using? I'm not sure what question the current "cpu user time" plot is answering.

![resources](https://user-images.githubusercontent.com/5114833/59210275-d81fb500-8b72-11e9-9690-27c8f42b2598.png)

I think something like this would be useful, where we can compare the total amount being used to the total amount available/being charged for. In this example the workflow is CPU-limited. If the total and committed were on top of eachother for memory, we'd be able to quickly spot that the workflow was memory-limited. 

A separate question is: am I efficiently using the resources I've been allocated? There are various levels to that. How efficiently are you using each core, and how efficiently are tasks packed on the node? I think the relevant metric for the former is CPU time / wall time.

**Comment by ZhuozhaoLi** [comment]
Think this is duplicated with #1108 and fixed by #1192 ?

**Comment by benclifford** [comment]
yes
