### ISSUE TITLE
Automatic checkpointing

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#106]
Checkpointing is currently manually triggered by the user. It would be convenient if users could specify automatic checkpointing at a given frequency and/or after each task completes.

As requested by @djf604.

**Comment by yadudoc** [comment]
From the discussion with @djf604, this should have high priority given user triggered checkpointing has limited usability. I can start adding functionality to support this with the following modes (copied over from the previous issue : #43 

1. (eager) checkpoint at the completion of every task or
2. (lazy) at configurable intervals (say ~1hr).
3. (atExit) write out a checkpoint when the DFK exits, capturing early termination from app failures,
uncaught exceptions, keyboard interrupts etc. This won't work for cases when the DFK is killed abruptly (SIGKILL), machine powered off etc.

**Comment by annawoodard** [comment]
@yadudoc Sounds good to me. I vote for a minor tweak to the naming scheme. I would guess without documentation that "lazy checkpointing is only performed when it is needed", not "lazy checkpointing is performed at regular intervals". Here's a possibility:

```
checkpoint=None # default, no checkpointing
checkpoint='periodic' # configurable intervals
checkpoint='task_exit'
checkpoint='dfk_exit'
```
