### ISSUE TITLE
App execution on remote cluster doesn't work

### ISSUE THREAD

**Issue by MatthewBM** [Parsl/parsl#1071]
Here is what I'm trying to run:

```
from parsl.app.app import python_app, bash_app
from parsl.channels import SSHChannel
from parsl.providers import SlurmProvider
from parsl.launchers import SrunLauncher
from parsl.config import Config
from parsl.executors.ipp import IPyParallelExecutor
from parsl.executors.ipp_controller import Controller
from parsl.addresses import address_by_query


    #SDSC
config_comet = Config(
    executors=[
        IPyParallelExecutor(
            label='comet_ipp_multinode',
            working_dir='/oasis/scratch/comet/mmadany/temp_project/parsl',
            provider=SlurmProvider(
                'debug',
                channel=SSHChannel(
                    hostname='comet.sdsc.xsede.org',
                    username='mmadany',     # Please replace USERNAME with your username
                    script_dir='/home/mmadany/parsl_jobs',    # Please replace USERNAME with your username
                ),
                launcher=SrunLauncher(),
                scheduler_options='#SBATCH -A DDP140',     # Input your scheduler_options if needed
                worker_init='source /home/mmadany/.bashrc; conda activate parsl',     # Input your worker_init if needed
                walltime="00:10:00",
                init_blocks=1,
                max_blocks=1,
                nodes_per_block=1,
            ),
            controller=Controller(public_ip=address_by_query(),port='63105'),    # Please replace PUBLIC_IP with your public ip
        )
    ],
)


import parsl
parsl.clear()

@python_app
def generate(limit):
      from random import randint
      return randint(1,limit)
#local execute
from parsl.configs.local_threads import config
parsl.load(config)
message = generate(10)
print('Random number: %s' % message.result())

#remote execute
parsl.clear()
parsl.load(config_comet)
message = generate(10)
print('Random number: %s' % message.result())
```

The local execution app runs fine but when trying to run on the cluster, the command just hangs indefinitely. I tried using HighThroughputExecutor but that wouldn't even start the job or launch a controller. With ipyparrrelel I can at least see the job running and the worker communicating with the controller, but nothing happens...

Here's the runinfo from the local machine:
[084.zip](https://github.com/Parsl/parsl/files/3293783/084.zip)

**Comment by ZhuozhaoLi** [comment]
Hi @MatthewBM , from the logs, it seems the worker cannot connect to the controller
`Executor comet_ipp_multinode has 1 active tasks, 0/0/0 running/submitted/pending blocks, and 0 connected engines`.

I think you might want to make sure the worker nodes can actually connect to the controller via the IP address returned by `address_by_query()` utils. It would be great if you can post your job `stderr` and `stdout`.

**Comment by MatthewBM** [comment]
Hi @ZhuozhaoLi 

Here is the contents of stdout from the login node:

> getting Parsl version
> 0.7.2
> Found cores : 24
> Found nodes : 1
> Done
> 
stderr is empty

How can I be sure the worker nods can connect to controller? I tried putting `'echo "checking if port is open"; nc -z -v -w5 %s 63105' % address_by_query()` into woker_init  and this is what I get from stdout:
`
cat parsl.auto.1560708652.0526798.submit.stdout`
> getting Parsl version
> 0.7.2
> checking if port is open
> Connection to 67.58.56.44 63105 port [tcp/*] succeeded!
> Found cores : 24
> Found nodes : 1

Also when I change my config, how do I reset the config with `parsl.load()`? I've been trying` parsl.clear() parsl.load(config) `but it just hangs. The only way I've gotten it to reload the config is if I do `pkill ipcontroller` on the cmd for the local machine.

**Comment by ZhuozhaoLi** [comment]
One other thing to check is the logs in `'runinfo/083/engine_logs'` on comet.

Maybe we can jump on a call tomorrow on Monday to debug. Does it sound okay to you?

`parsl.clear()` should reset the config. 
If that does not help, you could try:
```
dfk = parsl.load(config1)
del dfk
parsl.clear()
parsl.load(config2)
```

**Comment by MatthewBM** [comment]
Yes Monday would be great, can you email me matthew.madany@gmail.com to setup.

**Comment by MatthewBM** [comment]
Parsl needs several ports open to run properly
