### ISSUE TITLE
Sqlalchemy version requirement is too narrow

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1102]
To work ariound the issue with sqlalchemy version 1.3.4 spewing warning message we updated our requirements file to specify `sqlalchemy==1.3.3`. This is needlessly narrow and we've run into a version incompatibility issue with the DESC stack on NERSC. 

Might be solved by updating this to `sqlalchemy>=1.3.0,<1.3.4`. 

More background here: #997

**Comment by dgasmith** [comment]
Thats a pretty narrow pin that wouldn't work for us either. We could likely help you fix the patch issues that you are having, but please only pin to minor at the most.

**Comment by yadudoc** [comment]
@Lnaden recommend this string -> `sqlalchemy>=1.3.0,!=1.3.4`

**Comment by Lnaden** [comment]
I would verify that 1.3.5 works first, and if it does, that string can avoid it, although it would be simpler to just lower bound as 1.3.5 if it does

**Comment by yadudoc** [comment]
The DESC community reported that their stack is still on `1.3.1`, so the more lenient string would work better for the time being.
