### ISSUE TITLE
Cumulative CPU time loses time when subprocesses end

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1108]
Monitoring accumulates time used by a process, for example, `psutil_process_time_user` both for the executing process and for any still-alive children.

However it does not keep the time used by any exited children -  when a child process exits, the CPU time for that child disappears from `psutil_process_time_user`, and the CPU time used reduces.

It would probably be a more useful metric to have this field accumulate all child process cpu usage, even exited children, so that it is monotonically increasing, and so that the final value gives a decent estimate of the CPU used by all processes spawned in the task.

This maybe related to #1033, which is visualization related.

**Comment by ZhuozhaoLi** [comment]
If that is the case, we need to fix that. Perhaps use a local dict to store the values of exited child processes
