### ISSUE TITLE
Switch to Jenkins

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#121]
This has been discussed before, I'm just creating an issue to keep track of it. @yadudoc has gotten a nice Jenkins server setup. This can do everything Travis can do + tests where we actually run on remote resources (because we can set up private keys on it). So for simplicity we should move the current nosetests and linting to Jenkins, so everything is done in the same place.

**Comment by benclifford** [comment]
this has been overtaken by the passage of time, and we're running ok in github actions these days. closing.
