### ISSUE TITLE
Hosted notebook link is broken

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#124]
It appears this link in the documentation is broken [http://try.parsl-project.org/](http://try.parsl-project.org/).

**Comment by yadudoc** [comment]
Can you try again now ? Looks like the python server for the redirect link died.

**Comment by annawoodard** [comment]
It is working now, thanks! Maybe we can start a cron job or something else to check if the server is up?

**Comment by annawoodard** [comment]
Meh, I vote we remember this and do that NEXT time it goes down. :smile:. Closing for now. Thanks @yadudoc!

**Comment by annawoodard** [comment]
> I vote we remember this and do that NEXT time it goes down. 😄.

Looks like 'next time' is now 😞 as noted by @danielskatz. Re-opening.

**Comment by annawoodard** [comment]
Fixed by @yadudoc
