### ISSUE TITLE
process_worker_pool can hang if a worker dies mid-task

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1245]
I've encountered a situation where a process_worker worker process is getting killed during task execution/result serialisation.

That's pretty obscure; however process_worker_pool as a whole does not continue working properly - that task is never seen as failed by the main parsl process (until the whole pool dies for example by running out of batch job walltime)

**Comment by benclifford** [comment]
Another case I think I have noticed this happening is when running inside `srun` on `cori`, when a bash app tries to run, and that app fails, then this sort of thing happens which I think might be killing the corresponding worker process without the manager noticing.

```
cat runinfo/025/task_logs/0000/task_0004_ingest.stderr
--> executable follows <--
ingestDriver.py /global/cscratch1/sd/bxc/parslTest/test0 /global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1.1i/sim/agn-test/00385844to00445379/00425529/lsst_a_425529_R03_S21_y.fits --cores 1 --mode link --output /global/cscratch1/sd/bxc/parslTest/test0 -c clobber=True allowError=True register.ignore=True
--> end executable <--
/tmp/tmpb2spzmc5: line 618: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
/tmp/tmpb2spzmc5: line 618: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
[mpiexec@nid01343] HYDU_create_process (utils/launch/launch.c:75): execvp error on file srun (No such file or directory)
[mpiexec@nid01343] HYDU_sock_write (utils/sock/sock.c:294): write error (Bad file descriptor)
[mpiexec@nid01343] HYD_pmcd_pmiserv_send_signal (pm/pmiserv/pmiserv_cb.c:177): unable to write data to proxy
[mpiexec@nid01343] ui_cmd_cb (pm/pmiserv/pmiserv_pmci.c:79): unable to send signal downstream
[mpiexec@nid01343] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@nid01343] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:198): error waiting for event
[mpiexec@nid01343] main (ui/mpich/mpiexec.c:340): process manager error waiting for completion
```

**Comment by annawoodard** [comment]
We need more machinery in the pool to deal with this properly-- we can see that a process died, but we have no way of knowing which task it was working on. One option is adding a shared dict via which the manager can track who is working on what.
