### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by monicadlewis97** [Parsl/parsl#13]
There seems to be a bug preventing the recursive fibonacci test running with Ipython parallel from passing. Although it passed the Travis CI check, it's not working on my local machine.

**Comment by yadudoc** [comment]
@monicadlewis97  Can you check if this is still failing ?

**Comment by monicadlewis97** [comment]
@yadudoc its still failing

**Comment by yadudoc** [comment]
@kylechard  @mjwilde  I'm considering a no fix for this one. We should probably discuss.
