### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#1329]
the parsl project needs a code of conduct

**Comment by danielskatz** [comment]
here's an example: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md

**Comment by dgasmith** [comment]
Another possibility is the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). @danielskatz Do you have general recommendations or thoughts on how to pick CoCs?

**Comment by danielskatz** [comment]
> Do you have general recommendations or thoughts on how to pick CoCs?

no, not really - I just tend to follow the examples of projects that I think work well

**Comment by danielskatz** [comment]
We now have https://github.com/Parsl/parsl/blob/master/CoC.md

And the README includes a link to this.

The last item needed for this issue is potentially one or more links in readthedocs to the CoC, but I'm not sure where to add this.  Any suggestions (or PRs) from others so that we can close this issue would be welcome

**Comment by benclifford** [comment]
https://parsl.readthedocs.io/en/latest/devguide/contributing.html
https://github.com/Parsl/parsl/blob/master/CONTRIBUTING.rst

**Comment by danielskatz** [comment]
addressed in https://github.com/Parsl/parsl/pull/1537/ and https://github.com/Parsl/parsl/pull/1538

**Comment by danielskatz** [comment]
I think we've now made enough process on this that this issue can be closed - we have an initial CoC and a number of links to it. Let's see how it works out, and if any more links or changes in the CoC are needed, a new issue can be created.  Thanks to @benclifford for quickly reviewing and merging changes to make this happen
