### ISSUE TITLE
Switch to class-based configuration

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#133]
This was discussed at the meeting yesterday.

**Comment by annawoodard** [comment]
For example, instead of
```python
singleNode = {
  "sites": [
    {"site": "Local_IPP",
      "auth": {
        "channel": "ssh",
        "hostname": "swift.rcc.uchicago.edu",
        "username": os.environ['MIDWAY_USERNAME'],
        "scriptDir": "/scratch/{0}/parsl".format(USERNAME)
      },
      "execution": {
        "executor": "ipp",
        "provider": "slurm",
        "block": {  # Definition of a block
           "nodes": 1,            # of nodes in that block
           "taskBlocks": 1,       # total tasks in a block
           "initBlocks": 1,
           "maxBlocks": 1,
            "options": {
               "partition": "westmere",
               "overrides": '''module load python/3.5.2+gcc-4.8'''
            }
        }
      }
    }
 ],
 "globals": {"lazyErrors": True}
}
```
we could have
```python
from parsl.config import Config
from libsubmit.providers.slurm.slurm import Slurm

user = os.environ['MIDWAY_USERNAME']

config = Config(
    [
        Site(
            'local_IPP',
            channel=SSHChannel(
                hostname='swift.rcc.uchicago.edu',
                username=user,
                script_dir='/scratch/{0}/parsl'.format(user)
            ),
            provider=Slurm(
                executor='ipp',
                nodes=1,
                task_blocks=1,
                init_blocks=1,
                max_blocks=1,
                partition='westmere',
                overrides=''''module load python/3.5.2+gcc-4.8'''
            )
        )
    ],
    globals={'lazy_errors': True}
)
```
One advantage would be that if someone handed off the above config to you, finding the relevant documentation interactively would be more natural:
```
>>> help(Slurm)

Help on class Slurm in module libsubmit.providers.slurm.slurm:

class Slurm(libsubmit.providers.provider_base.ExecutionProvider)

| Slurm Execution Provider
|
| This provider uses sbatch to submit, squeue for
| status and scancel to cancel jobs. The sbatch
| script to be used is created from a template file
| in this  same module.
```

Additionally, the documentation could be written more clearly, and defaults could be specified in the constructor signature (and so would be self-documenting) (left is current, right is proposed option)
![screen shot 2018-04-17 at 6 27 48 pm](https://user-images.githubusercontent.com/5114833/38903961-1fef2a5a-426d-11e8-83f6-77edc2b97724.png)

Another advantage would be that the proposed `Config` class could be completely specified in its own documentation in a straightforward way (which pieces are required, what defaults will be used, etc). Currently we lean heavily on showing examples rather than having a clear specification.

Relevant user feedback from the help channel:
> I don't know that I have anything specific, I just feel like I don't know how to do anything related to configuration haha
Like, I don't know what's required, what's possible, etc


This is related to Parsl/libsubmit#22; switching to class-based configs would allow the (currently non-existent) validation to be done more naturally in the constructors of each component, allowing for interactive  validation in notebooks (i.e., you are not sure if your config is correct, so you instantiate an instance of `Config` and immediately get an error raised; you can keep tweaking things interactively until you have a valid config).

Here are a few [slides](https://github.com/Parsl/parsl/files/1921918/slides.pdf) from the meeting.

**Comment by annawoodard** [comment]
Another advantage would be that we could get rid of redundant fields, for example here from the [Slurm](https://libsubmit.readthedocs.io/en/latest/devguide/dev_docs.html#slurm) provider documentation, where the executor must be IPP:
```
     "executor"   : #{Description: Define the executor used as task executor,
                    # Type : String,
                    # Expected : "ipp",
                    # Required : True},
```

**Comment by benclifford** [comment]
This is an opportunity to refactor configuration hierarchy, but that opportunity is distinct from it being python/json based.

I support this proposal (and for the reasons @annawoodard has described in slides) as long as the intention is that configurations are written in python land: for example, if it is expected that configurations are written by the same people writing python application code; or are being generated by python generation code.

(counterexamples: sysadmins writing configurations for their users - where neither is a python programmer; someone writing a config generator in a different language - I think those are quite weak examples, though)

**Comment by lukaszlacinski** [comment]
There is no relation between an executor and a Globus endpoint, so an information about a Globus endpoint should not be a part of executors configuration. A Globus endpoint is related to a site by providing a way to access a site filesystem.

**Comment by annawoodard** [comment]
To summarize a chat on Slack with @lukaszlacinski and friends: this proposal is dispensing with the term `site`, and the structure is not changing from what is currently in place. There was a lot of related discussion which @yadudoc will open in a separate issue.
