### ISSUE TITLE
Quickstart, accessed from https://github.com/Parsl/parsl-tutorial

### ISSUE THREAD

**Issue by ianfoster** [Parsl/parsl#1333]
From https://github.com/Parsl/parsl-tutorial, I see link to https://parsl.readthedocs.io/en/latest/quickstart.html, which says:
    You'll also need gcc to be installed in order to run Parsl.
    $ gcc --version
I asked people and they seem to think that is not correct?

**Comment by yadudoc** [comment]
Hi @ianfoster , I believe @macintoshpie added that to the quickstart docs after he ran into gcc requirements on MacOS. I'd guess that if you are pulling packages from Pypi you'd need the build tools, while that might not be necessary when using conda.

I'll check this with a mac user and confirm.

**Comment by yadudoc** [comment]
@tskluzac Can you help with debugging this ?
