### ISSUE TITLE
Add mechanism to flush tasks from DFK

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1347]
**Is your feature request related to a problem? Please describe.**
Currently we store a lot of information about tasks in the DFK. Unfortunately, since the DFK has no mechanism to auto-identify what tasks can be garbage collected, it keeps everything. This can bloat up pretty quickly if you are building a long running service on top of Parsl

**Describe the solution you'd like**
Add a mechanism to flush tasks from the DFK : 
```python
dfk = parsl.dfk()
dfk.flush(<list of task_ids>)
```

**Describe alternatives you've considered**
N/A

**Additional context**
Requested by @dgasmith at Parslfest,

**Comment by dgasmith** [comment]
This is becoming a larger issue now that we leave Parsl instance running for weeks to months that handle multiple millions of tasks.

**Comment by yadudoc** [comment]
@dgasmith On it.

Some thoughts on how we could do this properly. 

Python3 uses a combination of reference counting and generational garbage collection internally
for garbage collection. The DataFlowKernel keeps track of every future in it's internal
task graph which leads to live references that prevent Python's GC from reaping futures (and it's data)
even when no references are held in the main context.

1. We need to differentiate between references held inside the DFK vs outside it.
   We can assume that the task graph inside the DFK will not generate additional references, only additional indirections.
   For example `TaskA <---- TaskB` might transform to `TaskA <--- stage_out() <---- stage_in() <---- TaskB`
   
   Currently these data stageing tasks are the only additional operations that the DFK would insert into the task graph.
   
2. Ideally we make minor changes that enable Python's GC to step in and handle dead data.

   * We can assume that if a live reference exists in the main context the future should not be deleted.
   * If there are no live references outside the DFK no additional references will be added.
   * Once a task is completed and *all* it's dependents used their references to it, then it should be safe to GC
   
So, we could mark a future as a weakref upon resolving and delete it's dependencies, such that the reference counts
within the DFK are updated correctly. Therefore, if no references exist in the main context, the future would be
garbage collected.

If we go this route, the user will be able to flush task by calling `del app_future` rather than having to ask the dfk to flush the tasks, which I think is cleaner.

**Comment by dgasmith** [comment]
Overall this sounds good, but does seem fairly involved. I am unsure how transferable our use case is.

It we can simply delete a DFK and rebuild periodically that could work as well.

**Comment by yadudoc** [comment]
Hi @dgasmith, quick heads up that this implemented properly in master now. The DFK will now clear tasks from the internal table only tasks have completed.

**Comment by dgasmith** [comment]
Great, we will check it out!

**Comment by benclifford** [comment]
@yadudoc @dgasmith - does DFK removal now present in master resolve this issue?

**Comment by dgasmith** [comment]
Reading through the code it should. I don't have something at scale to checkout, perhaps @bennybp or @lnaden could take a look.

**Comment by benclifford** [comment]
Closing this as no complaints on the implementation since May.
