### ISSUE TITLE
API to request resource status from the DFK

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1348]
**Is your feature request related to a problem? Please describe.**
Currently our support for reporting resources is pretty limited. We have added support to the 
`HighThroughputExecutor` to report status of total/active workers, but this needs to be expanded to support the following: 

We need the following broken down by executor.
* Total tasks pending / running / done  
* Total workers pending (requested)  / active (running tasks) / total

**Describe the solution you'd like**
```python
dfk  = parsl.dfk()
dfk.get_worker_status()
dfk.get_task_status()
```

**Describe alternatives you've considered**
We might be limited here by what different executors support, so we might have support for these methods limited to HTEX to start with. Open to discussion here :)

**Additional context**
Requested by @dgasmith  at Parslfest

**Comment by benclifford** [comment]
This is probably mostly addressed by parsl's monitoring functionality.

**Comment by yadudoc** [comment]
Agreed. Closing.
