### ISSUE TITLE
Take advantage of WQ categories

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1351]
@tjdasso has done some great work tackling #1324. As soon as core/mem/disk specification is merged (the core specification is already implemented in his branch), we will have the ability to tell WQ specific resource requirements for a task. A next step that I think would be extremely useful would be to implement the missing pieces in order to make WQ aware of what category the task is in (as a first pass, we can try just using the app name as a category). This will allow us to take advantage of WQ's ability to optimally size tasks, using the specified resource requirements as a first guess.

For another project I'm implementing some bioinformatics pipelines, so I would be an enthusiastic tester for this use case.

**Comment by annawoodard** [comment]
cc @dthain, @btovar, @tjdasso

**Comment by dthain** [comment]
@trshaffer please comment here on the task category capability in the latest WQ executor.

**Comment by trshaffer** [comment]
I have a PR in (#1677) that does exactly what @annawoodard proposes. I added two options: one to automatically assign a fresh category for each function, and one to turn on WQ's automatic resource labeling. With both of these turned on, WQ should be able to do a pretty OK job of figuring out resource requirements automatically and subdividing large workers.

**Comment by trshaffer** [comment]
Now that #1677 is merged, this should be resolved
