### ISSUE TITLE
Parsl 0.5.0 release preparation

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#142]
Code must be frozen by Friday, Mar 23, 2018.

- [x] All PRs merged
- [x] All new features documented
- [ ] All new features added to the tutorial, if applicable
- [ ] Unit and integration tests run by as many people as possible
  - [ ] @yadudoc 
  - [ ] @kylechard 
  - [ ] Please add your name here if you are able to help with this!
  - [ ] Testing **must** be done on a Linux and a Mac
- [ ] Scale tests are completed and posted (details TBD)
- [x] Update changelog
- [ ] Update tmpnb
- [ ] Post announcement to users 
- [ ] Update readme/notes with latest version info
- [ ] Update tutorial
- [ ] Update website and news.

**Comment by annawoodard** [comment]
We can edit the above to add TODOs as needed, this is just a starting point.

**Comment by annawoodard** [comment]
@yadudoc I'm confused about your tick under
> Unit and integration tests run by as many people as possible

Are you referring to just the tests that are run by Travis?

**Comment by yadudoc** [comment]
Yep. I ran all the tests that travis runs, stress and site specific tests. I guess this still doesn't cover all our tests.

**Comment by annawoodard** [comment]
Thinking about this more, because this is the first time we are doing it and we don't have anything to compare to, I don't think we need to finish "Scale tests are completed and posted" as a pre-req for putting out the release. We just need to make sure it is done with 0.5 before the next release.

**Comment by annawoodard** [comment]
@yadudoc should we add containers to the tutorial?

**Comment by yadudoc** [comment]
Let's add containers to tutorials once we decide that it is no longer in an experimental state. Agreed on not blocking the release for scale/stress tests.

**Comment by annawoodard** [comment]
Sounds good. I'll open an issue so we don't forget.
