### ISSUE TITLE
LocalProvider+LocalChannel discards stdout/stderr of launched command

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1444]
**Describe the bug**
LocalProvider+LocalChannel directs stdout/stderr of the submitted command into a pipe that is then not used.

This means that stdout/err from the command is lost.

**To Reproduce**
Run HTEX with LocalProvider+LocalChannel+SingleNodeLauncher. The "Found cores :" message from SingleNodeLauncher does not appear in a log file.

**Expected behavior**
This output should not be discarded. For example, with slurm, the output of the executed batch job goes into a log file alongside the batch job submit file.

**Environment**
parsl master ea8333c3249fdf3b21691b7a66fb4e9c8ed37ec0

**Comment by benclifford** [comment]
the plan in #1448 should resolve this, as the non-LocalChannel code path directs output to a file

**Comment by WardLT** [comment]
Following up on the reference in #1620, not using the buffered stdout/stderr can even lead to stalling if the command produces enough output.

The stalling is particularly common when using Tensorflow-enabled apps, which produce a lot of stderr.
