### ISSUE TITLE
Request to redirect cmd_parsl* and wrap-container* files.

### ISSUE THREAD

**Issue by TomGlanzman** [Parsl/parsl#1455]
During the execution of a workflow, the working directory fills  up with files of the sort:

wrap-container.nid02519.11561.1573864860.9112365
  and
cmd_parsl.auto.1573848735.3809993.sh

Ordinary task stdout/stderr also go there by default, but I have overridden that in my workflow script.  To keep these files organized by run, my request is that one can redirect these files elsewhere, preferably into the runinfo/NNN directory tree.

Thank you.

**Comment by benclifford** [comment]
For some context:

cmd_parsl.auto in this workflow is being created by SrunLauncher, always in the cwd.

wrap-container* is an intermediate file produced by the workflow to wrap bash apps in containers; there is an interaction here with checkpointing: moving these wrap-container files to runinfo/NNN/ will give a different bash app command line (as that file name is placed in the bash_app commandline), and so will not be regarded as the "same" command run in a previous run.

**Comment by benclifford** [comment]
The `cmd_parsl.auto.*` files are created in the default directory that a batch job runs in. That directory can usually be changed at provider level by putting a `cd /wherever` command in the `worker_init` parameter of the relevant provider. That will cause the directory to be changed just before those files are written out (by the chosen `Launcher).

The `wrap-container*` files that Tom mentions were DESC application specific and not part of parsl. We're not using parsl level checkpointing any more there, so the checkpointing considerations don't apply.
