### ISSUE TITLE
One method of getting useful ip address returns error page

### ISSUE THREAD

**Issue by lgray** [Parsl/parsl#1456]
**Describe the bug**
In a PR build of coffea we see
```
DEBUG    parsl.executors.high_throughput.executor:executor.py:269 Launch command: process_worker_pool.py   -a 172.17.0.1,10.30.4.170,127.0.0.1,<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>,travis-job-5d7410aa-227a-4b52-876a-d84aa0c8635e -p 0 -c 1 -m None --poll 10 --task_port=54980 --result_port=54886 --logdir=/home/travis/build/CoffeaTeam/coffea/runinfo/000/coffea_parsl_default --block_id={block_id} --hb_period=30 --hb_threshold=120 
```

We can see here that the launch command is not being rendered correctly.

**To Reproduce**
This bug is transient and based on the return of some website you are accessing.

**Expected behavior**
The list of ip addresses should not include an html error string.

**Environment**
 - OS: ubuntu xenial 
 - 3.6
 - zipball of master on 20 November 2019 @ roughly 11:00am

**Distributed Environment**
- Travis CI testing VM
- Locally

**Comment by benclifford** [comment]
This is almost definitely coming from `address_by_query()`. Better behaviour for that function would be to throw an exception rather than return a non-IP address.

**Comment by benclifford** [comment]
crossref #1475

**Comment by benclifford** [comment]
#1555 adds more exception handling around this code.

It should not fail in this particular way any more.

However, if code is implicitly relying on address_by_query() to discover a valid IP address, because it none of the other methods work, then the same scenario that caused this failure will cause a different failure in parsl.

**Comment by lgray** [comment]
Awesome! Thank you!
