### ISSUE TITLE
HTExecutor should report an error when run on MacOS

### ISSUE THREAD

**Issue by ianfoster** [Parsl/parsl#1458]
**Describe the bug**
When HTExecutor is run on MacOS, it hangs, rather than failing. Long term, it would be good if it ran correctly, but until then, it will be good if it reports an error. 

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl with Python 3.7 on my laptop
2. Run a test script
3. Wait, but in vain, for it to complete

**Expected behavior**
When I run a Parsl program with HTExecutor on MacOS, I want it to fail rather than hang.

**Environment**
- MacOS
- Python3
- Latest Parsl as of SC'19

**Distributed Environment**
- Running on my laptop
- Workers running on same laptop

**Comment by benclifford** [comment]
crossref similar issue: https://github.com/Parsl/parsl/issues/854

**Comment by yadudoc** [comment]
#1469 fixed this.
