### ISSUE TITLE
Monitoring visualization show negative CPU usage with retries

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#1494]
**Describe the bug**
Currently, the logged CPU time in monitoring db is cumulative. This works for most of the cases, except when a task is failed and retried. As a result, multiple figures in the visualization will show a sawtooth.

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl master with Python 3.6 on cluster
2. Run all the tests and open the visualization
3. See error

**Expected behavior**
Each retried task should be on a new row.

**Possible solution**
Add a new column (e.g., `retries`) to the table as a new primary key.
Fix visualization based on that

**Comment by benclifford** [comment]
PR #1808 switches resource utilisation to be keyed by try identity, not by task identity. That should address the database side of this issue, although probably not visualization of the information in parsl-visualize.
