### ISSUE TITLE
Remove IPyParallel executor

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1548]
**Is your feature request related to a problem? Please describe.**
The parsl ipp code isn't really maintained any more. As I try to tidy up some stuff in the test suite I find myself spending more time than I'd like to debugging what is happening inside the IPP  parsl executor, while at the same time the folklore is "don't use IPP".

**Describe the solution you'd like**
I'd like to remove all IPP tests from the test suite now. This will inevitably lead to the ipp code rotting fast, and so in addition the IPP executor should probably be removed in its entirely.

**Describe alternatives you've considered**
An alternative is to put developer effort into maintaining IPP as a supported executor.

**Additional context**
The folklore on slack seems to be "don't use IPP". This feature request turns that folklore into reality.

I invite comment in support or against from @kylechard @yadudoc @annawoodard especially as regards how this would affect existing users who have not moved to htex (if any?).

see #1328

**Comment by annawoodard** [comment]
I strongly support removing IPP.

**Comment by yadudoc** [comment]
My vote is on removing IPP from tests and clarifying in docs that it is no longer supported. I would defer removing it entirely from the codebase for later.

**Comment by annawoodard** [comment]
What is the point of having something that isn't being tested (and therefore we can assume isn't working 😆) in the codebase?

**Comment by yadudoc** [comment]
I think it would be nicer to the users to have a release go out that warns anyone using IPP of the impending deprecation before we drop it entirely. Same process as planned for #1553

**Comment by annawoodard** [comment]
Sounds good, but after we depreciate, let's open an issue to remind us to remove it after the depreciation period has ended.

**Comment by benclifford** [comment]
> I think it would be nicer to the users to have a release go out that warns anyone using IPP of the impending deprecation before we drop it entirely.

If we're intending users to use it, we should be testing it. Otherwise, what is the response to broken IPP when a user reports it?

**Comment by annawoodard** [comment]
Thinking about it more, I agree with Ben. I think these are our two options:

1. Add depreciation warnings in next release, continue testing until the following release, when we completely remove IPP and IPP testing.
2. Add retroactive depreciation warnings (if someone tries to use IPP, we tell them to install the previous release) and remove IPP and IPP testing now.

I slightly favor option 2.

**Comment by kylechard** [comment]
I vote for option 2. If people really need to use IPP then they can use an old version of Parsl until its time to update. I can't think of a single situation where IPP would work and HTEX would not.

**Comment by benclifford** [comment]
This was noted in the docs as deprecated as of 0.8, in 78cac3d5a9

**Comment by benclifford** [comment]
@kylechard :

>  I can't think of a single situation where IPP would work and HTEX would not.

One specific situation is the docker / container_image support documented here: https://parsl.readthedocs.io/en/latest/userguide/containers.html#id1

That isn't tested in CI and the documentation is sufficiently out of date to refer to `libsubmit`.

**Comment by yadudoc** [comment]
@benclifford Are we waiting on anything in order to close this one ?

**Comment by benclifford** [comment]
@yadudoc  yes - remove the ghostly stubs of IPP that were put in by #1565 sometime after the next release
