### ISSUE TITLE
Make Python3.6 the minimum requirement for Parsl

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1553]
**Is your feature request related to a problem? Please describe.**
Supporting Py3.5 has slowly become a hassle. For eg. these have changed for the better:
1. fspath objects are only supported in 3.6+
2. fstrings are supported in 3.6+.
3. Bunch of improvements in the typing module 

**Describe the solution you'd like**
Push requirements to 3.6+

**Additional context**
The daily download proportion plot shows that Python3.6 downloads make up the majority of the downloads. This shows that only a tiny fraction of the user base might be affected by discontinuing support for 3.5.
https://pypistats.org/packages/parsl
This requires feedback from users.

**Comment by benclifford** [comment]
We could make `master` now strongly warn users of 3.5 that this version is deprecated, and then end support for 3.5 in two releases time.

**Comment by danielskatz** [comment]
This is a great idea, and a good policy for use to implement more generally

**Comment by annawoodard** [comment]
I support depreciating 3.5

**Comment by kylechard** [comment]
I agree we should deprecate 3.5. I like Ben's idea of noting now that 3.5 support will end in one-two releases time.

**Comment by benclifford** [comment]
PR #1557 adds a deprecation warning issued at DFK initialization on Python < 3.6, stating that Parsl 0.10 will be the last version supporting earlier versions.

After the 0.10 release, this warning could turn into a RuntimeException for one or more future releases, and perhaps be eventually removed.

**Comment by yadudoc** [comment]
Assuming the next release is 1.0 and the one after will be 1.1, I'm retagging this for 1.1.

**Comment by benclifford** [comment]
Docs also contain at least one reference to python 3.5 specific behaviour (in docs/futures.rst). When 3.5 support is removed, grep for `3.5` in the docs and tidy.

**Comment by benclifford** [comment]
done in  #1753, #1758
