### ISSUE TITLE
GridEngine provider mis-parses wall times, treating minutes as seconds

### ISSUE THREAD

**Issue by benhg** [Parsl/parsl#1556]
**Describe the bug**
The GridEngine system expects walltime in seconds, but parsl provides `10`, which leads to difficult-to-recognize errors relating to walltime errors.

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl 0.9.0 with Python 3.6 on cluster
2. Run a sleep job with GridEngine provider
3. Watch the `qstat`, where you will see jobs disappear

**Expected behavior**
10 minute default walltime

**Environment**
 - OS: CentOS 7
 - Python version 3.6
 - Parsl version 0.9

**Distributed Environment**
- Where are you running the Parsl script from ? Login node

- Where do you need the workers to run ?Worker nodes on same network as login node

**Comment by benclifford** [comment]
The default is provided as a literal `walltime="00:10:00"` in `grid_engine.py` and then converted to minutes by `job_config["walltime"] = wtime_to_minutes(self.walltime)`.

A quick google suggests that SGE expects `HH:MM:SS` format times - although I guess it is accepting a single integer in this case too.

I think this is a bug in the handling of any walltime specification, not only the default value, as an explicitly specified walltime will also go through `wtime_to_minutes`.
