### ISSUE TITLE
End of execution task summary is broken by task garbage collection

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1559]
**Describe the bug**
At DFK shutdown a summary record of final task statuses is logged.
Task garbage collection PR #1543 deletes that information before it is needed by the summary generator, resulting in missing summary information, such as:
```
INFO     parsl.dataflow.dflow:dflow.py:803 Summary of tasks in DFK:
INFO     parsl.dataflow.dflow:dflow.py:841 End of summary
```

**To Reproduce**
```
pytest parsl/tests/test_python_apps/test_memoize_1.py  --config parsl/tests/configs/local_threads.py  --log-cli-level=DEBUG
```
and observe summary info.

**Expected behavior**
The task summary should report all tasks.

This behaviour is broken in commit a33d465b8024d261b1fbe79cafc506053386fcef but works in the immediate parent commit 92a4bbc06c6cd5e46cdc307212caebd546f2db9b

```
pytest parsl/tests/test_python_apps/test_memoize_1.py  --config parsl/tests/configs/local_threads.py  --log-cli-level=DEBUG
...
INFO     parsl.dataflow.dflow:dflow.py:779 Summary of tasks in DFK:
INFO     parsl.dataflow.dflow:dflow.py:810 Tasks in state States.done: 0, 1, 2
INFO     parsl.dataflow.dflow:dflow.py:817 End of summary
```

**Environment**
my laptop, python 3.7, master @ ee2e39b2c

**Comment by benclifford** [comment]
See PR https://github.com/Parsl/parsl/pull/1560 for a regression test for this

**Comment by yadudoc** [comment]
Do we want the summary to list all the task ids in each of the states, or would a count do ?

**Comment by benclifford** [comment]
A count is probably sufficient
