### ISSUE TITLE
Error for globus transfer failure

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#162]
At the moment if the transfer fails we get a FileNotFoundError.  Ideally, we should tell the user that the transfer failed and perhaps relay the Globus error message.

**Comment by annawoodard** [comment]
We think this is because Kyle was not calling `.result()`

**Comment by annawoodard** [comment]
(deferring this because it relies on #169 and is a substantial enough change it will not be ready for 0.5)

**Comment by lukaszlacinski** [comment]
Parsl 0.5.0 implements explicit staging, so it requires calling result() on a DataFuture object.
