### ISSUE TITLE
PR #1471 seems to go a few steps backwards

### ISSUE THREAD

**Issue by hategan** [Parsl/parsl#1641]
While trying to commit the rest of the split-up PR #1420, I ran into the fact that PR #1471 conflicts with it. 

In principle, the idea behind issue #1448 is the right one: make code more abstract. In practice, #1471 does it by also removing essential functionality. To use a bit of hyperbole, it's really nice when you can abstract all your code to "return True", but it is not very useful.

In particular, after #1471, tasks managed by the local provider appear to never be able to have the COMPLETED status, only RUNNING and FAILED. This was handled properly when using popen() locally. I would think that, should a single solution be adopted, we should adopt the correct one and fix the remote channels to properly report task status. Without the ability to distinguish between success and failure when running a worker, we cannot detect the type of problems that  #1420 does. Like ever.

Additionally, but this should be easily fixed, the channel interface does not support pull_file (although the SSH implementation does) method, which is needed for getting stdout/stderr files back. And, by the way, the current code munges stdout and stderr, whereas the special-cased one didn't.

**Comment by benclifford** [comment]
I'm fine with the `Channel` interface being changed to support what is necessary for new features.
