### ISSUE TITLE
Globus path mapping in config

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#165]
At the moment we are conflating the Globus/Local path mapping and the working directory. I think we should break this config up as follows: 

```
 "data": {
     "globus": {
           "endpoint_name": "7d2dc622-2edb-11e8-b8be-0ac6873fc732",
           "endpoint_path": "/home/globus/kyle",
            "local_path" : "/home/user/kyle"
       }
       "working_dir" : "/home/user/kyle/parsl-stuff
 }
```

This would then allow us to keep the mapping in the site-specific Globus object (from endpoint_path to local_path) and manage the working directory as a general data option. I expect this will be easier in the long run as we transition to externally cataloged site definitions too.

**Comment by lukaszlacinski** [comment]
"working_dir" specifies where files will be staged in to. "endpoint_path" is optional and by default is  the same as "working_dir". "endpoint_path" is needed only when <endpoint_name><working_dir> does not correspond with working_dir on the filesystem. In this case, endpoint_path needs to be specified, so <endpoint_name><endpoint_path> points to the working_dir on the filesystem.

"data": {
     "globus": {
           "endpoint_name": "7d2dc622-2edb-11e8-b8be-0ac6873fc732",
           "endpoint_path": "/kyle/parsl-stuff"
      }
       "working_dir" : "/home/user/kyle/parsl-stuff
 }

**Comment by kylechard** [comment]
In the long run I expect the person defining the Globus config will be different than the person defining the working_dir. So it would be preferable to include both endpoint_path and local_path to specify the mapping independent of the working directory.

**Comment by annawoodard** [comment]
To clarify @kylechard's comment, I think what he's saying is to have what we had before with the `working_dir` as an additional option
