### ISSUE TITLE
Should we allow `ignore_for_cache` keyword args that do not appear in app signature?

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1652]
Currently, the following app will fail, because we require that any keyword args appearing in an app decorator's `ignore_for_cache` list exist in the app signature:
```python
@python_app(ignore_for_cache=['foo'])
def test(bar='one'):
    return bar
```

I think in such a case, we should just pass, since that _would_ be ignoring it-- we don't call the list `assert_kwarg_exists_and_ignore_for_cache`, after all. A case could be made though that if someone has written an app like above, they're confused, and raising an error might help them. 

This bug was found by #1182, error can be found [here](https://travis-ci.com/github/Parsl/parsl/jobs/323140049):
```
DEBUG    parsl.dataflow.memoization:memoization.py:159 Ignoring these kwargs for checkpointing: ['stdout']
DEBUG    parsl.dataflow.memoization:memoization.py:161 Ignoring kwarg stdout
DEBUG    parsl.dataflow.dflow:dflow.py:427 Got an exception launching task
Traceback (most recent call last):
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 418, in launch_if_ready
    task_id, task_record['func'], *new_args, **kwargs)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 484, in launch_task
    memo_fu = self.memoizer.check_memo(task_id, self.tasks[task_id])
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/memoization.py", line 199, in check_memo
    hashsum = self.make_hash(task)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/memoization.py", line 162, in make_hash
    del filtered_kw[k]
KeyError: 'stdout'
```

**Comment by benclifford** [comment]
the existing behaviour argument is to avoid "I wrote to ignore `my_sanitized_param` but I can't see why parsl isn't ignoring `my_sanitiized_params`". most kwarg based stuff in python will break if kwargs don't align across different uses (unless you're using **kwargs in which case, it's on your own head)

**Comment by annawoodard** [comment]
OK, good point. 

> Should we allow `ignore_for_cache` keyword args that do not appear in app signature?

No. Closing.
