### ISSUE TITLE
Always use a fresh `ignore_for_cache`

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1655]
A bug is causing the tests to fail in #1182, the error can be found [here](https://travis-ci.com/github/Parsl/parsl/jobs/323140049):
```
DEBUG    parsl.dataflow.memoization:memoization.py:159 Ignoring these kwargs for checkpointing: ['stdout']
DEBUG    parsl.dataflow.memoization:memoization.py:161 Ignoring kwarg stdout
DEBUG    parsl.dataflow.dflow:dflow.py:427 Got an exception launching task
Traceback (most recent call last):
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 418, in launch_if_ready
    task_id, task_record['func'], *new_args, **kwargs)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/dflow.py", line 484, in launch_task
    memo_fu = self.memoizer.check_memo(task_id, self.tasks[task_id])
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/memoization.py", line 199, in check_memo
    hashsum = self.make_hash(task)
  File "/home/travis/build/Parsl/parsl/parsl/dataflow/memoization.py", line 162, in make_hash
    del filtered_kw[k]
KeyError: 'stdout'
```

But note that the failure happens in `test_memoize.py` when the new test was added in `test_stdout.py`. I think this is due to us passing around a mutable default value `ignore_for_cache=[]` in various places; when we add `stdout` and `stderr` to `ignore_for_cache` when `stdout=parsl.AUTO_LOGNAME` is passed in the app signature, that gets propagated later unexpectedly.

**Comment by benclifford** [comment]
It looks like PR #1656 doesn't change defaulting for python_apps. re-opening this as a reminder to fix.
