### ISSUE TITLE
Version mismatches are getting suppressed

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1669]
**Describe the bug**
#1357 changed the default behavior to suppress failures in the interchange's handling of messages
from the managers. However, this was very broad. While this change was made to broadly ignore garbled messages, and messages from managers marked as dead, this had the unintended effect of also masking version mismatches between the interchange and the workers.

**To Reproduce**

Steps to reproduce the behavior, for e.g:
1. Update worker config to load python3.7
2. Run parsl script with python3.6

**Expected behavior**
Parsl should shutdown with an exception pointing out the version mismatch in the env.

**Environment**
 - OS: [e.g. ubuntu, centos, MacOS, windows]
 - Python version
 - Parsl version

**Comment by benclifford** [comment]
#1537 is a code-of-conduct change, not htex

**Comment by yadudoc** [comment]
Sorry. fixed in original post to https://github.com/Parsl/parsl/pull/1357
