### ISSUE TITLE
Link to instructions for starting ipcontroller/engines in User guide

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#167]
We should add instructions for starting ipcontroller/engines to the User guide. This [documentation](https://github.com/Parsl/parsl/blob/master/parsl/tests/test_ipp/README.rst) is probably a good starting point.

As reported by @ryanchard.

**Comment by benclifford** [comment]
closing as outdated - ipcontroller is part of the now-removed IPP executor
