### ISSUE TITLE
Implement implicit staging

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#169]
Currently users have to call

```
dfu = file.stage_in()
dfu.result()
```

It would be preferable to call `result()` automatically. Related to #162.

**Comment by yadudoc** [comment]
@annawoodard We should just remove explicit staging. If we call result() automatically, we block the workflow, it becomes serial.
Trying to handle externally launched futures in the DFK is pretty ugly, and I would recommend we fix this by adding implicit staging.

**Comment by annawoodard** [comment]
Sounds good @yadudoc
