### ISSUE TITLE
Monitoring should record tasks when they are created, not when they start running

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1723]
**Is your feature request related to a problem? Please describe.**
It is unclear from (for example) Gantt plots when tasks are created by app invocation. Monitoring at the moment only records a task once it is passed to an executor, ignoring that the task may not be passed to an executor for some time (for example, because it is waiting on dependencies).

**Describe the solution you'd like**
Monitoring should record a task as soon as it is known to the DFK (pretty much when an app invocation happens)

**Comment by ZhuozhaoLi** [comment]
I actually modified this for the Biology pipeline to generate the DAG first. I can make a PR for this.
