### ISSUE TITLE
potential changes to BW config in docs

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#1750]
The config in the 1.0 docs says

```
config = Config(
    executors=[
        HighThroughputExecutor(
            label="bw_htex",
            cores_per_worker=1,
            worker_debug=False,
            address=address_by_hostname(),
            provider=TorqueProvider(
                queue='normal',
                launcher=AprunLauncher(overrides="-b -- bwpy-environ --"),
                scheduler_options='',  # string to prepend to #SBATCH blocks in the submit script to the scheduler
                worker_init='',  # command to run before starting a worker, such as 'source activate env'
                init_blocks=1,
                max_blocks=1,
                min_blocks=1,
                nodes_per_block=2,
                walltime='00:10:00'
            ),
        )

    ],

)
```

Two possible additions are:

1 - explain how to use the XK nodes, with an option like
```                scheduler_options='#PBS -l nodes=1:ppn=16:xk```
which would also require explaining what options here overwrite other parts of the config

2 - explain that virtualenv is the recommended environment for Python on BW, which leads to
```                worker_init='module load bwpy; source $VIRTUALENVPATH/bin/activate',```
or something similar

**Comment by danielskatz** [comment]
@ZhuozhaoLi, I hope that perhaps you can help put this in as a PR - I'm not exactly sure how best to put this idea of options and potential text into a config object in the docs...

**Comment by sophie-bui** [comment]
@danielskatz – can we close this issue since BW is no longer in use?
