### ISSUE TITLE
Globus staging returns unclear error

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#178]
Here's the error we get when we try to stage in a file without setting the globus endpoint path in the config:

```
globus_sdk.exc.TransferAPIError: (400, 'ClientError.BadRequest.ResourcePropertyValueError', "invalid value '' for property 'destination_endpoint' of type 'string.ascii.endpoint_name': value does not match regex '([a-z][0-9a-z_]+#)?[0-9a-zA-Z_][-0-9a-zA-Z_.]*'", 'gX6cpN9gL')
```
This is not super helpful. We should catch this in the globus initialization and simply report that the endpoint_name is not set or malformed.

**Comment by lukaszlacinski** [comment]
1. I am not able to replicate the error. The config without endpoint_path works for me.
2. The error says that endpoint_name is set to ''. Parls does not know what is the correct endpoint_name. The Globus service does. Maybe Parsl should present Globus exceptions in a more user friendly form.

**Comment by yadudoc** [comment]
Fixed in new config support.
