### ISSUE TITLE
@join_app decorator for launching apps from inside other apps

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1796]
parsl 1.0.0 supports launching apps from within other (ThreadPool) apps, but lacks a good way to
depend on the results of those apps. This issue talks about that and proposes a solution.

For the avoidance of doubt, this issue does not address launching apps inside a remote worker
in some kind of remote mini-DFK to avoid the main DFK being aware of those apps.

## Motivating example

There are "sensors" which must be processed and assembled into "patches", and all patches assembled into a "mosaic".
The list of which sensors must be assembled into "patches" is not know ahead of time and is expensive to compute.
There are many patches which must all be processed in this way.

For each patch:
1. Generate list of sensors for this patch, one parsl app.
2. Process sensors for this patch - one parsl app per sensor
3. When all sensors are processed, assemble all the processed data into a patch.
4. Some post processing happens on the patch
Once all patches are done:
5. Make mosaic of all patches

Here are some implementation attempts and the weaknesses I see in them.

## Attempt 1:

```
post_process_futures = []
for patch in patch_list:
  sensor_list_future = generate_sensor_list_app(patch)
  sensor_futures = []
  for sensor in sensor_list_future.result():
    sensor_futures.append(process_sensor(sensor))
  assembled_future = assemble_sensors(*sensor_futures)
  post_process_futures.append(post_process(assembled_future))
mosaic_future = make_mosaic(*post_process_futures)
mosaic_future.result()
```

Weaknesses:

*  Only one patch is processed at a time. The outer for loop blocks on job completion repeatedly
before all of the apps are submitted, forcing unnecessarily serialised execution ordering: each
loop will block waiting for generate_sensor_list_app to complete.

## Attempt 2

Put the whole loop body into an app.

```
patch_futures = []
for patch in patch_list:
  patch_futures = process_patch(patch)
mosaic_future = make_mosaic(*patch_futures)
mosaic_future.result()

@python_app(executors=['local-thread-pool']
def process_patch():
  sensor_list_future = generate_sensor_list_app(patch)
  sensor_futures = []
  for sensor in sensor_list_future.result():
    sensor_futures.append(process_sensor(sensor))
  assembled_future = assemble_sensors(*sensor_futures)
  post_process_future = post_process(assembled_future)
  post_process_future.result()
```

In this attempt, all of the for-loop bodies are launched without blocking (as process_patch invocations),
and potentially can run concurrently.

Weaknesses:

Each process_patch app must stay executing (occupying a thread pool worker) for the entire duration of
the tasks that it has launched, because it blocks waiting for completion of the post_process step, by
calling post_process_future.result().
It does this so that the process_patch app completes after the post_process step. If this call to
.result() was not there, the process_patch app invocation would complete too early, and make_mosaic
could run before post_process is complete.

Because of this, there can be serialization and deadlock issues: there needs to be one local-thread-pool
worker available for every patch to be processed simultanously, that will for the most part be sitting
idle waiting for final results. If there are fewer, then patch processing will be serialised due to
lack of workers, although to a lesser extent than in attempt 1.

But worse, if any of the launched apps also used local-thread-pool, then the workflow can deadlock if there
insufficient workers:
launched process_patch apps will be waiting for other apps to complete, but those apps cannot complete
because process_patch apps are occupying all of the local-thread-pool workers.

This leads to a principle: apps should not block on other apps

## Attempt 3:
No blocking inside apps

```
sensor_list_futures = []
for patch in patch_list:
  future = generate_sensor_list_app(patch)
  future.patch = patch
  sensor_list_futures.append(future)

post_process_futures=[]
for future in concurrent.futures.as_completed(sensor_list_futures):
  patch = future.patch
  sensor_futures = []
  for sensor in future.result()
    sensor_futures.append(process_sensor(sensor)
  assembled_future = assemble_sensors(*sensor_futures)
  post_process_futures.append(post_process(assembled_future))

mosaic_future = make_mosaic(*post_process_futures)
mosaic_future.result()
```

weaknesses:

There is some loss of the sense of data flow expressed in syntax, obscured by the implementation of a rudimentary
task scheduler that only knows about sensor list futures.

This is *still* blocking on the second for loop needing to complete before later apps can be launched,
and that for loop only completes when all sensor lists have been generated - this is earlier than
in previous examples, but there is a still blocking there.

This impedes compositionality: this code could not be placed into a function and (for example) run
inside another for loop that loops over multiple datasets: the function would block each time waiting
for sensor list generation, rather than processing each data set's sensor list generations
concurrently.

Anything that blocks the execution thread on future completion (for example, `.result()`
or `.as_completed()`) is the enemy.

## Proposed and prototyped join syntax:

This is an attempt to move some of the cases where blocking and ad-hoc task scheduling happens in
the workflow into parsl dependency handling. The only blocking should happen at the very end of the
workflow, so that the main process does not end until work is completed. Other than that, nothing else
should block on app completion.

```
post_process_futures=[]
for patch in patch_list:
  sensor_list_future = generate_sensor_list_app(patch)
  sensors_future = process_sensors(sensor_list_future)
  assembled_future = assemble_sensors(sensors_future)
  post_process_futures.append(post_process(assembled_future))

mosaic_future = make_mosaic(*post_process_futures)
mosaic_future.result()

@join_app
def process_sensors(sensor_list):
  sensor_futures = []
  for sensor in sensor_list:
    sensor_futures.append(process_sensor(sensor))
  return combine_app(*sensor_futures)

@python_app
def combine_app(*args):
  pass # do nothing, but only after all args are complete
```

The new prototype language feature here is a new kind of app called a @join_app, which runs python code locally inside the workflow process and then performs special processing on the result, described below.

There is also a helper app (which already works in parsl 1.0.0) which, given a list of input futures,
completes when all of those futures complete, without any further processing. This constructs a
barrier future, depending on an arbitrary list of other futures.

Without @join_app, in parsl 1.0.0, the process_sensors app could be implemented as  a @python_app running on a thread local executor. It would invoke the
individual process sensors apps, and then immediately return. The value returned would be a Future,
the AppFuture from invoking combine_app.
process_sensors returns a Future containing a Future.

assemble_sensors then depends on receiving a value from process_sensors. This would happen almost
immediately, with the value being the Future returned by combine_app. But that's no good - we want
to block assemble_sensors from executing until combine_app has finished execution. Instead, we only
block until we get the AppFuture for combine_app.

We could put in a `.result()` somewhere to extract that value - but remember that calling `.result()`
is bad, for reasons outlined above.

What could help is a way to say that if an app returns a Future, the AppFuture doesn't complete
until that returned Future has completed. In the case of process_sensors above, the process_sensors
AppFuture should not complete until the returned Future completes, in this case the AppFuture
returned by combine_app. That is what the special post-processing behaviour of @join_app does.

This allows more naunced dependencies to be expressed which can help with:
* increased concurrency - helping with strong scaling
* more focused error propagation - allowing more of an ultimately failing workflow to complete
* more useful monitoring information

This has been prototyped in LSST work in two forms, with the above syntax prototyped in the
`lsst-dm-202005` branch.

## Terminology

The term `join` comes from use of monads in functional programming, especially Haskell.

## Merge plan

- PR #1856 - generalise file staging inhibit, allowing reuse of data_manager executor for other parsl internal tasks
- rename data_manager executor to parsl_internal
- main join_app PR

**Comment by annawoodard** [comment]
I agree that the motivating examples are real problems and I generally support the proposed solution. The only tweak I would make is to substitute a dedicated decorator in place of a `join` decorator keyword argument-- this would allow us to require that a threadpool executor is used (we could insert a dedicated threadpool executor for joined apps under the hood) and document it explicitly. We would need to make it very clear in the documentation that joined apps always run in a threadpool and are never sent out to remote compute resources-- I think this bit would be very confusing for users.

```python
@python_app(join=True, executors=['local-thread-pool'])
def process_sensors(sensor_list):
  sensor_futures = []
  for sensor in sensor_list:
    sensor_futures.append(process_sensor(sensor))
  return combine_app(*sensor_futures)
```

would become

```python
@joined_python_app
def process_sensors(sensor_list):
  sensor_futures = []
  for sensor in sensor_list:
    sensor_futures.append(process_sensor(sensor))
  return combine_app(*sensor_futures)
```

**Comment by annawoodard** [comment]
Maybe something like `local_joined_python_app` would be even more explicit that it's not going anywhere

**Comment by ravihansa3000** [comment]
This feature will open up new possibilities that will immensely help Parsl app developers to manage workflows that have dynamic divergent and convergent points. I'm currently working on a genomic analysis problem that could benefit by having a feature that would allow an app to depend on an AppFuture within an AppFuture. 

I'd +1 @annawoodard 's proposal to have a separate decorator to indicate that the app should be executed in a local thread pool and returned AppFuture within the app must be completed. I really like the idea of having a built-in local thread pool rather than having to include one in the Parsl config which IMO could lead to confusion and accidental errors.

**Comment by ravihansa3000** [comment]
I should also point out that until a distributed DFK mechanism is implemented, this approach might cause problems in environments with non-shared filesystems.

**Comment by benclifford** [comment]
@ravihansa3000 what issues do you expect with non-shared filesystems?

**Comment by ravihansa3000** [comment]
@benclifford it would be problematic if the app (@joined_python_app) needs access to files for some reason (perhaps a validation step)

**Comment by benclifford** [comment]
@annawoodard I've changed the syntax in the LSST implementation and in the main description to use `@join_app`, without need to specify an executor (which is now always the parsl internal thread local executor that was previously only used for globus file staging)

**Comment by annawoodard** [comment]
@benclifford sounds good!

**Comment by benclifford** [comment]
This test lives in our CI but breaks easily - for example, if invoked with non-trivial (n>3) fibonacci size on htex.

This test should be re-written to be use @join_app and tested with larger sizes - recursive fibonacci can be a nice example of join_app
