### ISSUE TITLE
Support older versions of Bash

### ISSUE THREAD

**Issue by jadamstephens** [Parsl/parsl#1797]
Slurm submission scripts written by Parsl 0.7 use the Bash builtin command 'wait' with the -n option. I believe this option was introduced in a relatively recent version of Bash, perhaps 5.0 Many of the systems at my organization run Redhat Enterprise Linux 7, which uses Bash-4.2. This version of bash does not recognize the -n option to wait, and the script errors out.

Please consider implementing the slurm submission script without using wait -n to improve compatibility with older versions of bash, which I imagine are still in common use.

**Comment by yadudoc** [comment]
Hi @jadamstephens, could you try switching to the latest parsl version (v1.0.0)? In the latest version I do not see `wait` being used with the `SlurmProvider`+`SrunLauncher` combination. If you still have issues, please share a tarball of your runinfo directory.

**Comment by benclifford** [comment]
A quick skim doesn't show me `wait -n` in 0.7.0 either, though, so I'm unclear where the -n is coming from for you. Can you attach a full submission script that has this in it?

**Comment by jadamstephens** [comment]
Hi,

I wrongly assumed that I was using 0.7 based on some instructions that are probably now outdated. It looks like I did install 1.0.

Anyway, [this line](https://github.com/Parsl/parsl/blob/f11417a0255ed290fd0d78ffa1bc52cfe7a06301/parsl/launchers/launchers.py#L103) in launchers/launcher.py seems to be the source of the wait command in the slurm submission script.

I'm encountering this issue when running [example.py](https://github.com/Parsl/dynamic_launcher) using the command:

```
python3 example.py --fileconfig=blake --count=10 --example=tasks
```

(I modified cori.py to use on a machine here named blake.)

**Comment by benclifford** [comment]
OK. That line isn't in 1.0.0, but was introduced into master in PR #1724. So I guess you've actually installed the latest master, not 1.0.0 (although it likely claims to be 1.0.0).

**Comment by benclifford** [comment]
tagging @hategan because that's some code he's been working on recently

**Comment by jadamstephens** [comment]
You're right. I did clone master. I checked out and installed the 1.0.0 tag and now it's working. Even so, since the change is on master, my feature request stands :)

**Comment by hategan** [comment]
Didn't realize that "-n" was v5 and up. I very much agree that currently-in-use versions of bash should be supported.
