### ISSUE TITLE
Implement a WQ-specific scaling strategy

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1823]
Our current scaling strategy does not work for WQ, because it depends on the number of tasks and number of workers to decide how many workers to submit. We need a strategy that emulates what the WQ factory does in order to allow users to fully use the WQ executor with a provider, without submitting workers or starting a factory by hand.

**Comment by benclifford** [comment]
or make wq factory able to submit using parsl providers.

or use wq factory and don't expect the provider mechanism to work - it's not clear to me that it's a real requirement.

**Comment by annawoodard** [comment]
> or make wq factory able to submit using parsl providers.

This isn't necessary, since the factory is already able to talk to all the same systems that we are.

> or use wq factory and don't expect the provider mechanism to work - it's not clear to me that it's a real requirement.

Good point, perhaps we should just clarify the docs to explain what can be expected if users do use a provider. I'll close this, experiment a bit and open another issue if needed.
