### ISSUE TITLE
Add NSF badge to the README

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1828]
**Is your feature request related to a problem? Please describe.**

Since Parsl is an NSF funded project, it would be nice to acknowledge that with a badge and also make it easy for software-analytics efforts to track our project better. This is based on the twitter request here : https://twitter.com/sjGoring/status/1291442252573679616

**Describe the solution you'd like**
Add the badge

**Comment by danielskatz** [comment]
I'm not sure how we do this with a .rst README - I've asked on twitter

**Comment by danielskatz** [comment]
The answer seems to be in https://stackoverflow.com/questions/34777943/insert-clickable-svg-image-into-sphinx-documentation

**Comment by danielskatz** [comment]
And if someone does this, they should add multiple badges, one for each of the NSF Parsl collaborative awards
