### ISSUE TITLE
Monitoring Bug on ALCF Theta

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#1837]
**Describe the bug**

I get some errors when using monitoring on Theta, which I think are causing problems with executors. When using monitoring, my jobs sent to a `ThreadPoolExecutor` execute but I do not see a "Task Completed" notification and the jobs eventually stall:

```
2020-08-08 17:10:06,436 - root - ERROR - Exception reading IO counters for child memory_percent. Recorded IO usage may be incomplete
Traceback (most recent call last):
  File "/lus/theta-fs0/projects/CSC249ADCD08/colmena/env/lib/python3.7/site-packages/parsl/monitoring/monitoring.py", line 551, in monitor
    d['psutil_process_disk_write'] += child.io_counters().write_bytes
AttributeError: 'Process' object has no attribute 'io_counters'
```

**To Reproduce**

The following script computes on my desktop and stalls on the Theta login node:

```python
import logging

from concurrent.futures import as_completed

import parsl
from parsl import ThreadPoolExecutor, python_app
from parsl.addresses import address_by_hostname
from parsl.config import Config
from parsl.monitoring import MonitoringHub

#logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)

config = Config(
    executors=[
        ThreadPoolExecutor(label="local_threads", max_threads=1)
    ],
    monitoring=MonitoringHub(
        hub_address=address_by_hostname(),
        hub_port=55055,
        monitoring_debug=False,
        resource_monitoring_interval=10,
    ),
    strategy=None,
)

parsl.load(config)


@python_app
def func(x):
    return x + 1


futures = [func(i) for i in range(32)]
for f in as_completed(futures):
    print(f.result())
```

**Expected behavior**

No scary error messages and my jobs all executing completely.

**Environment**
 - OS: Centos
 - Python version: 3.7
 - Parsl version: 1.0

**Distributed Environment**
- Where are you running the Parsl script from ? Launch node
- Where do you need the workers to run ? Some on compute nodes, some on launch node

**Comment by benclifford** [comment]
monitoring isn't supported on ThreadPoolExecutor - so don't be surprised that it doesn't work with anything other than HighThroughputExecutor.

Do you know which version of the `psutil` library you are using? It would be interesting to see what you get if you log
`child.as_dict()` on that exception to show what information is available - for example, I see this on a test process:

```
>>> p.as_dict()
{'threads': [pthread(id=1, user_time=0.05, system_time=0.02)], 'num_threads': 1, 'cpu_percent': 0.0, 'memory_full_info': None, 'cpu_times': pcputimes(user=0.05, system=0.02, children_user=903.06, children_system=621.44), 'cpu_affinity': [0, 1, 2, 3, 4, 5, 6, 7], 'memory_info': pmem(rss=0, vms=7020544, shared=0, text=897024, lib=0, data=573440, dirty=0), 'ionice': pionice(ioclass=<IOPriority.IOPRIO_CLASS_NONE: 0>, value=0), 'nice': 0, 'open_files': None, 'memory_percent': 0.0, 'io_counters': None, 'memory_maps': None, 'status': 'sleeping', 'environ': None, 'num_ctx_switches': pctxsw(voluntary=636, involuntary=6), 'cmdline': ['/bin/bash', '/home/benc/tmp/cue/rootfile-benc-bsgjdeodu3poa1neabtg'], 'connections': None, 'gids': pgids(real=0, effective=0, saved=0), 'ppid': 0, 'cwd': None, 'pid': 1, 'uids': puids(real=0, effective=0, saved=0), 'name': 'rootfile-benc-b', 'num_fds': None, 'username': 'root', 'cpu_num': 2, 'exe': '/bin/bash', 'terminal': '/dev/pts/0', 'create_time': 1596012245.43}
```

The jobs stalling thing is also interesting - the above exception happening should not stop job progress because that exception is caught and handled entirely by that code. However if psutil is behaving unexpectedly, it's possible that there is another exception happening which isn't being caught and logged. I've encountered that in a few places when parsl launches threads, that exceptions fall off the top of the call stack; and in my LSST branch I have code which wraps most threads with another wrapper that properly logs exceptions falling off the top to help diagnose those problems.

You could do something similar here: put a try block around the entire body of `monitoring.py:monitor` making no assumptions about any of the code being well behaved, and catch and log anything that goes wrong.

**Comment by WardLT** [comment]
I'm using `psutil` version 5.7.0. 

Thanks for the suggestion on the additional monitoring for Thread workers. I would not be surprised if the root of this error are exceptions not being caught and returned properly.

**Comment by ZhuozhaoLi** [comment]
@WardLT Thanks for reporting the issue. As Ben pointed out, monitoring does not work for `ThreadPoolExecutor`. 

I just tried your minimal example with Parsl master, it did hang. But when I switched it to `HighThroughputExecutor`, it worked fine for me. I will dig into why it hangs.

BTW, I would like to note the issue #1069 . If later on you use monitoring on Theta compute nodes, you will probably see message missing with more than 40 workers/node. As far as I know, this is likely still an issue on Theta.

**Comment by yadudoc** [comment]
@ZhuozhaoLi  When I run @WardLT 's script on Theta, I see all the tasks return, but the DFK appears to be hung at the end with these lines at the end of the parsl.log :
```
2020-08-10 15:55:07.158 parsl.monitoring.monitoring:267 [INFO]  Terminating Monitoring Hub
2020-08-10 15:55:07.159 parsl.monitoring.monitoring:283 [INFO]  Waiting for Hub to receive all messages and terminate
```

**Comment by ZhuozhaoLi** [comment]
> @ZhuozhaoLi When I run @WardLT 's script on Theta, I see all the tasks return, but the DFK appears to be hung at the end with these lines at the end of the parsl.log :
> 
> ```
> 2020-08-10 15:55:07.158 parsl.monitoring.monitoring:267 [INFO]  Terminating Monitoring Hub
> 2020-08-10 15:55:07.159 parsl.monitoring.monitoring:283 [INFO]  Waiting for Hub to receive all messages and terminate
> ```

I tried to run Logan's script for 10 times, I think 2 out of 10 succeeded, but the rest hung. For the hung ones, I saw these lines:

```
2020-08-10 16:07:30.552 parsl.dataflow.dflow:907 [INFO]  DFK cleanup initiated
2020-08-10 16:07:30.553 parsl.dataflow.dflow:810 [INFO]  Summary of tasks in DFK:
2020-08-10 16:07:30.553 parsl.dataflow.dflow:823 [INFO]  Tasks in state States.done: 1
2020-08-10 16:07:30.553 parsl.dataflow.dflow:823 [INFO]  Tasks in state States.launched: 31
2020-08-10 16:07:30.553 parsl.dataflow.dflow:829 [INFO]  End of summary
```

**Comment by benclifford** [comment]
That summary looks weird if you're expecting all of the tasks to be in `done` state at exit.
