### ISSUE TITLE
Remote function name is not resolved correctly | task_func_name: wrapper

### ISSUE THREAD

**Issue by ravihansa3000** [Parsl/parsl#1857]
**Describe the bug**
The stdout and stderr log filenames of Parsl apps should contain the function name of the corresponding app (Parsl 1.0.0 behavior). In master branch version (ec09fdc), the function name is appended as 'wrapper'. This unexpected behavior is only noticed in bash_apps. It works as expected for python_apps.

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl latest (ec09fdc) with Python 3.7 on cluster
2. Run a test script with a bash_app named "my_bash_app"
3. Wait until tasks are finished
4. See generated Parsl stdout, stderr log files.
5. Check parsl.log for 'task_func_name': 'my_bash_app'. However, 'task_func_name': 'wrapper' is seen

**Expected behavior**
1. 'task_func_name': 'my_bash_app' in Parsl log
2. "my_bash_app" string contained in stdout and stderr log filenames.

**Environment**
 - OS: RHEL6.1
 - Python version: 3.7 (Anaconda 4.8.2)
 - Parsl version: ec09fdc2099e1795f41210bd1a159633b601cee3

**Distributed Environment**
- PBS Pro in NSCC's ASPIRE1 (HTEX)

**Comment by ravihansa3000** [comment]
@benclifford @annawoodard pls take a look

**Comment by benclifford** [comment]
I bisected this with a simple test case and the breaking commit is:
```
benc@parsl-dev-3-7-4078:~/parsl/src/parsl$ git bisect good
8b981dc954f539bcbd04e986fec43e234e21bfaf is the first bad commit
commit 8b981dc954f539bcbd04e986fec43e234e21bfaf
Author: Yadu Nand Babuji <yadudoc1729@gmail.com>
Date:   Tue Aug 4 03:50:30 2020 -0500

    New serialization system to replace IPP serialization (#1806)
```

I suspect the lines that adjust use of `partial` are breaking something there. In the LSST branch of parsl I have those lines reverted because (according to the note I made at the time) they did something bad to memoization, with a TODO to investigate what is actually happening.

@yadudoc should follow up.
