### ISSUE TITLE
WQ category is always the same

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#1867]
**Describe the bug**

The WQ category is always being set according to the function's `__qualname__` [here](https://github.com/Parsl/parsl/blob/master/parsl/executors/workqueue/executor.py#L409), and the function is being wrapped [here](https://github.com/Parsl/parsl/blob/master/parsl/app/errors.py#L154). For some reason, the qualname is not being updated correctly, so the category is always `wrap_error.<locals>.wrapper`:

```
1600806505778540 2352716 CATEGORY wrap_error.<locals>.wrapper MAX {"cores":[18,"cores"],"memory":[2464,"MB"],"disk":[2,"MB"]}
1600806505778556 2352716 CATEGORY wrap_error.<locals>.wrapper MIN {"cores":[3,"cores"],"memory":[100,"MB"],"disk":[2,"MB"]}
1600806505778565 2352716 CATEGORY wrap_error.<locals>.wrapper FIRST MAX_THROUGHPUT {"cores":[3,"cores"],"memory":[100,"MB"],"disk":[2,"MB"]}
```
According to the [docs](https://docs.python.org/3/library/functools.html#functools.wraps), `functools.wraps` should update the qualname as well as the name. But this patch fixes the issue, does anyone object to just setting according to name?

```diff
(gf) annawoodard@daenerys:/cephfs/users/annawoodard/parsl/parsl$ git diff executors/workqueue/
diff --git a/parsl/executors/workqueue/executor.py b/parsl/executors/workqueue/executor.py
index 52aa5c2..accae4e 100644
--- a/parsl/executors/workqueue/executor.py
+++ b/parsl/executors/workqueue/executor.py
@@ -407,6 +407,7 @@ class WorkQueueExecutor(NoStatusHandlingExecutor):
         # Create message to put into the message queue
         logger.debug("Placing task {} on message queue".format(task_id))
-        category = func.__qualname__ if self.autocategory else 'parsl-default'
+        category = func.__name__ if self.autocategory else 'parsl-default'
         self.task_queue.put_nowait(ParslTaskToWq(task_id,
                                                  category,
                                                  cores,
```

**Comment by benclifford** [comment]
__name__ is what is used else where (for example, monitoring) to distinguish between apps, so it would be more consistent to use __name__.
