### ISSUE TITLE
add contributor/community guidelines on parsl/parsl/readme and elsewhere

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#193]
I think we should add some contributing guidelines to the readme, perhaps summarizing and pointing to a new section in https://parsl.readthedocs.io/en/latest/index.html

Basically, that we welcome contributions, maybe pointing to the roadmap for some ideas of things we know we want, how contributions should be made (PRs), code style, etc.  Also explaining how to get support, which might be copied from http://parsl-project.org/support

And http://parsl-project.org/support should have the contributor part updated to more than just "follow the project on GitHub"

**Comment by annawoodard** [comment]
We have this started [here](https://github.com/Parsl/parsl/blob/master/.github/CONTRIBUTING.rst). I think that is the right place for it but I agree we should link to it from the docs. PRs and coding style is already there. So, summarizing the remaining points that should be done for this issue to be resolved:

- [ ] link to CONTRIBUTING from docs
- [ ] link to things we want in CONTRIBUTING (probably easiest to add more `help-wanted` tags)
- [ ] explain how to get support in CONTRIBUTING

**Comment by danielskatz** [comment]
What's [there](https://github.com/Parsl/parsl/blob/master/.github/CONTRIBUTING.rst) is great, but we also need some more general welcoming/requesting text. Not just how, but please do...

**Comment by danielskatz** [comment]
@kylechard addressed the README part in https://github.com/Parsl/parsl/commit/b51121450a0de0294251a383e3e23c6d00c3f471
We still need address the checklist items two comments above.
