### ISSUE TITLE
Add block ID to try table

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1969]
**Is your feature request related to a problem? Please describe.**

The monitoring database should record which block (and worker, ...) a particular try happened on.

This is useful for understanding where tasks run at a finer grain than the hostname, which can be re-used in multiple blocks over the course of  a run. 

**Additional context**

This is for lsst desc drp

cc @tomglanzman

**Comment by ZhuozhaoLi** [comment]
Looks like it should not be too difficult to add. Do you expect this to come in 1.1 release?

**Comment by benclifford** [comment]
The DRP workflow runs off a branch that regularly has master merged, so it doesn't need to have any main release target.

**Comment by TomGlanzman** [comment]
Hi @ZhuozhaoLi , just checking to see if there is any progress on this?  Having it in Ben's lsst-desc branch would enable me to move ahead with work defining standard db queries.  Thanks!

**Comment by ZhuozhaoLi** [comment]
@TomGlanzman I will come back to this in a week or so.

**Comment by ZhuozhaoLi** [comment]
@TomGlanzman the PR #1991  for this feature is merged into master. Thanks for the suggestion
