### ISSUE TITLE
ManagerLost is too vague

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1972]
**Describe the bug**

`ManagerLost` is pretty vague and confusing to new users. It might be useful to expand the error message to at least list the possible causes of failure, for eg short walltimes.

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Run parsl with a config with a short walltime set with a cluster scheduler, say walltime=2 mins.
2. Run a test that sleep > 2mins
3. `AppFuture.result()` raises `ManagerLost`

**Expected behavior**
A clearer error message that describes possible causes of failure.

**Comment by benclifford** [comment]
I'm unclear how this is any worse than any other "infrastructure" exceptions (i.e. ones not raised by the actual app).
