### ISSUE TITLE
garbage collection vs usage tracking shutdown race condition

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1986]
**Describe the bug**
I've seen this exception at least once in CI local tests. I think it comes from job completion garbage collection racing with DFK shutdown usage reporting, in examining the task dictionary.

```
parsl/tests/test_staging/test_elaborate_noop_file.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
parsl/dataflow/dflow.py:1051: in cleanup
    self.usage_tracker.send_message()
parsl/dataflow/usage_tracking/usage.py:224: in send_message
    message = self.construct_end_message()
parsl/dataflow/usage_tracking/usage.py:182: in construct_end_message
    app_fails = len([t for t in self.dfk.tasks if
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.0 = <dict_keyiterator object at 0x7f86107ca040>
>   app_fails = len([t for t in self.dfk.tasks if
                     self.dfk.tasks[t]['status'] in FINAL_FAILURE_STATES])
E   RuntimeError: dictionary changed size during iteration

```

**To Reproduce**
non-deterministic in CI

**Environment**
CI, near master 02d3b93ad4fd97b2411c000cf0b8820c76e5dfef

**Comment by benclifford** [comment]
From a quick look at that code, I think task garbage collection should be removing tasks in final failure states anyway, so that the code block raising the exception, which counts failed tasks, would always count 0 tasks.

I haven't verified if that is the case.

If it is, either failed task count should be dropped from usage tracking, or this code should be re-written to count without the `dfk.tasks` table.

**Comment by yadudoc** [comment]
I just did a quick check with latest, and failed tasks are still getting reported in the cleanup phase:

```
2021-03-02 14:56:57.029 parsl.dataflow.dflow:1030 [INFO]  DFK cleanup initiated
2021-03-02 14:56:57.029 parsl.dataflow.dflow:920 [INFO]  Summary of tasks in DFK:
2021-03-02 14:56:57.029 parsl.dataflow.dflow:934 [INFO]  Tasks in state States.failed: 10
2021-03-02 14:56:57.029 parsl.dataflow.dflow:940 [INFO]  End of summary
```

**Comment by benclifford** [comment]
That field comes from:

>         keytasks[States.failed] = self.tasks_failed_count

not from the self.tasks table, though, I think.

**Comment by benclifford** [comment]
(and if that is the case, this should be an easy fix)
