### ISSUE TITLE
combine() parsl_app returns exception if cached

### ISSUE THREAD

**Issue by TomGlanzman** [Parsl/parsl#2011]
** DESCRIPTION **
parsl_app throws exception when cached.

** TO REPRODUCE **
The following construction will cause an exception to be returned:

@python_app(executors=['cori-login'],cache=True)
def combine(inputs=[]):
   return

Where inputs is a list of futures.

'cori-login' is defined as:
        ThreadPoolExecutor(
                    label='cori-login',
                    max_threads=2
                    ),

The exception is:

unknown type for memoization: <class 'parsl.dataflow.futures.AppFuture'>

** ENVIRONMENT **
Parsl branch lsst-dm-202103
Running at NERSC/Cori

**Comment by benclifford** [comment]
The closest I've been able to replicate this (knowing what you've been working on) is if an earlier app returns a Future in its `return` statement - as if it was a join app (but without a @joinapp or `join=True` annotation).

In that case, that behaviour is expected: a Future can't be used as a key for checkpointing.

Here's my incorrect code that gives this exception:
```
import parsl


@parsl.python_app
def noop():
  import time
  time.sleep(10)
  return


@parsl.python_app
def n2():
  return noop()

@parsl.python_app(cache=True)
def combine(inputs=[]):
  return

parsl.load()

nf = n2()

combine(inputs=[nf]).result()

combine(inputs=[nf]).result()

print("done")
```
By replacing the definition of n2 with:

```

@parsl.join_app
def n2():
  return noop()
```

(joinapp vs pythonapp)

then this code works ok.

**Comment by TomGlanzman** [comment]
Ben has instructed me to use 'join_app' in this case and my tests are now running successfully.  Case closed.
