### ISSUE TITLE
Provider scaling with WorkQueue

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2031]
**Is your feature request related to a problem? Please describe.**
The WorkQueueExecutor doesn't work with the parsl provider/scaling mechanism; instead our recommendation so far has been to use workqueue's work_queue_factory: https://cctools.readthedocs.io/en/latest/man_pages/work_queue_factory/

Some of the problems with that:
* a configuration barrier to users switching between HTEX and WorkQueue: the complicated and painstakingly configuration statements defined for htex cannot be re-used for workqueue
* parsl monitoring is aware of provider-based batch jobs, but not of batch jobs launched in some other way

Workqueue already contains some code to launch *one* block with providers; and the HTEX provider scaling code is fairly well separated from the rest of HTEX.

In the `desc` branch I have prototyped rearrangements that allow the WorkQueueExecutor to re-use the htex provider code. This has been used in practice by a few users and has allowed them to easily move their configs from htex to wq, so I think it is worth moving into parsl `master`.

The structure so far looks roughly like:
* rework StatusHandlingExecutor to include almost all of HTEX's scaling code - become more a base class for executors that do any kind of provider/block/scaling (which in the past would also have included the IPP executor)
* make WorkQueueExecutor inherit from this

This doesn't stop people using work_queue_factory if their usage is more workqueue-centric than parsl-centric.
  
**Describe alternatives you've considered**
Supporting users understanding how to use work_queue_factory.

**Additional context**
This work is done as part of LSST DESC CI.

**Comment by benclifford** [comment]
cc @dthain who should also check his spam folder

**Comment by dthain** [comment]
@benc this approach makes sense to me.  What can my team do to support your work?

**Comment by benclifford** [comment]
@dthain I don't think anything is needed - this issue is just to state what I'm working on.

**Comment by benclifford** [comment]
This exists as PR #2071

**Comment by benclifford** [comment]
PR #2071 has been merged.
