### ISSUE TITLE
Parsl stuck after 30 minutes on HTCondor

### ISSUE THREAD

**Issue by jrueb** [Parsl/parsl#2040]
**Describe the bug**
Using Parsl with HighThroughputExecutor and CondorProvider, Parsl becomes stuck after 30 minutes of no results from a manager.

**To Reproduce**
1. Run the following script with HTCondor available
  <details>
    <summary>Python script</summary>
    

```python
#!/usr/bin/env python3

import os
import parsl
from tqdm import tqdm


def get_parsl_config(num_jobs):
    condor_init = "source {}/environment.sh\n".format(os.environ["HOME"])
    provider = parsl.providers.CondorProvider(
        init_blocks=num_jobs,
        max_blocks=num_jobs,
        worker_init=condor_init
    )
    parsl_executor = parsl.executors.HighThroughputExecutor(
        label="HTCondor",
        address=parsl.addresses.address_by_hostname(),
        max_workers=1,
        provider=provider,
    )
    parsl_config = parsl.config.Config(
        executors=[parsl_executor],
    )
    return parsl_config


@parsl.python_app
def work(sleep):
    import time
    time.sleep(sleep)
    return sleep

parsl_config = get_parsl_config(4)
parsl.load(parsl_config)
futures = [work(i + 28 * 60) for i in range(0, 4 * 60, 60)]
results = []
for future in tqdm(futures):
    results.append(future.result())

print(results)
```
  </details>

The `~/environment.sh` script that is executed here just sets `PATH`, `PYTHONPATH` and related variables to allow executing `process_worker_pool.py` with the needed libraries available on my particular setup.

 2. Wait for the HTCondor jobs to start and wait 30 minutes.
 3. The script will be stuck at 50%. Only the first two `future.result()` calls will return (the ones with 28 and 29 min of sleep), the others won't.
 
I also tested it with with various other sleep times. If the sleep time is below 30 min, it works. If it is above or equal it gets stuck. The HTCondor jobs continue running fine and the workers report having finished all the tasks.

**Expected behavior**
All four calls should return after a waiting time of 31 min and the script should print `[1680, 1740, 1800, 1860]`.

**Environment**
 - OS: CentOS Linux release 7.9.2009
 - Python version 3.6 and 3.8
 - Parsl version 1.0.0 and 1.1.0

**Distributed Environment**
- Where are you running the Parsl script from? Login node
- Where do you need the workers to run? HTCondor cluster nodes that run the same OS and software as the login node

**Additional Information**
From some debugging I did it looks to me like the connection `result_outgoing` of the Manager stops working, but I'm not sure if this is the entire problem.

**Comment by benclifford** [comment]
can you attach a copy of your runinfo/ directory for a run with parsl 1.1.0?

**Comment by benclifford** [comment]
an off-the-cuff thought without further evidence is that your network environment doesn't let network connections last longer than 30 minutes (that's the sort of thing I wouldn't expect in a clean network, but is the sort of thing I'd expect in some routed environments involving network address translation).

**Comment by yadudoc** [comment]
@jrueb Thanks for getting us the logs. It looks like 4 tasks were dispatched to 4 workers and all of them completed execution:
```
> cat HTCondor/*/*/worker_0.log |  grep Completed
2021-04-27 14:15:56.166 worker_log:551 Rank:0 [INFO]  Completed task 2
2021-04-27 14:16:56.348 worker_log:551 Rank:0 [INFO]  Completed task 3
2021-04-27 14:14:52.326 worker_log:551 Rank:0 [INFO]  Completed task 1
2021-04-27 14:17:57.496 worker_log:551 Rank:0 [INFO]  Completed task 4
```

The obvious item that jumps out from the logs is that the `CondorProvider.walltime` is set to the default of 10 minutes. Could you retry running with a more reasonable walltime of say `00:45:00`? I'm a bit surprised that the managers getting dropped are not being detected. There's no indication in the `interchange.log` that the managers disconnected, or from the manager logs that there was some failure. Similarly, the `parsl.log` has no logged errors/exceptions. 

Do you think you could also pop in these additional config options for better debug logging?
```
Config(executors=[
      HighThroughputExecutors(
            worker_debug=True,       # This will add debug logs
            heartbeat_period=10,     # More frequent heartbeats to detect network drops
            heartbeat_threshold=30,  # Report failure if heartbeats were not received in a 30s period
      )

```

**Comment by jrueb** [comment]
Here is the runinfo with walltime, worker_debug, heartbeat_period, and heartbeat_threshold set as mentioned.
[runinfo.zip](https://github.com/Parsl/parsl/files/6386317/runinfo.zip)

**Comment by jrueb** [comment]
After further testing I think the `result_outgoing` connection of `process_worker_pool` `Manager` gets broken. Is there a reason why there are no heartbeats being sent over it?

**Comment by yadudoc** [comment]
If the Managers are connecting and then losing connection that might be an issue to discuss with your network admins. In the last log you shared, I do not see the HighThroughputExecutor detecting any Manager disconnects, but the logs show that all dispatched tasks finish execution. Can you share your latest logs please?

**Comment by jrueb** [comment]
There are no changes to the logs. The connections are in the weird state of being connected but still nothing is received.
I would like to discuss this with my admins. If you could provide just a few lines of code that sets up the same type of connections that is used here, it would help a lot.

**Comment by yadudoc** [comment]
Try this script -> https://gist.github.com/yadudoc/a8bba2b31167c08633cfa5563e5fbce7
You'll have to give the worker-side the server address over command line args.

**Comment by jrueb** [comment]
After a discussion with my admins, I have the strong impression that this will not be solved from their side. They are telling me the network is not experiencing any issues and an idle connection being dropped after 30 min is something unreasonable.
However, I will open a small PR for Parsl that fixes this issue.
