### ISSUE TITLE
'partition' argument needed in SlurmProvider although it is documented as optional

### ISSUE THREAD

**Issue by QLeB** [Parsl/parsl#2125]
Using SlurmProvider without specifying 'partition' returns
`TypeError: missing a required argument: 'partition'`
Although it is supposed to be optional:
`Slurm partition to request blocks from. If none, no partition slurm directive will be specified.`

**Comment by benclifford** [comment]
Which version of parsl are you using? it looks like this was supposed to be fixed in 4a726d1d5a613d0f4641ad07714b1371009c1fe6, issue #518.

**Comment by benclifford** [comment]
oh, I see what's happening.

There are two different meanings of optionality floating around.

If you specify a parameter `partition=None`, then this should work for you.

Probably that documentation should be clarified to indicate that `partition=None` is a required parameter.

**Comment by QLeB** [comment]
That's the latest 'desc' branch. Yes you are right it's working with `partition=None`. Thanks!
