### ISSUE TITLE
How to join the parsl slack channel?

### ISSUE THREAD

**Issue by nirandaperera** [Parsl/parsl#2145]
**Describe the bug**
I would like to join the parsl slack channel. The link in the contributing guide seems to have expired! Could you please send me an alternative link?

**Comment by benclifford** [comment]
try this: https://join.slack.com/t/parsl-project/shared_invite/zt-4xbquc5t-Ur65ZeVtUOX51Ts~GRN6_g

I'll update the contributing guide.
