### ISSUE TITLE
Running python_app(join=True) Can Select Invalid Executor

### ISSUE THREAD

**Issue by Oddant1** [Parsl/parsl#2147]
**Describe the bug**
If you have a HighThroughputExecutor in your config, and you run a python_app(join=True), it can end up running on the HighThroughputExecutor. This causes a very gross and non-descriptive type error to do with not being able to pickle _queue.SimpleQueue objects because (to my understanding) join apps should not be running on a separate process. This can happen if you specify a HighThroughputExecutor, or if you let it choose at random, and it randomly chooses a HighThroughputExecutor. This makes it difficult to track what is happening because if it chooses a ThreadPoolExecutor, it works. This non-deterministic behavior made me think I had some sort of race condition at first.

**To Reproduce**
1. Setup parsl 1.1.0 with Python 3.8 on Linux Mint 20.2 (this is my environment, this issue probably applies to more environments).
2. Setup a config with a HighThroughputExecutor.
3. Invoke a python_app(join=True, executors=[the HighThroughputExecutor]).
4. Observe error (at the end of a very long and gross traceback).
___
![image](https://user-images.githubusercontent.com/10642616/141212108-f3aadab9-fff6-42de-af3a-c6c098c9d72a.png)
___

**Expected behavior**
Don't let this happen. If a python_app is run with join=True, don't put it on an executor that is not local to the main process. If they select a HighThroughputExecutor specifically, tell them not to. Maybe I'm just missing some extra utility that python_app(join=True) is meant to allow over a join_app.

**Environment**
 - OS: Linux Mint 20.2
 - Python: 3.8
 - Parsl: 1.1.0

**Distributed Environment**
- Running the parsl script on my laptop.
- The workers are running on the same laptop.

**Comment by benclifford** [comment]
The ability to write python_app(join=True) is a relic from before @join_app existed as a separate definition - there shouldn't be any intended functionality that you can't get with @join_app.

The right fix is probably to remove that parameter from python_app so that it can't be specified by a user at all, which would need a little bit of internal restructuring on how join_apps and python_apps are implemented.

Thanks for your report.

**Comment by benclifford** [comment]
#2621 changes this behaviour so that you cannot invoke python_app with a join parameter
