### ISSUE TITLE
Usage tracking with certain missing network causes 20s startup delay.

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#220]
Usage tracking appears to happen synchronously when something like this is called:

    dfk = parsl.DataFlowKernel(executors=[workers])

When something is wrong with the network that causes long delays (for example, slow/timing-out name resolution - for example, in a container with a weird network configuration), startup of the DataFlowKernel is delayed, before the program then successfully continues onwards.

In my case, I'm running in a docker container where the `/etc/resolv.conf` resolver points to a not-responding IP address, and the startup delay is 20 seconds.

No log message appears to be output describing the cause of the delay.

This occurs with several versions, including 48d46ba04afcd86c984953c1d75b7818101cf87f

**Comment by yadudoc** [comment]
@benclifford What should be the correct behavior ?
1. We can try to send a message asynchronously and abort if it doesn't work
2. We can inform the user of the delay if we wait for sending to complete.

**Comment by benclifford** [comment]
I think usage tracking should be async and never significantly delay workflow start or cause any other workflow problems in the case of problems.

**Comment by yadudoc** [comment]
@benclifford I'm running tests on this, and if there's no network, I see that being caught and reported in the logs. Is it possible that the network is mis-configured ? I've pushed some code that puts a time limit on send. Not fully async.

**Comment by benclifford** [comment]
It specifically is when system hostname resolution hangs: you should be able to recreate that by changing a linux machine so that `/etc/resolv.conf` contains only the line:

```
nameserver 2.2.2.2
```

That's a relatively common network problem that I encounter in real life as the cause of "mysterious hangs" in loads of software.

**Comment by benclifford** [comment]
I've just tried dfccb8a, and I no longer experience this delay (after checking that I *do* get the delay against master)
