### ISSUE TITLE
DataFlowKernel cleanup is not aggressive enough

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#221]
dfk.cleanup() can take a very long time to shutdown.

It looks like before shutting down, all queued apps that do not have unsatisfied dependencies are executed. (subsequent apps with dependencies do not execute before shutdown)

In my example, this means that a workflow will continue to run for several hours draining a pile of 15 minutes apps before shutdown; it wasn't initially apparent that the subsequent failure to continue with the workflow was because cleanup was in progress.

My example code sets itself up like this:

    workers = parsl.ThreadPoolExecutor(max_workers=5)
    dfk = parsl.DataFlowKernel(executors=[workers])

**Comment by yadudoc** [comment]
@benclifford Here you are creating the worker pool explicitly, and the DFK is not responsible for resource handling. So you end up with cleanup(

**Comment by benclifford** [comment]
By "explicitly", does that mean "declared in the python file rather than in the json config file?"

**Comment by annawoodard** [comment]
I vote that we remove this mode of declaring the dfk, if it results in different behavior:
```
workers = parsl.ThreadPoolExecutor(max_workers=5)
dfk = parsl.DataFlowKernel(executors=[workers])
```
It is true that in some cases users may wish to have more control over executors, as this mode allows, but I think that can be solved with class-based configuration (which will allow us to remove the provider factory) as proposed in #133.

**Comment by benclifford** [comment]
I changed to this:

``
from parsl.configs.local import localThreads as config
dfk = parsl.DataFlowKernel(config=config)
``

It looks like it still drains some of the queued apps over a period of time, but now also throws an exception as some (but not all) of the apps complete:

```
RuntimeError: cannot schedule new futures after shutdown
```

I'll note that in both cases, the `dfk.cleanup()` call returns very fast (less than 0.1 seconds) and job execution continues even after it has returned.

**Comment by yadudoc** [comment]
Okay, I'm tagging this as a bug.

**Comment by benclifford** [comment]
Attached is the workflow that is giving me the long-slowdown problem.

This should print the string `X12` to console (indicating that drk has returned from cleanup) very early on in the run, and then continue running stuff for a minute or so afterwards.

[fake_drp_pipeline.txt](https://github.com/Parsl/parsl/files/1940185/fake_drp_pipeline.txt)

**Comment by yadudoc** [comment]
It looks like this might still be an issue with threads.
