### ISSUE TITLE
End of workflow behaviour to discard some unexecuted work is surprising

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#222]
When reaching the end of the main Python script of a workflow, `dfk.cleanup()` happens implicitly. This causes some unexecuted apps to be discarded.

I think less surprising behaviour is that when you reach the end of the main Python script, any work that has been asked for actually gets done before exit.

The present correct thing to do in a workflow, I think(?), is record which Apps you have launched, and wait for all of them at the end. I would like to not have to do that.

**Comment by annawoodard** [comment]
Agreed. I think we would want to add a `dfk.wait()`-type function. If the process receives sigterm or sigkill, then we call `dfk.cleanup()` and don't ewait, otherwise we wait.

**Comment by benclifford** [comment]
My current proposal is that at DFK cleanup:

i) puts parsl in a state where it refuses to create new AppFutures
ii) does a wait on every app future in the dfk.tasks structure

Every app known to exist will be waited for; code which subsequently tries to launch a new app will be refused (for example, getting an exception saying the DFK is shutting down)

**Comment by benclifford** [comment]
crossref #313

**Comment by benclifford** [comment]
That latter problem was fixing in PR #612.
