### ISSUE TITLE
executors/ipp: controllers linger after ungraceful shutdown

### ISSUE THREAD

**Issue by ahayschi** [Parsl/parsl#223]
While debugging I'm starting and stopping a lot of workflows in weird states, so I just ctrl-c the workflow. Should SIGINT be captured to perform cleanup? Right now, the controllers linger until I manually kill them.

**Comment by annawoodard** [comment]
Note this may be causing engine failures for @madduri and @daheise.

**Comment by benclifford** [comment]
crossref #1318

**Comment by benclifford** [comment]
IPP is gone - closing with no further fix necessary.
