### ISSUE TITLE
Add pickling convenience functions for common unpickleable classes

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#227]
Reported by @WardLT. 

Some objects are not pickleable (for example, instances of the Keras `Model` class.) It would be nice if we provided convenience functions to make these pickleable. @WardLT found a nice example for Keras models [here](http://zachmoshe.com/2017/04/03/pickling-keras-models.html). We should also catch the pickling error and provide useful instructions for dealing with it.

**Comment by WardLT** [comment]
FYI: For that method to make Keras picklable, ot seems like you need to call `make_keras_picklable` on each of the worker threads. Something like:

```python
@App('python', dfk)
def f(x):
  from foo import make_keras_picklable
  make_keras_picklabe()
```

**Comment by WardLT** [comment]
[Answering you four years later!] Yea, this is a user problem or problem with the libraries and not a parsl problem.
