### ISSUE TITLE
Checkpoints will not reload from a run that was Ctrl-C'ed

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#232]
If I use ctrl-c to kill a run, the checkpoint file will not load into a subsequent run:

```
2018-04-25 10:31:39 parsl.dataflow.dflow:692 [ERROR]  Failed to load Checkpoint: /home/benc/parsl/desc-skeleton/runinfo/001/checkpoint/tasks.pkl
Traceback (most recent call last):
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 672, in _load_checkpoints
    data = pickle.load(f)
TypeError: __init__() missing 2 required positional arguments: 'reason' and 'exitcode'
```

My gut feeling is that it is having trouble loading a serialised exception, but I haven't probed.

**Comment by yadudoc** [comment]
Looks like we need a signal handler in the DFK. I suspect that we weren't writing a checkpoint at all in your case. Can you check if the checkpoint files were empty ?

**Comment by benclifford** [comment]
Those tests look broadly fine, though I'm having trouble replicating what I think is the expected behaviour on my laptop when I kill things other than by pressing control-C.

In any case, whatever is left behind when I kill stuff with a ctrl-C does not upset checkpoint restore, so recent changes have seem to have fixed this bug, yes.

**Comment by yadudoc** [comment]
Okay, I'm closing this then.
