### ISSUE TITLE
Add regression test for #230

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#233]

**Comment by annawoodard** [comment]
Whatever we implement for this, we should port over to the existing checkpointing tests. They parse the log, but I think we need something more robust-- all that tells us is that we _said_ we checkpointed :smile:

**Comment by benclifford** [comment]
I think there's a useful higher level checkpointing test: start a dfk. run a bunch of tangled stuff. shut down. start a dfk. run the tangled stuff again, with a global-ish flag set to tell the test-supplied app code: "if you run again, fail". also run a bunch of new stuff that depends on checkpointed results, and check that that runs correctly.

**Comment by yadudoc** [comment]
I'm writing this.
1. Start dfk 
2. generate rand numbers from app and checkpoint per task
3. stop
4. Restart dfk from checkpoint
5. run same apps again and check if "all" the apps return the same rand numbers.

**Comment by annawoodard** [comment]
done
