### ISSUE TITLE
Live visualization of execution graph

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#24]
This feature is motivated by Hemant's request to enable visualization of the execution graph and more importantly simplify the user-flow involved in determining failures, retries and recovery.

Here's a breakdown in terms of priority:

- [x] Visualize the DAG with tasks as vertices and futures/dependencies as edges
- [x] Update the DAG periodically by polling the tasks data structure in the dfk
- [x] Color code the vertices, mapping the run states
- [x] Enable hover to show status / fail codes/ exceptions etc as appropriate
- [ ] Enable editing of the task ~~app~~ args
- [ ] Design error flows to describe automated healing and user-assisted healing.
- [ ] Enable resetting of task state to indicate a retry request

**Comment by danielskatz** [comment]
I'm certainly ok with this in general, but am not sure how we prioritized it for parsl 0.4 rather than later.

**Comment by benhg** [comment]
1,2,3,4 now done.

**Comment by danielskatz** [comment]
Do these numbers refer to items in the initial checklist?  If so, can just check them off?

**Comment by yadudoc** [comment]
@benhg Could you make a pull request that I could look at ?

**Comment by benhg** [comment]
@danielskatz I don't think I had access to edit the issue

@yadudoc I'm doing this as a jupyter widget and I don't really know where I should put it. Let me know where to make the pull request and I will.

**Comment by yadudoc** [comment]
Deferring for 0.5.0.

**Comment by yadudoc** [comment]
Deferring for 0.6.0

**Comment by yadudoc** [comment]
Closing since most of the features described here have either been implemented or pared down to what is useful in practice.
