### ISSUE TITLE
Retries not working

### ISSUE THREAD

**Issue by avidalto** [Parsl/parsl#2416]
**Describe the bug**
The retries parameter in the Parsl Config is not behaving as expected. Setting this parameter to >0 does not cause Parsl to relaunch apps that fail. 

**To Reproduce**
Launch the code below using parsl version 1.2.0.

```
import parsl
print(parsl.__version__, flush = True)
from parsl.app.app import python_app, bash_app
from parsl.config import Config
from parsl.executors import HighThroughputExecutor


@python_app
def test(fail = False, stdout='std.out', stderr = 'std.err'):
    if fail:
        a = 1/0
    return 'Hello'

if __name__ == '__main__':

    config = Config(
        executors = [HighThroughputExecutor()],
        retries = 2
    )
    print('Loading Parsl Config', flush = True)
    parsl.load(config)

    fut = test(fail = True)

    print(fut.result())
```

**Expected behavior**
I expected the app to be launched again and see the `ZeroDivisionError: division by zero` appear more than once. 

**Environment**
 - OS: Linux
 - Python version: 3.10.4
 - Parsl versionL 1.2.0

**Distributed Environment**
- Where are you running the Parsl script from ? Docker container in cloud VM
- Where do you need the workers to run ? Local

**Comment by benclifford** [comment]
This code ```    print(fut.result())``` will only execute after all retries have been attempted. It will return the error message of the final retry attempt.

In the runinfo/*/parsl.log log file for your run, you should see lines like this:

```
2022-09-05 14:06:04.498 parsl.dataflow.dflow:289 [DEBUG]  Task 0 try 0 failed
...
2022-09-05 14:06:04.522 parsl.dataflow.dflow:289 [DEBUG]  Task 0 try 1 failed
2022-09-05 14:06:04.522 parsl.dataflow.dflow:330 [INFO]  Task 0 marked for retry
...
2022-09-05 14:06:04.546 parsl.dataflow.dflow:289 [DEBUG]  Task 0 try 2 failed
2022-09-05 14:06:04.546 parsl.dataflow.dflow:333 [ERROR]  Task 0 failed after 2 retry attempts
```

showing the tries happening.

**Comment by avidalto** [comment]
Thanks! I missed that before
