### ISSUE TITLE
Describe code state more precisely in the logging

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#242]
We currently log the Parsl version. For debugging, it would be convenient to log the most recent commit hash and whether or not there are any additional changes.

**Comment by yadudoc** [comment]
We badly need this!

**Comment by benclifford** [comment]
I found this information really useful when debugging other people's stuff.

Swift had some scripting that did pretty much exactly this, which was run as part of the build process.

This is the current version:
https://github.com/swift-lang/swift-k/blob/master/libexec/svn-revision
