### ISSUE TITLE
walltime app function parameter modifies task_record func_name

### ISSUE THREAD

**Issue by avidalto** [Parsl/parsl#2449]
**Describe the bug**
When the walltime special parameter is passed to a Parsl app the `task_record['func_name']` parameter is set to "wrapper" instead of to the function's name. 

**To Reproduce**
Launch the code below using parsl version 1.2.0:
```
import parsl
print(parsl.__version__, flush = True)
from parsl.app.app import python_app, bash_app
from parsl.config import Config
from parsl.executors import HighThroughputExecutor


@python_app
def test(stdout='std.out', stderr = 'std.err', walltime = 5):
    from time import sleep
    sleep(1)
    Fail = 1/0
    return 'Hello'

def retry_handler(exception, task_record):
    print(task_record['func_name'], flush = True)
    return 1

if __name__ == '__main__':

    config = Config(
        executors = [HighThroughputExecutor()],
        retries = 2,
        retry_handler = retry_handler
    )
    print('Loading Parsl Config', flush = True)
    parsl.load(config)

    fut = test()

    print(fut.result())

```

It will print "wrapper" if the walltime parameter is present and test otherwise. 

**Expected behavior**
The code should print the function's name (test).

**Environment**
- OS: Linux
- Python version: 3.10.4
- Parsl version: 1.2.0

**Distributed Environment**
- Where are you running the Parsl script from ? Local
- Where do you need the workers to run ? Local

**Comment by benclifford** [comment]
This bug is also present in more recent parsl `master` at 50044b7f67cbe34ec0c612a9f16507b1383e53a4

This behaviour also shows up in log messages:

```
parsl.dataflow.dflow:929 submit INFO: Task 0 submitted for App wrapper
```

should show the app name, but instead shows `wrapper`.

**Comment by benclifford** [comment]
@avidalto this should be fixed by https://github.com/Parsl/parsl/pull/2450

**Comment by avidalto** [comment]
Thanks! It is working after the fix
