### ISSUE TITLE
Update parsl decorator

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#246]
Now that we are removing the DFK from the app decorator we would like to remove required parameters. 

So our proposal is to have the following two decorators:
`@pythonapp`
`@shellapp `

To support params we can then include them if needed
`@pythonapp(sites=[])`

**Comment by danielskatz** [comment]
We've called them bash apps so far.  Is shellapp better?  What about extapp?

**Comment by djf604** [comment]
Will `@App()` still exist for backward compatibility?

**Comment by yadudoc** [comment]
@djf604 We won't break backward compatibility. Slowly will be deprecated, with warning messages.

**Comment by annawoodard** [comment]
See the SO answer [here](https://stackoverflow.com/a/19017908/5111510) on how we can write, for example, 

```
def python_app(function=None, data_flow_kernel=None, walltime=60, cache=False, executors='all'):
    foo
```

which can be called either as
```
@python_app(cache=True)
def foo(bar=1):
    baz
```
or, if using all defaults, as
```
@python_app
def foo(bar=1):
    baz
```

**Comment by annawoodard** [comment]
The new decorators have been added in 0.6, but we should consider this issue resolved when tests are added.
