### ISSUE TITLE
Real-time usage tracking

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#248]
For DESC we need to be able to specify a remote location to send usage information.  The main item here is to develop a model for providing real-time information from Parsl to a DESC database (probably running in the cloud). We will work with the DESC team to make this data available for a UI to display the information to users. 

From a configuration perspective the user should be able to select the DESC config (which defines the remote storage location). 

Here is the schema we have come up with: 
 
Workflow level
* Workflow name (default: script name)
* Execution start time, completion time
* Executing user (linux username, in the future we could get Globus identity information)
* Site name(s)
* Site hostname(es)
* Summary statistics (rolled up from the task level)
* Number of tasks completed/failed/pending
* Number of executions of this workflow
* Version (if defined)
*  Link to runinfo folder (submit scripts, job info, etc.) 

Task level
* App name
* State: completed/failed/pending + optional reason
* Type: Bash/Python
* Start time, completion time
* Task ID
* Input files (path)
* Output files (path)
* Link to logs (path)
* Logs (referenced and accessible via Globus)
* Stdout
* Stderr
* Runinfo
* Controller log
* Submit scripts
* Job info

**Comment by yadudoc** [comment]
https://github.com/Parsl/parsl/pull/371 fixes this.
