### ISSUE TITLE
Report application progress to external systems

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#251]
We should be able to stream the status of the workflow to external systems such as a queue or database. This would enable visualization and dashboards to get their live data without being tied to parsl.
Parsl should report the status of apps and the resources on which they are being processed.

This is a DESC requirement.
Also related to #5, #42, and most closely with #248 which goes into details of information that would be interesting to capture.

**Comment by benclifford** [comment]
My initial thought is that this should be via a Python callback with a reasonably documented API, plus whatever DESC specific things we need implementing that callback?

**Comment by yadudoc** [comment]
@kylechard With the merge of #371 can we close this one ? The basic functionality is supported and further improvements should be tracked separately.
