### ISSUE TITLE
Output files from apps

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#26]
If we have an app that produces no output files we call such an app like : 

    <var:App_fu> = app_func ( .... )

However if the app has outputs, the return is a tuple : 

    <var:App_fu>, [ <var:Data_fu> ... ] = app_func ( ...., outputs=[ Files ....])

When this was last discussed, one proposed solution was to simply return the app future in both cases, and have the data futures be a property of the app future. This would look like this : 

    # Single return
    app_fu = app_func ( ... , outputs=['a.txt', 'b.txt'] )
    # User has to unpack outputs separately 
    x, y = app_fu.outputs

Right now, we have the outputs property added, but continue to return a tuple of app future and the list of data futures. I propose that these changes should go into 0.3.0.

**Comment by kylechard** [comment]
Agreed.  I like the model with data futures as a property of the app future.

**Comment by yadudoc** [comment]
This is going in as a non-backward compatible update in Parsl-0.3.0. Closing.
