### ISSUE TITLE
htex termination (and other scale-in-by-quantity) does not scale in blocks that haven't registered yet

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2627]
**Describe the bug**
When scaling in by quantity of blocks (at parsl exit, or in the htex scaling strategy), the htex scale in code chooses which blocks to scale in, up to the specified quantity.

It does not choose blocks which have not got as far as a manager in that block registering - on my laptop, because execution is happening so fast, but I think in the HPC case, this will apply to blocks waiting in the queue.

These blocks are then abandoned by parsl - left running in my laptop, and in the HPC case, I expect occupying space in the queue, to eventually run.

The code in question is here:
 https://github.com/Parsl/parsl/blob/33398b15cbb20ddc5c273d22015d6c18351337c4/parsl/executors/high_throughput/executor.py#L666

Crossref related #2120 which talks about picking available blocks in an unusual order.

**Expected behavior**
Blocks in queues should be scaled in when scaling by quantity.

Especially, they might be considered ahead of blocks which are already running (although that order is probably a policy decision, not a technical one, taking into account things like cost of occupying idle nodes, immediacy of worker availability on workload increase, "fresh" walltime vs partially used walltime...)

**Environment**
my laptop, parsl master 33398b15cbb20ddc5c273d22015d6c18351337c4

**Comment by benclifford** [comment]
this code also hangs during certain shutdown patterns: it asks the interchange for a list of connected managers, but if the interchange has already gone away (for example, due to shutting down with a ctrl-C), then this (disguised-as-a-property) interprocess call hangs (rather than fails).
In the shutdown case there is no need to discover which blocks are least idle: they *all* should be scaled in.

**Comment by svandenhaute** [comment]
Me and several others have struggled with this issue when running on HPCs with `SlurmProvider`s!

**Comment by benclifford** [comment]
note for whoever fixes this: there's probably also some policy to bake in about which unregistered blocks to scale in first. Probably the default/only behaviour should be to scale in later submitted (bigger block-id) blocks before earlier ones, if they haven't registered/started running, on the basis that earlier submissions will probably be launched soonest, so are in a sense more valuable than the later submitted ones.

**Comment by benclifford** [comment]
fixed by #3353
