### ISSUE TITLE
quickstart: download needed?

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#27]
On the quickstart part of the README, should we remove item 1 (download), since I think the pip install means that a manual download is not needed?

**Comment by yadudoc** [comment]
@danielskatz I think I left that in because we needed to clone the repo to get tutorials to the local machine.
Maybe we should split the tutorial to a different repo and merge it into the main repo as a submodule. What do you think ?

**Comment by danielskatz** [comment]
I think this makes sense.

**Comment by yadudoc** [comment]
The parsl_demos repo already has the tutorial material broken out. Please reopen if this is still an issue.
