### ISSUE TITLE
Understanding blocks with respect to MPI parallel sub tasks 

### ISSUE THREAD

**Issue by jan-janssen** [Parsl/parsl#2723]
I would like to understand how the parsl blocks work with MPI parallel sub tasks: 
https://parsl.readthedocs.io/en/stable/userguide/execution.html#blocks

My tasks typically fall in either of the following four categories: 

| **Code type / Parallelism**             | **serial**        | **MPI parallel** |
|-----------------------------------|---------------|-----------------|
| **Python task**                                | @python_app | ?                          | 
| **Code without Python bindings** | @bash_app    | ?                          |

For the case of MPI parallel codes without Python bindings I currently use https://flux-framework.org and I saw there is a flux interface in parsl but as far as I understand it only covers serial python tasks.

**Comment by WardLT** [comment]
I'll also update the documentation to make it clearer that the "multi-node tasks in a single block" is clunky at the moment.

**Comment by jan-janssen** [comment]
Ok, thanks a lot for the explanation.
