### ISSUE TITLE
Globus data provider

### ISSUE THREAD

**Issue by KiwiFac3** [Parsl/parsl#2734]
**Describe the bug**
Testing the Globus data_provide whenever I try to get results out of my @python_app on this line https://github.com/Parsl/parsl/blob/master/parsl/data_provider/globus.py#LL97C9-L97C55 it terminates because it gets the following error "TypeError: task_wait() takes 2 positional arguments but 4 were given" 

**To Reproduce**
Steps to reproduce the behavior, for e.g:
1. Setup Parsl 2023.1.23 with Python 3.9.13 on cluster
2. Run a test script [This is my test https://github.com/KiwiFac3/Falcon2Parsl/blob/main/Test/Globus.py ( I had the last line commented since it the one terminating the program)]
3. Wait 5 mins

**Expected behavior**
The test should keep running until the transfer of the file is done

**Environment**
 - OS: Ubuntu
 - Python 3.9.13
 - Parsl 2023.1.23
 - globus-sdk: 3.15.1

**Distributed Environment**
- Where are you running the Parsl script from ? Laptop/Workstation or Compute node
- Where do you need the workers to run ? Same as Parsl script

**Comment by benclifford** [comment]
Can you add which version of the globus-sdk package you are using:  `pip list | grep globus-sdk`

**Comment by KiwiFac3** [comment]
globus-sdk: 3.15.1

**Comment by benclifford** [comment]
@KiwiFac3 looks like PR #2735 should fix this - can you try it out?
