### ISSUE TITLE
Enable manual specification of CPU affinity

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#2739]
**Is your feature request related to a problem? Please describe.**
The presets for cpu affinity (e.g., block) for HTEx do not cover all system architecture. 

**Describe the solution you'd like**
Make it so that users can provide mappings of worker to CPU threads as an option to `cpu_affinity`

**Describe alternatives you've considered**
Continue writing new presets, which we may still do. However, it means users have to alter the Parsl library in order to experiment with different affinity approaches

**Comment by benclifford** [comment]
@WardLT @cms21 - I think this is what PR #2990 did?

**Comment by WardLT** [comment]
Indeed. Let's close
