### ISSUE TITLE
Link to or provide instructions for example Perlmutter config

### ISSUE THREAD

**Issue by arosen93** [Parsl/parsl#2752]
Since Cori is now retired, it can be removed from the [Configuration](https://parsl.readthedocs.io/en/stable/userguide/configuring.html?highlight=nersc#cori-nersc) section of the docs. In its place, it would be worthwhile to add (or link to) an example config for Perlmutter at NERSC, the details of which can be found [here](https://docs.nersc.gov/jobs/workflow/parsl/).

**Comment by benclifford** [comment]
PR #2753 reworks the NERSC-related documentation to point to NERSC's detailed parsl page, rather than showing an example configuration.
