### ISSUE TITLE
Docs "source" link not linked with `SlurmProvider`

### ISSUE THREAD

**Issue by arosen93** [Parsl/parsl#2758]
On [this page](https://parsl.readthedocs.io/en/latest/stubs/parsl.providers.SlurmProvider.html) for the `SlurmProvider`, if you click the [source link](http://github.com/Parsl/parsl/blob/master/parsl/providers.py), you get a 404 error.

**Comment by benclifford** [comment]
see PR #2624 for some experimentation trying to fix this: it's a bit more complicated than I initially expected...

**Comment by arosen93** [comment]
Ah wow, wasn't expecting that!

(Feel free to close this as a duplicate)

**Comment by benclifford** [comment]
Dupe of #2604
