### ISSUE TITLE
Consider removing emphasis on the `DataFlowKernel` in the docs

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#278]
We might want to relegate discussion of the DFK to the more advanced section of the docs. For many applications, simply running `parsl.load` is sufficient. I strongly feel that as part of the class-based configuration shuffling we're doing, it will be simpler and less bug prone (on our side and user-side) to have the `Config` object be the only mode of specifying options (in other words, dispense with the ability to override options in the DFK constructor-- that removes places people can get confused about what precedence options have. There isn't really a cost; if they are importing a config and then overriding various options, it should be the same if they do it in the `Config` before loading or passing options to the constructor. Overriding options in the `Config` makes it explicit on their side what is going in.) If we _do_ go that route, then exposing the DFK to users seems even less necessary. I'm putting this out there now so I don't forget, but we should make the call after the class-based configs are worked out.

**Comment by annawoodard** [comment]
The way I see it, we have a limited quota of "user attention" people are willing to spend reading docs; the fewer vocab words we can throw at them, the more time they'll have for other things.

**Comment by benclifford** [comment]
I agree with this.
