### ISSUE TITLE
Any way for Parsl to stop running if there are no more apps to be launched?

### ISSUE THREAD

**Issue by arosen93** [Parsl/parsl#2780]
I imagine this may already be a feature, in which case I just had trouble finding it in the docs and it might be worth highlighting.

I am curious if there is a way for Parsl to stop running if there are no more apps to be launched. I'm envisioning a scenario where I request something like 1024 nodes. Of course, they will continually pull in work as it is made available, but the concern I have is "what happens if all the work is done in 12 hrs even though the walltime is set to 24 hrs." That'd be a lot of wasted compute, so I was trying to find the corresponding flag to enable this behavior if/when desired.

Of course, there is a subtlety here: it's possible that a `PythonApp` might launch another `PythonApp`, so at a given time, it could look like there are no tasks left when in reality there might be more coming downstream. So, I guess my question is more accurately phrased as "Any way for Parsl to stop running if there are no more apps to be run _and_ all running jobs have finished."

Also, it would be _really_ cool if there were a way for Parsl to start releasing allocated nodes towards the end of such a process so that the full 1024 nodes aren't being wasted when really only (say) 4 nodes are still needed for the remaining tasks. This is much more complex, and I imagine it's not currently a feature, but if it is please let me know!

**Comment by benclifford** [comment]
The `simple` scaling strategy will scale an executor down to min_blocks if there have been no tasks at all on that executor for a specific period of time. That happens here: https://github.com/Parsl/parsl/blob/4c4cc7abfe22b102fc52167f5a27bcdda6e149d3/parsl/dataflow/strategy.py#L219

That max idle time is defined in the parsl config with the max_idletime option in here:

https://parsl.readthedocs.io/en/stable/stubs/parsl.config.Config.html#parsl.config.Config

**Comment by benclifford** [comment]
> Also, it would be really cool if there were a way for Parsl to start releasing allocated nodes towards the end of such a process so that the full 1024 nodes aren't being wasted when really only (say) 4 nodes are still needed for the remaining tasks. This is much more complex, and I imagine it's not currently a feature, but if it is please let me know!

This was implemented in a very limited and specific way: if an entire block is empty, then the `htex_auto_scale` strategy should remove that block. *however* there is nothing that causes blocks to drain to become idle (and instead, tasks will continue to be allocated across all workers in all blocks) - so in any busy case, I think its quite unlikely that blocks will become idle even if there isn't enough work to use multiple blocks.

there's a tension here between that scaling strategy preferring many blocks with small numbers of workers (the original usecase from @yadudoc I think was one kubernetes worker per blocks) - vs HPC systems that prefer one block of 1024 nodes for ease of their own batch scheduling.

**Comment by arosen93** [comment]
> The `simple` scaling strategy will scale an executor down to min_blocks if there have been no tasks at all on that executor for a specific period of time. That happens here:
> 
> https://github.com/Parsl/parsl/blob/4c4cc7abfe22b102fc52167f5a27bcdda6e149d3/parsl/dataflow/strategy.py#L219
> 
> That max idle time is defined in the parsl config with the max_idletime option in here:
> 
> https://parsl.readthedocs.io/en/stable/stubs/parsl.config.Config.html#parsl.config.Config


Awesome! So would one then set `min_blocks` to 0? Also, thanks for the tip about the `max_idletime`. From the NERSC docs, I was under the impression that `max_idletime` was the maximum wait time for getting info back from `squeue`, not the maximum idle time of Parsl as a whole, but this makes more sense to me.

**Comment by benclifford** [comment]
closing this as question answered
