### ISSUE TITLE
Consider changing our `block` terminology

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#279]
I propose changing `taskBlock` and `nodes` to `tasks_per_node` and `nodes_per_block`. Instead of users having to learn: 
- Block concept
- Node concept
- Node parameter definition (Node parameter = Nodes / Block)
- TaskBlock concept
- TaskBlock parameter definition (TaskBlock parameter = TaskBlocks / Block)
- Task concept

They would just have to learn:
- Block concept
- Node concept
- Task concept

The parameter definitions would be clear from the name. For example, with the current terminology, you would need to look at the illustrations in the docs to understand the definition. On the other hand, I think most people could draw the corresponding diagram given the names `tasks_per_node` and `nodes_per_block`.

Example 1
----------
**current**
```
"block": {
    "taskBlocks": 4,
    "nodes": 1
}
```

**proposed**
```
"block": {
    "nodes_per_block": 1,
    "tasks_per_node": 4
}
```
![n1_t4](https://user-images.githubusercontent.com/5114833/40025382-ff02696c-5796-11e8-9d42-abccd6803ba5.png)

Example 2
----------

**current**
```
"block": {
    "taskBlocks": 2,
    "nodes": 4
}
```

**proposed**
```
"block": {
    "nodes_per_block": 4,
    "tasks_per_node": 1 / 2.
}
```
![n4_t2](https://user-images.githubusercontent.com/5114833/40025377-fd62435c-5796-11e8-98d6-281d5661a59d.png)

**Comment by yadudoc** [comment]
Can we call this done ?
