### ISSUE TITLE
investigate task-end-to-task-end delays in Work Queue

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2801]
**Describe the bug**
Performance is poor in the work queue executor when running sequential tasks: the time from one task ending to the next task starting is around 1 second. I'm not sure if this is inside the parsl wq executor code, or inside core wq.

**To Reproduce**
submit two tasks, one which depends on the other. observe a 1 second delay between task 1 completing on the worker and task 2 starting on the worker.

**Expected behavior**
This could be much faster.

**Environment**
my laptop

cc @khk-globus

**Comment by benclifford** [comment]
looks like most of the time in the test case is being spent in this line: `t = q.wait(1)` waiting for a result (that will never come) for one second before submitting the next task.

Things I tried:

* Make 1 smaller - that parameter is an int.
and that parameter can only go down to 1 (second) by the looks of it - setting the timeout to 0 seems to make the call wait up to 1 second. So I can't try a smaller value here.

* Look at q.stats.tasks_with_results - this seems to be 0 always, so I can't poll for task readiness faster. I haven't investigated further what is going on there.

cc @dthain

**Comment by benclifford** [comment]
link to that line:

https://github.com/Parsl/parsl/blob/99701e819f7a85a40194b201cb6a4baf06e91d84/parsl/executors/workqueue/executor.py#L965

**Comment by benclifford** [comment]
In htex I've found this "poll one thing for 1s, poll another thing for 1s" behaviour awkward to deal with in one thread. I'm not sure with WQ the two different activities in that thread (submitting a task, and processing results) could happen in two different threads - are there issues accessing work queue from multiple threads?

**Comment by dthain** [comment]
@colinthomas-z80 please take a look at this.  Yes, it appears to be a classic example of the dual blocking wait problem.

**Comment by colinthomas-z80** [comment]
I can reproduce the issue with the wq executor. I put together a similar test with plain work queue and didn't observe the issue. I will do some digging into the executor retrieval loop.

**Comment by colinthomas-z80** [comment]
The above PR avoids the superfluous calls to wait() in between tasks. The performance is a good deal better, although I don't think we have seen the last of the timeout issue
