### ISSUE TITLE
README+ changes

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#29]
I think the README should say what the current version is, and ideally, should include a high-level roadmap, maybe via a link to another .md file.

**Comment by danielskatz** [comment]
thanks for adding the version

**Comment by jhcnz** [comment]
@danielskatz @yadudoc can we close this issue now, or are we still adding a roadmap?

**Comment by danielskatz** [comment]
we still need a roadmap.  I also note that under releases, we just have 0.1 and 0.1.2, but no 0.2, or 0.2.2

**Comment by yadudoc** [comment]
@danielskatz  I've added the missing tags against the commits that bumped up the version numbers.
I think the README should be a quick read and the docs could go into topics like roadmap. We could link to the roadmap section in the docs from the README.

**Comment by danielskatz** [comment]
releases look good

**Comment by danielskatz** [comment]
agree about readme and roadmap - we just need to actually create the roadmap now and then add something in readme to point to it
