### ISSUE TITLE
Parsl dflow structure missing dependency information

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#30]
This is based on a report from @benhg 

The dependency lists help per task in the dataflow kernel datastructures are empty lists. They should contain information of their dependent tasks.

This is blocking @benhg 's work on live visualization of the dataflow graph.

**Comment by yadudoc** [comment]
Tentative fix issued in a6e2d505d76ea8e6943d6ff4316513b355cf2649
@benhg  Please test and confirm.

**Comment by benhg** [comment]
Appears to be fixed. Thanks @yadudoc.
