### ISSUE TITLE
Support worker-side transfer

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#306]
Our current transfer model relies on inserting transfer Apps between existing nodes in the DAG, which are submitted to a locally-running `ThreadPoolExecutor` with several threads. This essentially serializes transfer-heavy work. For scalability when pulling data from external resources, we should consider supporting a model where such apps are submitted to the workers themselves.

**Comment by lukaszlacinski** [comment]
Only transfer apps for files with the 'globus' scheme are submitted to a locally-running ThreadPoolExecutor. The apps are very light tasks that are basically in the waiting state polling a transfer status every 60 seconds or so from Globus.
