### ISSUE TITLE
Radical executor hangs rather than reports error if MPI is not installed

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3070]
**Describe the bug**
When MPI is not installed, the test suite (and so perhaps user applications) hangs on execution rather than report an error that MPI is missing.

cc @AymenFJA 

**To Reproduce**
Run the test suite without MPI installed.

**Expected behavior**
Errors rather than hangs when something will definitely not run.

**Environment**
my dev environment, parsl 2024.02.12

**Comment by AymenFJA** [comment]
@benclifford by `MPI` I am assuming `mpi4py` if so the:

This is fixed/addressed in the current open PR: https://github.com/Parsl/parsl/pull/3060, specifically in this line: 

https://github.com/Parsl/parsl/blob/8026bf5c06febfd5b0e0045d284b353bbca67dec/parsl/executors/radical/executor.py#L156

As any internal error that happens within the master/worker including missing modules like `mpi4py` RPEX should catch it and fail the executor.

This ticket is somehow related to the behavior observed in this ticket: https://github.com/Parsl/parsl/issues/3013.  (termination problem)

Once the PR is merged, this should be addressed.

**Comment by benclifford** [comment]
the case i encountered was if i'm on a fresh install (eg. a fresh container) and haven't said `apt install mpich` - nothing in the Python packaging causes that to happen, because it is in a different packaging universe (debian managed, not `pip` managed) so the user isn't naturally guided towards how to fix this problem.

**Comment by AymenFJA** [comment]
@benclifford should we close this ticket? as the related PR with the fixes is merged?

**Comment by benclifford** [comment]
Yes
