### ISSUE TITLE
missing process_worker_pool `--available-accelerators` commandline gives awkward error

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3110]
**Describe the bug**

If an invocation of process_worker_pool is missing an `--available-accelerators` parameter, this exception happens:

```
    benc@parsl-dev-3-12-9646:~/parsl/src/parsl$ parsl/executors/high_throughput/process_worker_pool.py --cert_dir . --task_port 3 --result_port 4 --cpu-affinity none
    Traceback (most recent call last):
      File "/home/benc/parsl/src/parsl/parsl/executors/high_throughput/process_worker_pool.py", line 851, in <module>
        logger.info("Accelerators: {}".format(" ".join(args.available_accelerators)))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: can only join an iterable
```

**To Reproduce**
Run the above command line.

**Expected behavior**

It would be nicer if this was detected closer to command-line handling, for example, requiring it to be mandatory with a better error message or defaulting to a better value.

**Environment**
my laptop, parsl d1b85100f1826d74b0dc650835ea142ecec9a56d

**Comment by nupurkale78** [comment]
Hi @benclifford ,

I've reviewed the issue you reported about receiving a TypeError when the --available-accelerators parameter isn't included in the process_worker_pool.py invocation. It appears the script expects an iterable for this parameter, which causes an issue when the parameter is omitted. To address this, we could consider a few adjustments: ensuring the argument is compulsory and documenting its necessity, defaulting to an empty list to gracefully handle its absence, or refining our error handling to guide users more effectively when the argument is missing. These enhancements aim to preempt the confusion at the source, making the script more intuitive to use. Do you think these modifications would be suitable for solving the reported issue? Enhancing our command-line interface in such ways could significantly boost usability and error messaging clarity.

**Comment by SobiaAman** [comment]
Hi @benclifford 
Can we make our own function of join e.g `join_args`; in which we uses default  join function but if the non-iterable argument or a none arugment passes by the user instead of giving an error` TypeError: can only join an iterable` it displays a meaningful msg like the `argument passed by user is non-iterable`. Let me know if it will work, i'll do the necessary changes in it and create a PR.
Thanks

**Comment by SobiaAman** [comment]
Hi @benclifford 
i want to do this task.

**Comment by marameref** [comment]
hi @benclifford is this issue still open, i will like to work on it, i am an outreachy candidate and have already successfully worked on https://github.com/Parsl/parsl/issues/3105.
