### ISSUE TITLE
Wait for all tasks to finish before shutting down the DFK

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#313]
We should not shut down the DFK until all tasks have finished. We could add a `wait` or `join` method which the user could call to wait until pending tasks are completed, although I am interested if someone could describe a use case for calling such a function anywhere except the end of the script, in a system where dependencies are taken care of automatically. I favor assuming that the user definitely wants all of their tasks to finish, so we automatically call such a function at the end of the script, and do not require the user to do so.

**Comment by benclifford** [comment]
> although I am interested if someone could describe a use case for calling such a function anywhere except the end of the script, in a system where dependencies are taken care of automatically.

Where I have multiple terminal nodes that aren't all gathered together into a single combining app, and I want to (for example, interactively) keep my executors running (or some other context?), but I want to be able to know that the jobs I've launched have definitely output all their files, then either I contrive a join myself, or I use this DFK-provided join. Then a bit later, I can launch another set of tasks.

**Comment by annawoodard** [comment]
This is related to #221.

**Comment by yadudoc** [comment]
When the dfk.<wait/join> is called there is one tricky case to account for:
Any task launched on a threadPool, could potentially launch more tasks and so the list of tasks will expand while we iterate on it. Iterating on a list that expands asynchronously is generally unsafe. In the future we might even want to allow remote apps to launch tasks somehow.

A potentially interesting side-effect of having dfk.<wait/join> is that we could switch defer task launches until wait it called, at which point the dfk can do resource planning on the available DAG and then do smarter launches. We would be able to borrow some cool features from systems that do static planning on workflow DAGs

**Comment by annawoodard** [comment]
I like @benclifford's implicit-optimized-scheduling proposal.

Optimizing scheduling is more complicated than simply providing a wait/join, so I'm going to split that into its own issue, so that we don't need to wait for the complicated thing before having the simple thing.

**Comment by yadudoc** [comment]
@annawoodard  Might have a solution already.
