### ISSUE TITLE
Move historical documentation pages into a new documentation book

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3138]
**Is your feature request related to a problem? Please describe.**
Our documentation is divided into several "books": for example, the user guide, the reference guide and the developer guide.

Over time, some chapters have become historical: that means they are still interesting, but they don't reflect how things are *now*, and so they get in the way of people trying to read the documentation to understand the current state of things.

**Describe the solution you'd like**

These should move into a new book, called something like Historical Documents.

Make a new directory in docs/ called docs/historical/

Find the various sections in the user guide and dev guide that are titled "Historical: something" and move their files into docs/historical

Make docs/historical/index.rst to list those new files, and remove the moved files from the previous index.rst files for the other books.

Add docs/historical/index.rst to docs/index.rst to make it appear in the main table of contents.

Push a PR and you will see if the docs build OK in the automated test - likely something won't be quite right, so use the error messages and the generated docs to fix whatever is broken with your PR.

**Describe alternatives you've considered**
deleting this stuff and letting interested people find it in git history

**Comment by azharcodeit** [comment]
Hi @benclifford, thank you for the detailed explanation! Could you please take a look at the PR? Your feedback would be greatly appreciated!

**Comment by JO-YE** [comment]
I am interested in this and would like to work on it.

**Comment by SobiaAman** [comment]
Hello @benclifford i've done this task but my previous PR is still pending for review i.e. [#3178](https://github.com/Parsl/parsl/pull/3178) that's why i'm unable to pull request on this task. Kindly have a look on [#3178](https://github.com/Parsl/parsl/pull/3178) so that i create PR on this task as well.
Thanks.

**Comment by JO-YE** [comment]
Hello @benclifford, please take a look at my PR #3174

**Comment by supzi-del** [comment]
Guys, it is a good practice to get issues assigned to you, and then make a PR

**Comment by JO-YE** [comment]
@SobiaAman you can work on multiple pull request by creating a new branch for each PR

**Comment by SobiaAman** [comment]
Hello @benclifford i've made a PR [3191](https://github.com/Parsl/parsl/pull/3191), kindly have a look
