### ISSUE TITLE
Remove banner from MPI docs

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#3142]
**Describe the bug**

There's a banner at the top of the MPI Apps document which is no longer relevant since the MPI Apps functionality has been merged to master. We should remove that banner. I've added a snapshot that shows the banner.

**Expected behavior**

Remove the banner shown below:
<img width="792" alt="Screenshot 2024-03-05 at 12 05 34 PM" src="https://github.com/Parsl/parsl/assets/181489/461e9103-ebb4-4296-9528-59e6b635474c">

**Steps to solution**

1. Remove the note with the `..note::` header from `docs/userguide/mpi_apps.rst`
2. Follow steps here https://github.com/Parsl/parsl/blob/master/docs/README.rst to build and check the docs.

**Comment by rmeis06** [comment]
Hello! I'm an outreachy applicant. I made a PR (https://github.com/Parsl/parsl/pull/3146) for this issue. I believe this removes the old banner. I don't see the banner when I build the docs locally and check on localhost.

**Comment by crocmons** [comment]
Hello, I want to work on this issue as an outreachy contributor. @yadudoc  can you assign me this task?
