### ISSUE TITLE
Things that might be true about AppFuture internal state?

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#318]
I'm trying to understand the innards of AppFuture a bit more.

If you have done anything that relies on a particular parent/super() future, such as waiting on it, it is no longer a valid action to change the choice of future that will be used by subsequent calls.

So:

If you're waiting on super() future, you can't now set the parent future.

If you're waiting on either super() or the parent future, you can't now replace the parent future with a new parent future.

Are those things meant to be true? Or is there more subtlety?

I think I've seen both of the above not be true in a run, and am trying to tie this into race condition(s) I'm experiencing with failing python tasks.

**Comment by yadudoc** [comment]
There are really just two situations:
1. appFuture.result() is called when no parent future has been set
2. appFuture.result() points to the result of the parent future. (this is easy)

In case2, when the user makes a blocking call with appFuture.result(), we wait on the super().result() with the assumption that when the app is completed, the super().set_result is called which allows for the blocking call to return.

If you are waiting for the `super` future, a different thread can set the `parent` future and also add a callback to `parent` to set the result of `super` when it is completed.

Is there a situation where we might want to replace the parent future ? while waiting for the super() ?
Perhaps in the case of failures. In that case we may have some potentially tricky pieces where we try to switch from waiting on one future to another from a retry launch.

**Comment by yadudoc** [comment]
I'll have a look at this and #315, #312, #314  together since they are all related. #314 is a bit more troublesome and we might have to set it for later.
