### ISSUE TITLE
parsl.providers.cluster_provider _write_submit_script should return nothing, rather than constant True

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3234]
**Describe the bug**

_write_submit_script in parsl.providers.cluster_provider indicates failure by raising an exception, and so should not be returning a True (or False) value. Instead it should return None by either `return` on its own, or falling off the end of the method without a return statement.

To tidy this up, change that return handling. Edit the docstring to match.

**Comment by MundiaNderi** [comment]
@benclifford please assign me this issue. I'd very much like to work on it.

**Comment by benclifford** [comment]
ok, go ahead @MundiaNderi

**Comment by jessielin34** [comment]
Hi @benclifford, I've created a pull request for this issue and would love if you could check it out. Thank you!

**Comment by jessielin34** [comment]
@benclifford I've opened a PR for this issue, please review, thank you!

**Comment by mirembe-mariam** [comment]
Hello @benclifford . Kindly review my PR about this issue

**Comment by MundiaNderi** [comment]
Thank you @benclifford here is my PR on a separate branch from the rest of my work : https://github.com/Parsl/parsl/pull/3240/

**Comment by SobiaAman** [comment]
Hi @benclifford please check my PR [#3248](https://github.com/Parsl/parsl/pull/3248)
