### ISSUE TITLE
Clearing loaded DFK on cleaning the DFK in dfk.cleanup()

### ISSUE THREAD

**Issue by Harichandra-Prasath** [Parsl/parsl#3263]
**Is your feature request related to a problem? Please describe.**
Currently after a DFK is cleaned up by dfk.cleanup() ,  it cleans the DFK but not clearing the reference of the DFK. So, we have to call parsl.clear() to remove the loaded dfk to load another new config.  And if we try to load a new without parsl.clear(), it raises a error indicating there is already a loaded config. 

Try 

parsl.load()
parsl.dfk().cleanup()
parsl.load()

**Describe the solution you'd like**
it would be better if dfk.cleanup() can clear the reference as well,  as after dfk.cleanup() we cant load new config as well as pushing new tasks.

**Comment by benclifford** [comment]
PR #3444 fixes this - thanks for your discussion with me on this @Harichandra-Prasath which helped us understand how this behaviour should change.
