### ISSUE TITLE
The README has oddly formatted Python code

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Parsl/parsl#3354]
In the README, the code block example has some odd underlining. I hate reStructuredText so don't know how to fix it offhand. 😢 

![image](https://github.com/Parsl/parsl/assets/8674072/b576cf60-51a9-42b5-8010-2a41ca3aead3)

**Comment by benclifford** [comment]
This sounds like a recent github issue: https://github.com/orgs/community/discussions/113792

I verified that even looking at older readmes, the python codeblocks are now rendered with underlines...

I'll leave this a bit to see if github fixes it in the next few weeks, before trying to hack around it.

**Comment by benclifford** [comment]
Looks like this issue was resolved without further effort on the part of Parsl
