### ISSUE TITLE
Consider renaming 'overrides'

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#336]
In our configuration, `overrides` sounds a bit like something that is going to be run _instead_ of something else, rather than something that is going to get prepended to the command. We should consider something like `prepend` or `prologue`.

**Comment by benclifford** [comment]
agree

**Comment by annawoodard** [comment]
suggestion from @kylechard `scheduler_options` and `worker_init`

**Comment by kylechard** [comment]
To be done after libsubmit merge.

**Comment by benclifford** [comment]
prologue or worker_init seems fine to me.

avoid `*_options` because it isn't options - it's arbitrary shell code in which i can do interesting stuff

**Comment by annawoodard** [comment]
> avoid *_options because it isn't options - it's arbitrary shell code in which i can do interesting stuff (for example, launch my own other processes)

Good point, agreed

**Comment by kylechard** [comment]
Just to clarify my suggestion above. 

scheduler_options should be used for options that are passed to the scheduler (e.g., PBS nodes, etc. )

worker_init should be used for the scripts, env settings, etc. that are run when the worker node is provisioned. _init is quite common in the cloud world, less so in the HPC world.
