### ISSUE TITLE
[DOC] Slurm command reference 

### ISSUE THREAD

**Issue by R1j1t** [Parsl/parsl#3419]
**Describe the bug**
The below line says `Slurm's qsub` but I think it should rather be `Slurm's srun` or `Slurm's sbatch`?
https://github.com/Parsl/parsl/blob/1689a84f0a38c65a8ccf4060b76b474e06280ee1/docs/userguide/overview.rst?plain=1#L86

I hope I am not missing something here, and I am more than happy to open a PR to fix this!

**To Reproduce**
N/A

**Expected behavior**
`Slurm's srun` or `Slurm's sbatch`

**Environment**
 - OS: N/A
 - Python version: N/A
 - Parsl version: 2024.5.6

**Distributed Environment**
N/A

**Comment by benclifford** [comment]
yeah it should say squeue - https://github.com/Parsl/parsl/blob/80f6a7ac21927016a98aa5a71c81dda3fb1a3b5a/parsl/providers/slurm/slurm.py#L267 - PR welcome

**Comment by R1j1t** [comment]
Thank @benclifford for the help!
