### ISSUE TITLE
Parsl creates hidden log files, doesn't clean them up

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#3437]
**Is your feature request related to a problem? Please describe.**
I didn't know Parsl was creating so many log files because they were hidden. 
I'm OK with files appearing in my run directory, but not accumulating them endlessly without my notice.

To be specific, I don't know what is responsible for `.workers.block-0.17158*` files but I'd like them to be visible.

**Describe the solution you'd like**
No hidden files.

**Describe alternatives you've considered**
Adding a "clean up Parsl's logging files" CLI tool

**Additional context**
Is anyone else concerned?

**Comment by benclifford** [comment]
I don't recognise that log file at all... Can you post what is in it and a full example path?

**Comment by WardLT** [comment]
The files are located in the root directory, and named like

```
.workers.block-0.1715894085.9649055.nodes
```

I could be blaming the wrong code, as I couldn't easily find where it was coming from in Parsl.

**Comment by benclifford** [comment]
@WardLT whats inside?

**Comment by benclifford** [comment]
that block-0.171... string is block and submit timestamp that appears in parsl a few times for job submissions. it's passed onto the batch system too as a job name, and so possibly is then used by the batch system too... what batch system are you using that you see this under?

**Comment by benclifford** [comment]
MpiExecLaunch does something with jobname and a .nodes file - see here: https://github.com/Parsl/parsl/blob/b2147140e415fa3bd0eb8118bfdc0e0fe53ccdad/parsl/launchers/launchers.py#L223

However I don't see that it would put `.workers.` on the front so this might not be the place this is coming from.

My other suspicion is that it is a PBS nodefile - what value is in `$PBS_NODEFILE` inside your batch job? Everywhere I looked just refers to the variable, not to what I might expect the filename to look like... so it turns out I have no idea what to expect there at all.

**Comment by WardLT** [comment]
Here's the contents of the PBS_NODEFILE variable

```
(base) lward@x3006c0s19b1n0:~/ExaMol/colmena/demo_apps/task-limits> echo $PBS_NODEFILE 
/var/spool/pbs/aux/1940985.polaris-pbs-01.hsn.cm.polaris.alcf.anl.gov
```

**Comment by benclifford** [comment]
https://github.com/Parsl/parsl/blob/b2147140e415fa3bd0eb8118bfdc0e0fe53ccdad/parsl/providers/pbspro/template.py#L14

which is populated by a job name value generated here https://github.com/Parsl/parsl/blob/b2147140e415fa3bd0eb8118bfdc0e0fe53ccdad/parsl/providers/pbspro/pbspro.py#L152

which includes a timestamp and the underlying job name generated here:

https://github.com/Parsl/parsl/blob/b2147140e415fa3bd0eb8118bfdc0e0fe53ccdad/parsl/executors/status_handling.py#L213

so I think if you `echo` the host file name and job name inside that MPI executor, it will not be the name we are looking for... but probably worth checking to be sure.

**Comment by benclifford** [comment]
(I see where the string `workers` is coming from now - in your executor definition - so workers.block-id.timestamp which is part of the job substring is definitely present here - not sure if we're perhaps just losing the parsl off the front somehow?)

**Comment by WardLT** [comment]
Yea, that's seems right. I'm digging through to see how `label` gets into `job_name` parameter passed to `.submit` of `LocalProvider`.

**Comment by benclifford** [comment]
(ignore the links above about PBSProvider templates - you aren't using that...)

**Comment by benclifford** [comment]
(instead JOBNAME is set in LocalProvider.submit)

**Comment by WardLT** [comment]
Ah, I see it. Where is `parsl.` going!?

**Comment by WardLT** [comment]
Ah ha! Check out the `.sh` file it writes. There's a `$` that is resulting in `$parsl` to be treated as an environment variable

```bash
module load miniconda-3
conda activate /lus/theta-fs0/projects/CSC249ADCD08/edw/env

export JOBNAME=$parsl.workers.block-0.1715928813.7517216
```

**Comment by benclifford** [comment]
aha!

**Comment by WardLT** [comment]
I'm making a PR to remove the `$` from all the `export JOBNAME=$jobname` that are throughout parsl

**Comment by WardLT** [comment]
Hold up, all the other uses of $jobname are correct. It's only me 🤦🏼
