### ISSUE TITLE
[proposal] remove PARSL_TRACKING environment variable

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3456]
**Is your feature request related to a problem? Please describe.**

Currently Parsl takes usage tracking configuration from both `Config` (like other configuration) and from the `$PARSL_TRACKING` environment variable.

The interactions between these two parameters, as well as two conflicting defaults (one in `Config` and one in `usage.py`), are quite subtle and hard to understand intuitively and in the code.

PR #3400 makes that configuration more complicated: instead of a `bool`, the usage tracking level becomes an `int` (of restricted range). In reviewing that PR, along with @khk-globus, it's become pretty apparent that fusing two configurations and defaults together is even more complex in this situation.

Other configuration options in Parsl do not have this "specify multiple configuration values, fuse them together" behaviour: configuration comes from the `Config` object (and objects contained within that class).

**Describe the solution you'd like**

I would like to simplify this piece of Parsl by removing `$PARSL_TRACKING`: this removes a bunch of complexity both for user understanding of what usage level they have actually configured, and for programmers trying to understand these code paths.

**Describe alternatives you've considered**
A more generalised fuseable configuration mechanism that can fuse *any* configuration options, not only usage tracking level.

**Additional context**
This is part of a funded deliverable for usage tracking coordinated by @kylechard and @yadudoc, which @NishchayKarle is working on right now.

**Comment by kylechard** [comment]
Makes sense to put it all in the configuration.
