### ISSUE TITLE
Raise an error when a non-MPI-mode HTEX is passed a resource specification

### ISSUE THREAD

**Issue by chris-janidlo** [Parsl/parsl#3519]
**Is your feature request related to a problem? Please describe.**
Globus Compute would like to warn users when they try to do MPI stuff on non-MPI Compute endpoints. Currently the only place that would raise an error is when workers try to access `PARSL_MPI_PREFIX`, and it would be nice to catch that even earlier.

**Describe the solution you'd like**
Add a check to `validate_resource_spec` which raises an error if `is_mpi_enabled` is false and any resource spec is passed in.

**Describe alternatives you've considered**
Compute could check this at the engine level, before submitting to the HTEX

**Additional context**
https://github.com/Parsl/parsl/issues/3498 is asking for almost the opposite, but it sounds like @benclifford is on the side of more restrictiveness here

**Comment by benclifford** [comment]
This is implemented in #3582
