### ISSUE TITLE
Should app caching compute the hash every time an app is called?

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#357]
We currently hash the function source code in the app factory, to avoid having to compute the hash every time an app is called. This might lead to unexpected behavior, especially when mixed with checkpointing. I think it would be useful to have a look at what the cost of hashing is for a variety of apps/running conditions-- if the cost is low enough, it might make sense to hash per-call.

**Comment by yadudoc** [comment]
I believe that we compute the hash of the function body at define time.
