### ISSUE TITLE
Error when resolving hostname for IPv6

### ISSUE THREAD

**Issue by svandenhaute** [Parsl/parsl#3570]
**Describe the bug**
```python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.node()
'ptr-fr6qae86egjn2e5y6si.18120a2.ip6.access.telenet.be'
>>> import socket
>>> socket.gethostbyname(platform.node())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -5] No address associated with hostname
```

This strange error occurs also within Parsl in `address_by_hostname` when starting HTEX ... I've never encountered this before?
Perhaps [this SE](https://stackoverflow.com/questions/15373288/python-resolve-a-host-name-with-ipv6-address) is relevant?

**To Reproduce**
see above

**Environment**
Fedora 40, Python 3.10
Parsl: latest version

**Distributed Environment**
local machine

**Comment by benclifford** [comment]
for whoever reads this later, from my own machines:

```
$ host ptr-fr6qae86egjn2e5y6si.18120a2.ip6.access.telenet.be
ptr-fr6qae86egjn2e5y6si.18120a2.ip6.access.telenet.be has IPv6 address 2a02:1812:d15:9c00:bbb2:400a:8cf6:53e2 

```

so an `AAAA` DNS record but no `A` record - which means the hostname exists but does not have the record being looked for.

Contrast with a non-existent hostname:

```
>>> import socket
>>> socket.gethostbyname("ptr-fr6qae86egjn2e5y6si.18120a2.ip6.access.telenet.be")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -5] No address associated with hostname
>>> socket.gethostbyname("fhsfhshshdfshdsfffd.lol.hawaga.org.uk")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by benclifford** [comment]
I think after working with sander on this in slack, this turned out to be something like his laptop had an ipv6 only hostname but had lost that IP address. Having a hostname that does not resolve right was then upseetting some Work Queue code which expects the local hostname to resolve to the local computer.
