### ISSUE TITLE
CI testing of SLURM in a container environment

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#3579]
See PR #3159 which runs Parsl tests in flux environment and (unmerged prototype) PR #3482 which does similar for kubernetes.

A couple of different groups have slurm-in-container for their own tests.

So I think the pieces are broadly there.

cc @kylechard who most recently mentioned this to me

**Comment by benclifford** [comment]
also cc @tylern4 who I have had some positive private emails with about this topic

**Comment by tylern4** [comment]
I've put some work into getting slurm working in a [single container](https://github.com/tylern4/slurm-docker-cluster/tree/single-container) and in a [docker compose](https://github.com/tylern4/slurm-docker-cluster/tree/nersc-minislurm) setup which should help with testing. I've got a [start](https://github.com/tylern4/parsl/tree/slurm-tests) and have the regular tests running but still need to work on the local slurm config to get tests running in the docker slurm instance.

**Comment by benclifford** [comment]
@tylern4 if you want to try that out in Parsl CI, you can make a draft PR to make it happen.
