### ISSUE TITLE
AWS provider tries to terminate empty list of instance IDs, and always logs instances as "pending"

### ISSUE THREAD

**Issue by fritzreece** [Parsl/parsl#362]
After completing tasks, Parsl passes on empty list of instances to terminate to boto3, which raises an API error and terminates the program before it is complete. Further, even when the EC2 console and the AWS CLI show instance status as "running," and even when Parsl logs that tasks have been completed on instances, Parsl logs instance status as "pending".

**Comment by yadudoc** [comment]
@fritzreece Hi Fritz, thanks a bunch for reporting this. I'm able to reproduce this bug, and have a fix in testing now. I'll have these changes in dev branches for now since these are being tested for our next major release (v0.6.0). I'll post more information once I have fixes out.

**Comment by yadudoc** [comment]
This is fixed.
