### ISSUE TITLE
Run Parsl in Headless mode in MareNostrum5

### ISSUE THREAD

**Issue by manuel-g-castro** [Parsl/parsl#3623]
**Describe the bug**

All tasks are assigned to the same node. 

**To Reproduce**

1. Install via conda Parsl 2024.9.9 with Python 3.12.5 on MareNostrum 5.
2. Login to MareNostrum 5 and request a 2 node allocation with `salloc`.
3. Run  the [NERSC's script for Headless execution on node 0](https://docs.nersc.gov/jobs/workflow/parsl/#example-headless-workflow-launched-from-node-0) without the `max_workers=1` option.
4. Wait for execution.
5. Check output with all tasks reporting on the master node.

**Expected behavior**

That some tasks are assigned to the other node.

**Environment**

 - OS: Red Hat Enterprise Linux 9.2 (Plow)
 - Python version: 3.12.5
 - Parsl version: 2024.9.9

**Distributed Environment**

- Where are you running the Parsl script from? 
From the master node. 
- Where do you need the workers to run ? 
At the master node and the rest of nodes in the allocation.

**Stdout**

```bash
[<AppFuture at 0x7f34570ce3c0 state=pending>, <AppFuture at 0x7f34583c2210 state=pending>, <AppFuture at 0x7f345723daf0 state=pending>, <AppFuture at 0x7f34570ce420 state=pending>]
Got result:  uname_result(system='Linux', node='gs06r3b58', release='5.14.0-284.30.1.el9_2.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023', machine='x86_64')
Got result:  uname_result(system='Linux', node='gs06r3b58', release='5.14.0-284.30.1.el9_2.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023', machine='x86_64')
Got result:  uname_result(system='Linux', node='gs06r3b58', release='5.14.0-284.30.1.el9_2.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023', machine='x86_64')
Got result:  uname_result(system='Linux', node='gs06r3b58', release='5.14.0-284.30.1.el9_2.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023', machine='x86_64')
```

**Comment by benclifford** [comment]
If you have lots of workers, and a small number of short running tasks, there's no guarantee that tasks will run on both nodes. That is usually the problem (with expectations about the submitted workload, not problem with parsl) when I see this behaviour in tests.

Make sure the tasks are long running (several seconds) and that you submitted enough to saturate every worker throughout the system (eg task count = cores per node * number of nodes * arbitrary factor 3)

**Comment by manuel-g-castro** [comment]
Oh, I see! Thank you, @benclifford.
