### ISSUE TITLE
Clarify documentation on app input resolution

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#367]
[Here](http://parsl.readthedocs.io/en/latest/userguide/apps.html#special-keywords-arguments) we say:
> inputs : (list) This keyword argument allows you to pass a list of input Futures, and thus wait on the results of these futures to be resolved before execution.

We should clarify this to explain that `inputs` can be used in case you want to add an arbitrary number of dependencies at call time. It is implied in our documentation that ONLY futures in `inputs` will be resolved, but really, any argument or keyword argument that is a future will be resolved.

**Comment by annawoodard** [comment]
Users that do not know non-special keyword args will also be resolved will need to do their own unpacking, which is less convenient:
```
@python_app
foo(inputs=[first, second, third]):
    first, second, third = inputs
    bar(first)
    bar(second)
    bar(third)
```
vs
```
@python_app
foo(first, second, third):
    bar(first)
    bar(second)
    bar(third)
```

**Comment by yadudoc** [comment]
6a7d4a84c5b893a4c148126bd1ae26e448d4aa4b from @kylechard fixes this.
