### ISSUE TITLE
SlurmProvider cannot find jobs submitted with "#SBATCH --clusters=some_cluster"

### ISSUE THREAD

**Issue by pdobbelaere** [Parsl/parsl#3675]
**Describe the bug**

Our local HPC ([HPC-UGent Tier-2](https://docs.vscentrum.be/gent/tier2_hardware.html)) groups its nodes in Slurm clusters rather than partitions. Luckily, it is possible to submit jobs from any cluster (e.g., the default login one) to any other cluster using the `#SBATCH --clusters=other_cluster` option. However, this leads to Parsl not recognising submitted blocks and endlessly requesting new resources.

**What I think is happening**
_Bear in mind that my experience with Parsl internals is lackluster at best. The archive attached below contains full runinfo dirs._

1. Job submission works fine, blocks are requested from the cluster(s) specified in `#SBATCH --clusters=..`

2. In the [SlurmProvider._status()](https://github.com/Parsl/parsl/blob/6dd5845baff745ae012b6c681926e3ca20278033/parsl/providers/slurm/slurm.py#L190C1-L190C23) call, it queries the system using `sacct -X --noheader --format=jobid,state%20 --job '{0}'` (by default). This only returns jobs/jobsteps running on the cluster where the main Parsl process lives.

3. As a result, Parsl does not find the submitted jobs and periodically requests scaling out indefinitely (until something triggers shutdown).

In the Parsl log, we find entries like:
```
parsl.providers.slurm.slurm:207 _status DEBUG: Executing sacct -X --noheader --format=jobid,state%20 --job '29835197'
parsl.providers.slurm.slurm:209 _status DEBUG: sacct/squeue returned  
parsl.providers.slurm.slurm:238 _status DEBUG: Updating missing job 29835197 to completed status
```
and
```
parsl.jobs.strategy:217 _general_strategy DEBUG: Executor HighThroughputExecutor has 1 active tasks, 0/0 running/pending blocks, and 1 connected workers
parsl.jobs.strategy:275 _general_strategy DEBUG: Strategy case 2b: active_blocks 0 < max_blocks 1 so scaling out
parsl.jobs.strategy:279 _general_strategy DEBUG: Requesting 1 more blocks
```

Executor-side, things seem to work as expected: a task is only passed to a single worker. Excess job allocations initialise and simply idle.

**A silly patch**

I could fix the issue by simply overwriting `SlurmProvider._cmd = "sacct -X -L --noheader --format=jobid,state%20 --job '{0}'"` (see [--allclusters](https://slurm.schedmd.com/sacct.html#OPT_allclusters)). However, I have no idea of the potential side effects this might cause elsewhere. Also, it is slightly cumbersome to adapt provider behaviour manually.

[test_cases.zip](https://github.com/user-attachments/files/17622999/test_cases.zip)

**Comment by benclifford** [comment]
tagging @tylern4 who has thought about the slurm provider the most...

Maybe its fine to always ask slurm for `--allclusters` ?

**Comment by tylern4** [comment]
I think there are two options here that make sense. 

1) Update the `sacct` call to include `--allclusters` and determine how to get all the clusters if using the `squeue` command. I don't think by default `squeue` will return all the jobs in all the clusters but that might be something @pdobbelaere could help confirm. Could you run `squeue` and see if it returns jobs form all the clusters or just the main cluster?

2) Add a cluster option to the `SlurmProvider`, similar to the `qos`, `partition`, `constraint` option other HPC centers use to separate jobs. Then in both the `squeue`/`sacct` call we can add `--clusters=clusters` and add a Slurm directive to the batch script `#SBATCH --clusters=clusters` so the user doesn't have to add anything extra to `scheduler_options`.

**Comment by benclifford** [comment]
I guess I feel like option 2 is the more consistent one there

**Comment by benclifford** [comment]
@pdobbelaere can you try out https://github.com/Parsl/parsl/pull/3694 to check it solves your problem

**Comment by pdobbelaere** [comment]
Works like a charm. Unfortunately, cancelling jobs presents the same issue: `scancel` also accepts a `--clusters` argument, and silently ignores when it does not find the job.

The Parsl log reports
```
parsl.channels.local.local:39 execute_wait DEBUG: Creating process with command 'scancel 29941077'
parsl.channels.local.local:47 execute_wait DEBUG: Created process with pid 1093005. Performing communicate
parsl.channels.local.local:50 execute_wait DEBUG: Process 1093005 returned 0
parsl.channels.local.local:56 execute_wait DEBUG: Execution of command in process 1093005 completed normally
parsl.executors.status_handling:350 scale_in_facade DEBUG: Marking block 0 as SCALED_IN
```
without actually cancelling the job allocation. Parsl assumes that `retcode == 0` means the job is cancelled, which is not true in this case. Scale in / shutdown does not work.

Manually, `scancel` behaves like
```
[from the doduo cluster]

>squeue --clusters=shinx
CLUSTER: shinx
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          29941142     shinx test_sca vsc43633 PD       0:00      1 (Priority)

>scancel 29941142
>scancel -v 29941142
scancel: Terminating job 29941142
scancel: error: Kill job error on job id 29941142: Invalid job id specified
>scancel -v --clusters=shinx 29941142
scancel: Terminating job 29941142
```
but it does not produce any output unless `--verbose`. 

I would guess that adding `--clusters=self.clusters` in the SlurmProvider [cancel function](https://github.com/Parsl/parsl/blob/92ab47fa45c254d400af42ae1336d14208649996/parsl/providers/slurm/slurm.py#L347C1-L347C87)  fixes the problem.

**Comment by tylern4** [comment]
@pdobbelaere Thanks for catching that! I added in code to also give `scancel` the clusters option. Could you pull the change and try again?
