### ISSUE TITLE
Files with explicit file:// URL scheme do not resolve as I expected on the executor side

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#383]
If I write `File('a.txt')`, then on the execution side, `inputs[0]` resolves to `a.txt`, a valid filename.

If I write `File('file:///etc/passwd'), then on the execution side, `inputs[0]` resolves to `file:///etc/passwd` which is not a valid filename.

Example code below.
```
#!/usr/bin/env python3

import parsl
from parsl import File
from parsl import DataFlowKernel
from parsl import DataFlowKernelLoader
from parsl.config import *
from parsl.app.app import bash_app

parsl.set_stream_logger()

c = Config(executors=[ThreadPoolExecutor()])

dfk = DataFlowKernel(config = c)

# workaround, issue #381
DataFlowKernelLoader._dfk = dfk

@bash_app(data_flow_kernel = dfk)
def foo(inputs=[]):
  return ("ls ; echo X{}X ; [ -f {} ] ".format(inputs[0], inputs[0]))

myfile = 'file:///etc/passwd'

future = foo(inputs=[myfile])

print("RESULT: {}".format(future.result()))
```

**Comment by yadudoc** [comment]
Confirmed. This is a bug.

**Comment by benclifford** [comment]
The test case has become irrelevant with the ongoing clearer distinction between strings and `File` in recent months.

The reported bug text is slightly different from the test case as it talks about using `File` rather than passing in strings - that case now works.
