### ISSUE TITLE
parsl installed from pip tries to determine its version using git

### ISSUE THREAD

**Issue by Xarthisius** [Parsl/parsl#388]
Every time I run parsl I get:

```
kacperk@dxl1: /dpool/kacperk/arxiv $ python scraper_parsl.py
fatal: Not a git repository: '/home/kacperk/.local/lib/python3.6/site-packages/.git'
```

and in logs:

```
2018-07-15 12:54:06 parsl.utils:24 [ERROR]  Unable to determine code state
Traceback (most recent call last):
  File "/home/kacperk/.local/lib/python3.6/site-packages/parsl/utils.py", line 19, in get_version
    head = subprocess.check_output(cmd, env=env).strip().decode('utf-8')
  File "/home/kacperk/miniconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/kacperk/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
```

**Comment by yadudoc** [comment]
@Xarthisius Thanks for reporting this bug. We've seen this error before (https://github.com/Parsl/parsl/issues/326) and have a fix out which suppresses the error. So the expected current behavior is that parsl will only log the git information if it is installed from a git repository, and if there's an error it is suppressed. Can you confirm that you are seeing an issue on your end with latest master ?

**Comment by Xarthisius** [comment]
Ah! I haven't checked the master, I'm running it from pip package.

**Comment by yadudoc** [comment]
We have a ton of changes going into 0.6.0-a0, but you could try that as well. If you would try the the alpha, I'd recommend taking a quick look at the changelog (https://github.com/Parsl/parsl/blob/doc_updates_0.6.0/docs/devguide/changelog.rst)
