### ISSUE TITLE
Globus SSH

### ISSUE THREAD

**Issue by lukaszlacinski** [Parsl/parsl#407]
Add support for Globus SSH to SSHChannel.

**Comment by yadudoc** [comment]
GlobusSSH is available in alpha state and available on Pypi. I'm looking into adding support for this as a channel.

**Comment by yadudoc** [comment]
Tagging @JasonAlt

**Comment by benclifford** [comment]
pleases see issue #3515 about removing channels from Parsl

**Comment by benclifford** [comment]
SSH channels were removed in #3677
