### ISSUE TITLE
Disable pushing straight to master

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#420]
I don't think the minor convenience of not opening a PR is worth the possibility of having master broken.

**Comment by benclifford** [comment]
agree

**Comment by yadudoc** [comment]
Agreed. Sorry about the goofup, I've updated the rules to require a PR. Github requires at least 1 approval for this rule-set but this shouldn't be a problem.

**Comment by annawoodard** [comment]
awesome, thanks yadu!
