### ISSUE TITLE
Hard requirement for CMRESHandler

### ISSUE THREAD

**Issue by jmjwozniak** [Parsl/parsl#422]
Is this needed for Parsl?  I get:

$ python3 setup.py install
...
Installed /usb1/sfw/miniconda3/lib/python3.6/site-packages/parsl-0.6.1-py3.6.egg
Processing dependencies for parsl==0.6.1
Searching for CMRESHandler
Reading https://pypi.python.org/simple/CMRESHandler/
No local packages or working download links found for CMRESHandler

**Comment by kylechard** [comment]
This is being used for real-time monitoring. @yadudoc can we make it optional given many people will not be using the monitoring capabilities.

**Comment by yadudoc** [comment]
The CMRESHandler package is optional, and should not be installed by default when installing from pypi. This might not be the behavior when installing from source. @jmjwozniak I do see some odd behavior when trying to install from source with `pip install -e .`

**Comment by jmjwozniak** [comment]
I will try this with pip install.

**Comment by jmjwozniak** [comment]
That worked.

**Comment by ConnorPigg** [comment]
My guess is pip uses setup.py (which lists it as optional) and pypi uses requirements.txt?
