### ISSUE TITLE
'config' link in references doc broken

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#423]
See [here](http://parsl.readthedocs.io/en/stable/reference.html).

Reported by @djf604.

**Comment by yadudoc** [comment]
Is this due to the stubs being broken ? I remember trying to update them, not being able to make the stubs and then giving up.

**Comment by annawoodard** [comment]
I am stumped. When I build it locally, it works.

**Comment by annawoodard** [comment]
Fixed in #429
