### ISSUE TITLE
Checkpoints not working in docs

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#427]
After a fair bit of troubleshooting with @olgoster we've identified two issues with the checkpointing examples in the `parsl-advanced-features.ipynb` notebook in the parsl-tutorial.
1. The config sets `run_dir=/tmp`, which throws off `parsl.utils.get_all_checkpoints()`
     I do not know why the `run_dir` was set, so I'm uneasy with just removing that line.
2. The `checkpoint_mode="dfk_exit"` does not seem to be trigger checkpointing when parsl.clear() is
     called , however setting it to `checkpoint_mode="task_exit"` creates checkpoints which are used
     by the next cell as expected.
      
We should resolve this quickly!

**Comment by benclifford** [comment]
In the current codebase, parsl.clear() only releases the reference to the `load`ed DFK. It doesn't take any  action to shut down that DFK. Final checkpointing happens in `cleanup`, and that looks like it is only called at unix process exit or if you call it explicitly - many of the test cases call it explicitly.
