### ISSUE TITLE
Executor `label` should be optional if the user doesn't need to refer to executors.

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#439]
If a user does not care to refer to executors (perhaps because they are only using one), then the `label` constructor field should be optional.

If it is desirable to have a label for internal purposes, an uglier label can be autogenerated.

**Comment by yadudoc** [comment]
We already set the label by default to `HighThroughputExecutor`, `threads` or `ipp`. Do we just want to add a random string to end of the default to ensure that multiple executors have unique names ?

**Comment by annawoodard** [comment]
> We already set the label by default to HighThroughputExecutor, threads or ipp. Do we just want to add a random string to end of the default to ensure that multiple executors have unique names ?

I would prefer not to do that to all labels. Maybe we could do it only in the case of dupes? Currently we raise an error on dupes, which I think is sufficient.

I favor closing this issue without fixing it, but I might be missing something from @benclifford.

**Comment by benclifford** [comment]
behaviour as @annawoodard describes is fine.
