### ISSUE TITLE
`States.running` is misleading

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#453]
We use change a task's status to `States.running` as soon as it is submitted. I think that is confusing, because in reality the task might be stuck in the queue and not actually running.

**Comment by benclifford** [comment]
At the moment, a task goes to `States.launched` when a task is submitted to an executor. The DFK doesn't see any further information about the progress of task execution inside the executor, but monitoring records a subsequent state change to `States.running` when the body of the task actually starts running.
