### ISSUE TITLE
All run-related working files should go in the rundir unless otherwise configured

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#457]
At the moment, run-related working files appear in various places, including in the hidden directories .scripts and .ipp_controller.

These should all go in the relevant rundir, when that directory is available.

At present, I'm finding it confusing to find relevant files: both because I have to remember there are several places to look, and because many of the automatically named files do not correlate easily with parsl runs that happen close in time/simultaneously.

**Comment by annawoodard** [comment]
Agreed!

Related to #442.

**Comment by daheise** [comment]
If it's useful, here is an example of a `Config` that gets (almost) everything under a working directory, `wd`. The relevant overrides are called out. The folder `.ipython` remains in `$HOME` and an empty directory `$HOME/parsl_scripts` is still created. 

The code below uses local modifications to work around an issue I reported [here](https://github.com/Parsl/libsubmit/issues/74) and a launcher I have submitted a PR for [here](https://github.com/Parsl/libsubmit/pull/73).


```
blocks = 2
nodes = 2
ppn = 32

wd = os.getenv("HOME") + '/hello_parsl/'
os.makedirs(wd, exist_ok = True)

ipp_config = Config(
    run_dir = wd, # Override 1
    retries = 0,
    executors = [
        IPyParallelExecutor(
            label="IPPHello",
            engine_dir = wd, #Override 2
            engine_file = wd + '/ipcontroller-engine.json', #Override 3
            provider = TorqueProvider(
                launcher = MpiExecLauncher(),
                init_blocks = blocks,
                max_blocks = blocks,
                min_blocks = 0,
                nodes_per_block = nodes,
                tasks_per_node = ppn,
                walltime = "00:02:00",
                script_dir = wd + 'provider_scripts', # Override 4
                channel = SSHChannel(hostname='hostname',
                                     username=os.getenv("USER"),
                                     script_dir = wd + '/channel_scripts'), # Override 5
                overrides = f'''
# Override 6
cd {wd}
                '''
            )
        )
    ]
)

parsl.load(ipp_config)
```
