### ISSUE TITLE
Split up example configs and testing configs

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#459]
It is too confusing for users. The `user_opts` dict adds an unnecessary step. Also, Importing anything from `parsl.tests` gives people an error because they need to set `PARSL_TESTING='True'`. We should just make equivalents which are dedicated examples.

**Comment by yadudoc** [comment]
We should update the configs in "parsl/tests/configs" to not import from the tests folders and be safe for users to run. This set of configs can then be safely used in the docs.
