### ISSUE TITLE
Zombie ipcontroller processes - Process cleanup in case of interruption

### ISSUE THREAD

**Issue by EiffL** [Parsl/parsl#460]
I have done a lot of experimentation with Parsl this week, and I probably sometimes killed manually a parsl job or two, I assume this has interfered with the normal cleanup done by Parsl. But I was made aware  that I was currently showing an increased  python activity at NERSC on cori despite not being running anything at the moment, and upon closer inspection I've discovered a number of zombie `ipcontroller` processes, which I assume are spawned by Parsl, but not necesarily killed when the  main parsl process is interrupted:
```
flanusse 45012  0.0  0.0 2384232 39348 ?       Sl   Aug08   0:00 /global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/bin/python /global/common/software/lsst/common/miniconda/py3-4.3.21-env/envs/parsl-latest/bin/ipcontroller --ipython-dir=/global/u2/f/flanusse/repo/metacal-pipeline/runinfo/060 --ip=* --profile=ipp_slurm
```

If there isn't something like this in place, I guess there could be some kind of watchdog in the  `ippcontroler` process to kill itself if the parent parsl process is not responding, or something like this...

**Comment by yadudoc** [comment]
Hi @EiffL, thanks for reporting this issue. 
I believe what you are seeing is related to the issue here: https://github.com/Parsl/parsl/issues/271.
We'll have a fix out for the next release.

**Comment by EiffL** [comment]
Hi Yadu, ok sorry I looked at open issue but didn't go that far back. I'm closing this  as a duplicate then.
