### ISSUE TITLE
heuristics for public_ip setting - bad user experience when using multi-login-node clusters

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#466]
At present our recommendation is roughly to hardcode a submit machine IP in configurations, for ipp engines to call back to a submitting ipp controller.

This is a terrible user experience when a user regularly logs into one of several login machines, as is pretty common on large clusters/machines, and so has a frequently changing callback address.

There are a bunch of heuristics we could use, none of which is perfect in all situations - in some cases the suitable callback IP isn't even configured on the submitting machine (!)

My recommendation then is to provide one or more helpers that can be used (perhaps by default?) but easily overridden.

heuristics which have worked in some places:

* `/sbin/ip route get 8.8.8.8 | awk '{print $NF;exit}'`    - [midway] - relies on route to 8.8.8.8 going out of an address that is contactable from everywhere we might want to (not always the case, I think, in the case of a headnode and worker nodes with a private network, where worker nodes don't have a route out of the network)

* `hostname`    - this actually returns a hostname not an IP, but it turns out the public_ip field does not need to be an IP. [cori] - needs that returned hostname to resolve sensibly everywhere we might try to resolve it

*  `public_ip=get('https://api.ipify.org').text` - https://stackoverflow.com/questions/2311510/getting-a-machines-external-ip-address-with-python  - address returned might not be address of machine, if going through a NAT. This might be a blessing (eg in some circumstances on EC2) or a curse (if the things we're trying to talk to is this side of the NAT)

**Comment by annawoodard** [comment]
agreed!

**Comment by benclifford** [comment]
#646 should resolve this
