### ISSUE TITLE
Support Butler file objects

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#47]
DESC Requirement

This depends on File object issues #9 and #38 

- [ ]  Explore butler file objects.
- [ ]  How to determine if butler file objects were created.
- [ ]  Identify when a butler output is a collection ?

This is still very vague and needs research into what is needed to support butler data objects in Parsl workflows. With all the unknowns this should be Parsl-0.5.0. Perhaps @annawoodard could help understand this space better.

Butler info: https://github.com/lsst/daf_butler

**Comment by jhcnz** [comment]
@yadudoc and @danielskatz to make some time next Tuesday to discuss Butler issues further

**Comment by danielskatz** [comment]
also see https://confluence.lsstcorp.org/display/DM/Data+Butler+Working+Group

**Comment by yadudoc** [comment]
Another design doc : https://confluence.lsstcorp.org/display/DM/Data+Butler+-+Current+Design
