### ISSUE TITLE
TorqueProvider fails on NSCC 

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#489]
The following patch is required in order to run the `TorqueProvider` on NSCC:
```
[nscc04] ~/libsubmit >git diff
diff --git a/libsubmit/providers/torque/template.py b/libsubmit/providers/torque/template.py
index a00ce7c..056c648 100644
--- a/libsubmit/providers/torque/template.py
+++ b/libsubmit/providers/torque/template.py
@@ -8,7 +8,6 @@ template_string = '''#!/bin/bash
 #PBS -l nodes=${nodes_per_block}:ppn=${tasks_per_node}
 #PBS -o ${submit_script_dir}/${jobname}.submit.stdout
 #PBS -e ${submit_script_dir}/${jobname}.submit.stderr
-#PBS -v WORKER_LOGGING_LEVEL
 ${overrides}

 export JOBNAME="${jobname}"
```

Otherwise, the job fails with `qsub: cannot send environment with the job`. Could we just merge the patch, or should we make this configurable somehow?

**Comment by yadudoc** [comment]
This is odd. Both PBSPro and Torque support -v syntax for setting env variables.
http://docs.adaptivecomputing.com/torque/4-0-2/Content/topics/commands/qsub.htm
Page 35: https://www.pbsworks.com/pdfs/PBSUserGuide13.0.pdf

**Comment by annawoodard** [comment]
Yeah, it might be a specific oddity, but we need to be flexible enough to deal with such things...

**Comment by annawoodard** [comment]
@yadudoc what is this actually used for? I do not see it mentioned anywhere else in parsl or libsubmit. It appears to be a vestige and safe to remove.

**Comment by yadudoc** [comment]
When you specify the worker logging level to the IPP executor, that option has to make it through the submit script down to the point where the ipengines are launched. This is done via an env variable.

Ref: https://github.com/Parsl/parsl/blob/master/parsl/executors/ipp.py#L78

**Comment by annawoodard** [comment]
That option is added to the command line ipengine invocation in the submit script as `"--log-level={}".format(self.engine_debug_level)`. `WORKER_LOGGING_LEVEL` does not appear in the ipyparallel source either. Who is reading that env variable?

[https://github.com/Parsl/parsl/blob/master/parsl/executors/ipp.py#L95](https://github.com/Parsl/parsl/blob/master/parsl/executors/ipp.py#L95)

**Comment by yadudoc** [comment]
Good point. I think we can safely remove this option.

**Comment by annawoodard** [comment]
awesome, thanks!
