### ISSUE TITLE
Support for application profiling

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#5]
Support for application profiling with reporting on:
1. CPU usage
2. Memory usage
3. Disk IO
4. Target resource info (env, uname -a etc..)

Perhaps we could collect this for apps which run longer than N minutes to reduce profiling overhead for trivial tasks ?

**Comment by annawoodard** [comment]
Note from meeting with @djf604 today: this feature would be useful in his workflow. Additional items that would be useful: per-task and per-workflow runtimes.

**Comment by yadudoc** [comment]
This is now supported from the monitoring PR #371
