### ISSUE TITLE
Improve MPIX fault tolerance against node failures

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#529]
I'm not sure exactly what happens if a node fails when using the MPIX. We need to figure it out and make sure the MPIX is tolerant against such failures.

**Comment by yadudoc** [comment]
If MPIX is running in MPI mode, we can't protect against node failure within the MPI program. There are no mechanisms available in MPI (cray-mpich) currently to support fault tolerance as far as I understand. @jmjwozniak is this right ? I am not sure about whether there are implementations that support FT in some way.
