### ISSUE TITLE
Fix event loop error with monitoring enabled

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#532]
```
2018-10-05 12:57:55 parsl.monitoring.db_local:219 [ERROR]  Cannot run the event loop while another loop is running
```

@ConnorPigg thinks this may be due to two tornado event loops running.

**Comment by ConnorPigg** [comment]
I have seen this when an event loop is attempted to be started more than once (such as when a code block is being called more than expected). I've seen it when testing some code in a Jupyter notebook (because the notebook uses a tornado event loop). What was your code/environment when this happened?

**Comment by benclifford** [comment]
This starts one logging server per DataFlowKernel, I think.

What happens when I have multiple DFKs in existence?

**Comment by ConnorPigg** [comment]
From my understanding, multiple dfks should not cause this issue as each dfk launches a unique logging server within a different process. Then there would only be one event loop per process and not cause the issue. I just tried a script that defined and used two different DFKs did not have any errors.

**Comment by ZhuozhaoLi** [comment]
Just a possible solution on this issue:
I saw this error in parsl.log when running the monitoring + ipp. I downgraded the Tornado version to 4.5.3 according to [this post](https://github.com/jupyter/notebook/issues/3397#issuecomment-383452306),  and this error is gone. Not sure if others have the same situation thought.

**Comment by kylechard** [comment]
I think we can fix this without downgrading the version. I played around with Asyncio in a notebook and the latest ipykernel definitely works. So we just need to look at how we're dealing with the event loop.

**Comment by yadudoc** [comment]
@ZhuozhaoLi Can this be closed ?

**Comment by ZhuozhaoLi** [comment]
The monitoring has been refactored. So I believe this is no longer an issue.
