### ISSUE TITLE
cannot pickle traceback

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#546]
The below code does not correctly pass a `ValueError` exception back when used with IPP Instead, IPP catches an error when attempting to pickle the exception, and raises a different error instead.
With `ThreadPoolExecutor`, the exception is passed correctly - the difference being that no pickling of the exception takes place.

This is likely to have related weird behaviour in any remote execution environment, not just IPP - especially if that remote executor does not correctly handle the pickling exception.

Related to this: #110 #198 

```
2018-10-09 12:04:04 parsl.dataflow.dflow:277 [INFO]  Task 0 failed after 0 retry attempts
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/benc/parsl/src/parsl/parsl/dataflow/dflow.py", line 248, in handle_update
    res = future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/benc/parsl/virtualenv/lib/python3.5/site-packages/ipyparallel/client/asyncresult.py", line 226, in _resolve_result
    raise r
ipyparallel.error.RemoteError: TypeError(can't pickle traceback objects)

```

```
#!/usr/bin/env python3

import parsl
from parsl import DataFlowKernel
from parsl.config import *
from parsl.app.app import bash_app
from parsl.app.app import python_app
from parsl.executors.ipp import IPyParallelExecutor
from parsl.providers import LocalProvider

parsl.set_stream_logger()

# config = Config(executors=[ThreadPoolExecutor()])
config = Config(executors=[IPyParallelExecutor()])

dfk = DataFlowKernel(config = config)

print("start")

@python_app(data_flow_kernel = dfk)
def foo():
  raise ValueError("BENC value exception")

f = foo()
f.result()

print("end")
```

**Comment by benclifford** [comment]
This doesn't happen with the MPI executor in mpi_executor_heartbeat - I think the exception handling there is better.

**Comment by yadudoc** [comment]
@benclifford I'm not able to reproduce this on master with `parsl.configs.local_ipp`, `parsl.configs.htex_local` and `parsl.configs.exex_local`. If you don't think this is an issue anymore, let's close.

**Comment by yadudoc** [comment]
We no longer support `IPyParallelExecutor`. This issue is no longer relevant.
