### ISSUE TITLE
AppFailures do not serialise/deserialise properly using ipyparallel.serialize

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#548]
The following code does not work on `master` at time of writing, but does work on `mpi_executor_heartbeat` which has a bodge in it that I implemented without fully understanding what's going on with deserialization (f77f72055c83887049ebd1bbe4666b1980570d80)

These serialize_object/deserialize_object calls are used in the implementation of the MPI executor to return exceptions.

The error in this test case occurs on deserialization:

```
Traceback (most recent call last):
  File "./failure2.py", line 17, in <module>
    (e2, _) = deserialize_object(ser)
  File "/home/benc/parsl/virtualenv/lib/python3.5/site-packages/ipyparallel/serialize/serialize.py", line 145, in deserialize_object
    canned = pickle.loads(pobj)
TypeError: __init__() missing 1 required positional argument: 'exitcode'
```

```
#!/usr/bin/env python3

from parsl.app.errors import AppFailure
from ipyparallel.serialize import serialize_object
from ipyparallel.serialize import deserialize_object

e = AppFailure("BENC: AppFailure Message Text", 33)

print("not yet serialised object:", e)
print(e)

ser = serialize_object(e)

print("serialised object:", ser)
print(ser)

(e2, _) = deserialize_object(ser)

print("deserialised object:", e2)
print(e2)
```

**Comment by benclifford** [comment]
Removing the call to `super.__init__(reason)` appears to fix this (as noted in https://bugs.python.org/msg310951)

**Comment by yadudoc** [comment]
Is this still a problem ?

**Comment by benclifford** [comment]
crossref #785
