### ISSUE TITLE
Re-examine block semantics

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#557]
In the context of the new `HighThroughputExecutor` and `ExtremeScaleExecutor`, the concept of a block and how it maps to workers/nodes/cores/batch jobs is even more confusing than before.

From Yadu:
> For the exex 1 block = 1 mpi_worker_pool
> For the htex 1 block = potentially many nodes, each with 1 process_worker_pool
> so there is some difficulty with all the configs that specify tasks_per_node which should now be handled by the executor rather than the launcher.

We need to think carefully about this and make sure everything is consistent. I vote that we favor consistency/clarity and the new executors over backwards compatibility and addressing limitations of IPP.

**Comment by yadudoc** [comment]
Since HTEX managers are launched on the compute nodes and have access to the resources on node, it can take resource based specification readily. This leads to inconsistencies between config definitions in the case of IPP, HTEX and EXEX. For eg:

For HTEX the following is the preferred config when specifying 4 workers per 16core nodes.:
```
HighThroughputExecutor(cores_per_worker=1, provider=SlurmProvider(nodes_per_block=2, launcher=SrunLauncher())                                          
```
Here we do not want the SrunLauncher to do more launches that 1 per node, because the manager is capable of partitioning resources within the node.

For IPP, since workers have no resource management capability, they need to be launched by the provider and launcher like this, where the core per node information has to be known by the user and used to calculate tasks_per_node:
```
IPyParallelExecutor(..., provider=SlurmProvider(nodes_per_block=2, tasks_per_node=4, launcher=SrunLauncher())                                          
```

With EXEX the same issue applies, information on cores/memory and other resources are not known at launch time and has to be defined by the user. Here ranks_per_node and tasks_per_node convey the same information.
```
ExtremeScaleExecutor(ranks_per_node=4, provider=SlurmProvider(nodes_per_block=2, tasks_per_node=4, launcher=SrunLauncher())                                          
```

**Comment by annawoodard** [comment]
So, putting the default explicitly, that would be
```HighThroughputExecutor(cores_per_worker=4, provider=SlurmProvider(nodes_per_block=2, tasks_per_node=1, launcher=SrunLauncher())```

@benclifford @kylechard any thoughts on this? We discussed Friday and are unhappy with the inconsistency, but weren't able to come up with a way to avoid it.

**Comment by annawoodard** [comment]
I vote to move specification of tasks per node to executors where it is relevant, and have the executors propagate to provider.

**Comment by annawoodard** [comment]
To clarify my proposal: we'd remove the `tasks_per_node` keyword arg to the providers, and have that property set instead by the executor (or alternatively, we could add it as keyword arg to the Provider's `submit` method). IPP would set (left side is setting in the provider, right side is keyword arg specification in the executor) `tasks_per_node=workers_per_node` (yes, I'm introducing a name change, just to keep everyone on their toes), htex would set `tasks_per_node=1`, and exex would set `tasks_per_node=ranks_per_node`. In this way we could completely document the specification of the executor in the executor and the provider in the provider, without having to refer from one to the other (in other words, say in the provider, "tasks_per_node is defined as XXX if you are using YYY executor, and AAA if you are using BBB executor").

In @yadudoc's example above with 4 workers, 16-core nodes:

**current**
```
HighThroughputExecutor(cores_per_worker=4, provider=SlurmProvider(nodes_per_block=2, tasks_per_node=1)                                         
```
```
IPyParallelExecutor(provider=SlurmProvider(nodes_per_block=2, tasks_per_node=4)                                          
```
```
ExtremeScaleExecutor(ranks_per_node=4, provider=SlurmProvider(nodes_per_block=2, tasks_per_node=4))                                          
```

**proposed**
```
HighThroughputExecutor(cores_per_worker=4, provider=SlurmProvider(nodes_per_block=2))                                         
```
```
IPyParallelExecutor(workers_per_node=4, provider=SlurmProvider(nodes_per_block=2)                                          
```
```
ExtremeScaleExecutor(ranks_per_node=4, provider=SlurmProvider(nodes_per_block=2))                                          
```

**Comment by annawoodard** [comment]
To answer @benclifford's suggestion, in the proposal above, one could calculate the number of simultaneous parsl tasks which could run in a single block as:

**htex (cores / node is determined on the node and does not need to be specified by user)**
simultaneous running tasks / block = cores / node / `cores_per_worker` * `nodes_per_block`

**ipp**
simultaneous running tasks / block = `workers_per_node` * `nodes_per_block`

**exex**
simultaneous running tasks / block = `ranks_per_node` * `nodes_per_block`

**Comment by annawoodard** [comment]
After discussion yesterday, I (think?) we all agreed on the version of this proposal where the `tasks_per_node` is specified as a keyword arg to `Provider.submit`, such that each executor can set it appropriately according to `workers_per_node` (IPP), 1 (htex), `ranks_per_node` (exex).
