### ISSUE TITLE
`time_returned` should be measured when the`handle_update` method is exited

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#571]
In particular, we want to be able to measure `time_returned - time_submitted` as the total time it takes a task to go round trip (user submits -> user receives task output).

**Comment by benclifford** [comment]
Note that handle_update has split into two: handle_exec_update and handle_app_update, as of PR #608 

At the point at which the output value is available to a workflow user through an AppFuture, handle_app_update is called, so that is probably the place to record the end time.

**Comment by ZhuozhaoLi** [comment]
This is done with monitoring
