### ISSUE TITLE
Run directories

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#58]
Workflows in production are often run in the same directory multiple times. Various log files, checkpoint files, submit scripts, config options etc are often produced and ideally stored in a manner that would allow the user to easily identify files associated with a single workflow run. Having a run specific directory would also help #39 and #48. 

I propose that we have run directory that is named runNNN by default and placed in the current directory. Users would have the option to specify a different run directory path, if they so choose.

**Comment by danielskatz** [comment]
The idea seems good, but some details are not clear to me:

1. What is NNN?
2. Is it always three characters?

**Comment by yadudoc** [comment]
1. I should have specified this as run[0-9][0-9][0-9] (Run followed by three digits).
2. In swift we had 3 digits. We need to guess here in terms of how many instances we expect users to run. 

Specifically the logic here would be that the first run would have the dir run000 and every subsequent run would increment the run number by 1. The only reason to use runNNN is that it looks nicer with the number padded with 0's when ls'ing the directories.

**Comment by danielskatz** [comment]
what happens if there are more than 1000 runs?

**Comment by yadudoc** [comment]
run000 -> run001 - > ... run999 -> run1000.
It's padded to 3 positions.

**Comment by danielskatz** [comment]
sounds reasonable

**Comment by annawoodard** [comment]
From Slack, @danielskatz suggested a top directory with the numbered ones underneath, and now we're all in agreement on:

```
runinfo/000
runinfo/001
...
```

**Comment by yadudoc** [comment]
Great! I'll add this to the multisite branch that needs this functionality.

**Comment by yadudoc** [comment]
This functionality has now been merged to master from branch:multisite.
