### ISSUE TITLE
publish as conda package

### ISSUE THREAD

**Issue by prjemian** [Parsl/parsl#60]
This would be useful to install as a [conda](https://conda.io/docs/) package.  Can you add that to your roadmap?  Suggest you create a channel on anaconda.org to publish the conda package.

**Comment by yadudoc** [comment]
This makes sense. I will add publishing on conda to the regular release process.

For now, if you are using a conda environment, you could do parsl installs in an activated conda environment with : 

> python3 -m pip install parsl

This is only a temporary stop gap, until we have a release process for conda

**Comment by yadudoc** [comment]
From a preliminary look at Anaconda and conda-forge, we ideally want to get parsl into the default channels. That would avoid having to add a channel or specify a channel at install time. Pushing the release to PyPi followed by pushing to conda-forge seems like the way to go. https://github.com/conda-forge/staged-recipes

**Comment by yadudoc** [comment]
Deferring this.
