### ISSUE TITLE
Switch database logging to use SQLAlchemy's ORM model

### ISSUE THREAD

**Issue by ConnorPigg** [Parsl/parsl#601]
The switch has the potential to improve code clarity by working with objects instead of SQL execute statements. The switch also may be able to leverage different parts of SQLAlchemy's ORM such as unit of work, sessions, etc. for performance improvements to the current logging server. This performance boost may be just as attainable by optimizing/reworking the current execute statements.

**Comment by ZhuozhaoLi** [comment]
This is done with the new monitoring.
