### ISSUE TITLE
Implement a gather() method to gather all results of futures concurrently

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#603]
We should implement a gather() method to gather many results concurrently. For example, 
```
>>> # results = [future.result() for future in futures]   # this gather on each future sequentially
>>> results = client.gather(futures)  # this can be faster
```

Link to code of gather() API for dask.distributed:
https://github.com/dask/distributed/blob/db903bc333ab8c1aec147896d7c5489863026243/distributed/client.py#L1586

**Comment by benclifford** [comment]
I'm unclear about what is faster with that client.gather() implementation: that `gather` code looks like it iterates over a list to get results from each future and construct the output list.
