### ISSUE TITLE
Make sure we get the right version of zmq

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#605]
Looks like htex breaks with zmq==17.0.0 and works with zmq==17.1.2

**Comment by yadudoc** [comment]
With pyzmq==17.0.0, the executor and the interchange communicate over a DEALER-DEALER sockets. If the interchange is slow to move messages off the queue, the queue quickly reaches an exceptional state. Once that happens no message go in or out. The correct behavior here should be that the DEALER socket blocks on the executor side when the queue is full. Updating pyzmq to 17.1.2 fixes this issue.
