### ISSUE TITLE
LowLatency Executor

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#609]
Low latency is a growing concern as Parsl is used as a framework for sub-second task execution as is common in model serving (DLHub), driving interactive compute from Jupyter notebooks and applications with real-time requirements. Our new remote executors `HighThroughput` and `ExtremeScale` are designed with a focus on high throughput to deliver task execution rates of ~1000-2500 Tasks/second. IPP on the other hand delivers lower throughput but offers much lower per task latency (~20ms). Ideally we want to be able to bound latency down to round-trip-time+3ms.

Here are some requirements for this new executor
1. low latency (rtt+3ms)
2. support for workers joining and leaving the pool
3. tolerate failures, (we may not need retries, but we at least need an fail report)

Once we have this executor, we can work on automating task profiling to create performance models, and using these models in conjunction with user defined latency objectives for batching. This task will require some engineering effort upfront to implement some communication code with zeromq, but once that is done we can switch to research mode.

**Comment by benclifford** [comment]
is the intention that throughput is allowed to be lower in this?

**Comment by yadudoc** [comment]
Correct.

**Comment by yadudoc** [comment]
This work is complete, thanks to @rohankumar42.
