### ISSUE TITLE
Move parent-related state handling out of AppFuture into handle_update

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#621]
At present, some of the task state machine lives in handle_update in the DataFlowKernel; and some lives in the parent callback of AppFuture.

It should be possible to move that AppFuture parent handling code into the DataFlowKernel state machine; this would get state handling code more concentrated into one place, and maybe remove the need for the AppFuture to know anything about a parent exec future.

This should not otherwise affect functionality (modulo exciting race conditions exposed by this change).

This came up after some discussion between myself and @yadudoc looking at reasoning about the behaviour of the DFK and related parts.

**Comment by kylechard** [comment]
Is this now done? @benclifford

**Comment by benclifford** [comment]
This is PR #722 which I am chopping into chunks and submitting as several more easily reviewable PRs.

**Comment by benclifford** [comment]
This has been completed. Closing.
