### ISSUE TITLE
potential race condition in bash_app keyword handling

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#627]
The bash_app app class (but not the python one) mutates its global `kwargs` parameter on invocation, and then uses this mutated `kwargs` during invocation.

This might be a race condition, when multiple @bash_apps are being invoked at once (which might happen as we ramp up the load on parsl)

It looks like it might be unnecessary to update the global state, and that instead a local variable could be used - but be aware of things like #349

**Comment by benclifford** [comment]
duplicated by #1058

**Comment by yadudoc** [comment]
I believe #1413 fixes this one as well.
