### ISSUE TITLE
Ctrl-C should cause DFK to cleanup fast

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#641]
Pressing ctrl-C (or sending termination signals in other ways) should invoke much more aggressive termination behaviour than exists now.

* Since #610, the DFK will wait for tasks to complete at shutdown, even if the shutdown is caused by an at exit handler happening because of ctrl-C. Ctrl-C should cause all tasks to fail immediately, or cause the DFK to not wait for tasks to finish.

The implementation of this may be related to making non-lazy errors work properly: that also needs a mechanism to make unrelated tasks fail hard.

related: #223

**Comment by benclifford** [comment]
#645 contains some code working towards this.

**Comment by yadudoc** [comment]
@benclifford Do we need to wait on #645 to close this ? Didn't #650 fix this ?

**Comment by benclifford** [comment]
#650 should have fixed this, yes. #645 was some other stuff I was playing with that was more complicated and that I have mostly given up on.
