### ISSUE TITLE
Change `public_ip` keyword arg to htex/exex

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#653]
Often we don't want a public ip. We should pick a name that isn't wrong part of the time. As I think @benclifford suggested, maybe 'address'?

**Comment by benclifford** [comment]
Specifically:

*  it doesn't need to be an IP; for example, it can often usefully be a hostname, as returned by `parsl.addresses.address_by_hostname()`

* it doesn't need to be public - it needs to be reachable from everywhere that we're expecting stuff to connect from, which might be a scope more like the internal IP networks of a supercomputer.

**Comment by annawoodard** [comment]
To consider this issue resolved, we should also clarify the docstring to reflect what @benclifford summarized above. We currently say `Set the public ip of the machine on which Parsl is executing.` which isn't quite right.
