### ISSUE TITLE
'connected_workers' does not return connected workers for htex/exex

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#656]
`HighThroughputExecutor.connected_workers` returns [this](https://github.com/Parsl/parsl/blob/master/parsl/executors/high_throughput/interchange.py#L236-L238), which means that the log line [here](https://github.com/Parsl/parsl/blob/master/parsl/dataflow/strategy.py#L193) does not make sense. I think we should rename the `connected_workers` attribute (`queue_status`?) and reserve 'connected_workers' for answering the question, 'based on the connected resources, how many tasks can I expect to run concurrently?' (which is the meaning of `IPyParallelExecutor.connected_workers`).

**Comment by yadudoc** [comment]
We'll update the log line to be clearer and consistent across executors.

**Comment by annawoodard** [comment]
cc @lgray
