### ISSUE TITLE
Fix install on BW

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#668]
Running `python setup.py install` on BW currently fails with `error: can't copy 'parsl/app': doesn't exist or not a regular file`. I need to comment out `include_package_data=True,` in order to install.

**Comment by yadudoc** [comment]
@ZhuozhaoLi mentioned that this may no longer be an issue on BW

**Comment by ZhuozhaoLi** [comment]
Just tested on BW, it worked without any issue.

**Comment by yadudoc** [comment]
Great. I'm closing this then.
