### ISSUE TITLE
installing new version of Parsl

### ISSUE THREAD

**Issue by danielskatz** [Parsl/parsl#68]
I think https://github.com/Parsl/parsl/blob/master/docs/quick/quickstart.rst should include something about how to upgrade your version of parsl using pip.

For example, I currently have 0.3.0-alpha, and just doing
python3 -m pip install parsl
doesn't install the current version.

**Comment by yadudoc** [comment]
Were you able to resolve this ? Usually pip install -U parsl, should do the job.

**Comment by danielskatz** [comment]
Yes, I think you told me this in a chat.  But it would be nice if it was part of the readthedocs info.

I've created https://github.com/Parsl/parsl/pull/77 to do this.
