### ISSUE TITLE
Allow configuration of workers per manager

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#690]
As proposed by @yadudoc, we should have a keyword arg to the exex constructor (say, `workers_per_manager`) that allows the user to configure how many workers are started per manager. Currently only one manager is ever started. This should be pretty straightforward to implement [here](https://github.com/Parsl/parsl/blob/master/parsl/executors/extreme_scale/mpi_worker_pool.py#L492).

**Comment by yadudoc** [comment]
Done. this is called `max_workers`
