### ISSUE TITLE
Difference from signac

### ISSUE THREAD

**Issue by berceanu** [Parsl/parsl#711]
How does `parsl` differ from [signac](https://signac.io/)?

**Comment by kylechard** [comment]
Until now I hadn't seen Signac before, so I can only really comment on what I see on their website. 

It would appear that Signac is designed to manage large data spaces with a "well-defined indexable storage layout for data and metadata." It provides some workflow capabilities as a way of for analyzing data in this model. Unlike Parsl, the focus here appears to be wrapping functions for invocation via the Signac command line and it requires explicit pre/post conditions to manage the linear flow between functions. 

Parsl is focused on implementing and executing dataflow-based workflows. The model here is that Parsl allows Python scripts to be processed into a dataflow graph of dependencies passed between _apps_. These dependencies might be Python objects or files. At runtime Parsl inspects the graph and determines what apps can be executed. It then manages the execution of apps on available resources (e.g., clouds, clusters, supercomputers).  

The best resource for learning about Parsl is via our Binder-hosted tutorials: https://mybinder.org/v2/gh/Parsl/parsl-tutorial/master

**Comment by yadudoc** [comment]
I believe the question is answered.
