### ISSUE TITLE
PEP8 conformance

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#72]
Running flake8 on parsl throws 4582 errors. This is **not** ideal.
This [article](https://www.caktusgroup.com/blog/2015/08/15/making-clean-code-part-your-build-process/) goes over some tools to auto fix code conformance issues.

- [x] Decide exceptions to conformance rules if any (line length, extra spaces ?)
- [x] Add config file with exceptions
- [x] Run auto fix tools and update changes
- [x] Add flake8 conformance as a test to travis, so as to fail a code does not conform to guidelines.

I'm tagging this for 0.4.0, but since the release deadline is very close might defer for a later point release since the code should be functionally identical.

**Comment by annawoodard** [comment]
I have autopep8 hooked into my vimrc so that issues are automatically fixed as I code. We should include instructions for doing so for vim and emacs. I'll add that to #65 TODOs. I can do the vim one.

**Comment by annawoodard** [comment]
(I edited the above comment with an additional link)

**Comment by benhg** [comment]
I have that setup in emacs and can write instructions for it

**Comment by yadudoc** [comment]
Let call this done until we have plans for improvements to make ?

**Comment by annawoodard** [comment]
It looks like flake8 is still complaining about a few things, since the last build is failing?

**Comment by annawoodard** [comment]
Also minor coment [here](https://github.com/Parsl/parsl/blob/f0f592ac56bdef42fac899e041eef66fb2d8ee3c/.flake8#L9): why exclude tests in the flake8 config? For me, the benefits of linting apply there too.

**Comment by yadudoc** [comment]
Hmm.. build looks green for me now (since last 5 hrs)? https://travis-ci.org/Parsl/parsl/builds 
I need to go back and fix the tests. That was not intentional.

**Comment by annawoodard** [comment]
Ah sorry :woman_facepalming: I just saw fdce2e7 and didn't look at the most recent. I agree then, with tests added to the config, this issue is good to go. 👏 👏 👏  🎉 🎉 🎉

**Comment by yadudoc** [comment]
Tests are added, and travis is showing all green. Closing.
