### ISSUE TITLE
htex stdout/stderr buffer fills up and causes a hang

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#738]
In this case as least:

```
python3 parsl/tests/manual_tests/test_worker_count.py -c 200000
```

the test eventually hangs - around 1000 jobs.

Removing `set_stream_logger()` from process_worker_pool.py at least stops thats happening, but that might not be the correct solution.

Instead, it might be better to ensure that whatever launches the process_worker_pool is able to accept arbitrary amounts of stdout/stderr.

This came from a debug session with @yadudoc and @ZhuozhaoLi

**Comment by yadudoc** [comment]
@benclifford  I believe this has been fixed. This was a debug line that got committed. We log to files and we've not had issues with 1M+ tasks.
