### ISSUE TITLE
Conda-forge deployment

### ISSUE THREAD

**Issue by dgasmith** [Parsl/parsl#747]
We find it very useful to have all of our tools available on the community conda channel [`conda-forge`](https://conda-forge.org). It looks like all of your dependancies are already on `conda-forge` besides `globus-sdk` whose dependancies are available. 

Would it be possible to deploy to conda-forge? We are happy to either help or write the recipes to get the project on there. conda-forge deployment basically looks like:
 - Initial recipe writing and identification of maintainers.
 - Conda-forge bots watch either PyPI or GitHub (whichever you decide to pull from) and automatically bump versions when a new release comes out.
 - Generally no other action is needed.

**Comment by yadudoc** [comment]
Tagging @ZhuozhaoLi.
We are going to take a stab at this right after `0.7.2` is released on PyPi.

**Comment by dgasmith** [comment]
Awesome! Let me know if you need a hand.

**Comment by ZhuozhaoLi** [comment]
Hi Daniel @dgasmith, I have submitted a [PR](https://github.com/conda-forge/staged-recipes/pull/8015) to deploy parsl to conda forge. 

I tried to skip win and OSX builds in the recipe as Parsl is mostly for Linux. But it seems the checks still try to build on win and OSX. Could you please take a look? Thanks.

**Comment by dgasmith** [comment]
The proposed skip should work, but Conda-forge maintainers may have preference on exactly how it is done. We usually use the following to pin Py3.6 [or greater](https://github.com/conda-forge/qcengine-feedstock/blob/master/recipe/meta.yaml). This is slightly nicer as it pins the package itself rather than just the build.

I also recommending running *some* tests beyond just imports. The import only imports has lead to many broken packages in production, especially with complex environments like Parsl.

The current PR will probably build everything regardless. Build control is done by regro bots which will render the correct Travis/Appveyor/etc builds to narrow down the build scope.

Thanks for giving this a go!

**Comment by yadudoc** [comment]
Thank you both for your help on this : @dgasmith @ZhuozhaoLi  

I'm now able to install from conda forge with : 
`conda install -c conda-forge parsl`

I think we need to update docs and update tests done by the conda-forge CI. I propose we close this issue and track those separately.

**Comment by ZhuozhaoLi** [comment]
Agreed. I have created a new issue #834 to track that.
