### ISSUE TITLE
Clarify nodes per worker workers per node

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#749]
Our docs are a little confusing here. Executors use “workers_per_node” and providers use “tasks_per_node." 

A user had to look in the code to understand what to use.

**Comment by yadudoc** [comment]
As of Parsl 0.7.1 we've moved `tasks_per_node` option from provider `__init__` to the  `provider.submit()`call. As a result passing `tasks_per_node` to the provider as config time should raise an exception. Our docs have been updated to remove mentions of the `tasks_per_node`, except in the changelog and documentation for the `provider.submit` call
