### ISSUE TITLE
Lookup Worker Information from within Workers

### ISSUE THREAD

**Issue by WardLT** [Parsl/parsl#751]
Being able to determine information about a worker (e.g., its rank) would be a nice new feature. 

My need for this is because I am running on a machine with multiple GPUs per node. I need a way to pin each worker to a specific GPU, and currently do so by a convoluted system that makes HTTP requests back to the host process to get a task ID. Something more elegant (@yadudoc has already suggested another hack involving directories) would be much appreciated. Example code below.

-------------------------

```python 

# Make a server for assigning threads to a GPU
@cherrypy.expose
class GPUManager:
    def __init__(self):
        self.lookup = {}

    def POST(self, hostname='', pid=1):
        if hostname not in self.lookup:
            self.lookup[hostname] = {}
        if pid not in self.lookup[hostname]:
            self.lookup[hostname][pid] = len(self.lookup[hostname]) % gpus_per_node
        return str(self.lookup[hostname][pid])

# Start the server on a random port
conf = {
    '/': {
        'request.dispatch': cherrypy.dispatch.MethodDispatcher()
   }
}
cherrypy.config.update({
    'server.socket_port': 5738,
    'server.socket_host': '0.0.0.0'
})
cherrypy.tree.mount(GPUManager(), '/', conf)
cherrypy.engine.start()
manager_hostname = 'http://{}:{}/'.format(hostname, 5738)

# Make the task
@bash_app
def run_training(name, size, hostname):
    # Load libraries (needed for parsl)
    import requests
    import socket
    import os

    # Get the hostname and pid for this process,
    #   use it to determine the GPU
    pid = os.getpid()
    nodename = socket.gethostname()
    gpu_id = requests.post(hostname, params={'hostname': nodename, 'pid': pid}).text

    # Print the GPU id to disk
    return "python3 train_models.py --num-workers=4 -d cuda:{} --copy /dev/shm {} {} >> train.log".format(gpu_id, name, size)
```

**Comment by yadudoc** [comment]
This is related to issue #107 and probably should be addressed in the context of workers being aware of resources and affinities.

**Comment by WardLT** [comment]
I am seeing a need for this issue again when running Parsl applications that use Tensorflow. As discussed in [a Tensorflow issue](https://github.com/tensorflow/tensorflow/issues/8602), multiple processes that use Tensorflow will attempt to use the same resources (e.g., same GPUs, same CPU cores) leading to resource contention. 

[Solutions to the contention issue](https://github.com/tensorflow/tensorflow/issues/8220) seem to involve pinning processes to certain issues, which involve workers knowing who they are.

**Comment by WardLT** [comment]
Could I have workers recognize who they are by modifying the [worker function in HTEX](https://github.com/Parsl/parsl/blob/b31c18b7346eb9ba2072a801826ad31dd5e4d8d3/parsl/executors/high_throughput/process_worker_pool.py#L446) to set an environment variable that would be visible from the Parsl function?

I would move ahead with this, but I'm concerned about whether this "environment variable" model would work with other methods.

**Comment by benclifford** [comment]
@wardlt It almost definitely won't work with the ThreadPoolExecutor because there is not a per-thread environment to put information in. I don't really see a problem for now with saying that some features are not available in all executors, though - different executors have different characteristics and we don't try to make the execution environment look completely identical across all of them.

**Comment by WardLT** [comment]
Makes sense.

I'm going to attempt to make the change to HTEX to make worker IDs accessible. Besides worker ID (which is kind of a local rank), is there any other worker information you'd like in the short term?

**Comment by yadudoc** [comment]
Fixed.
