### ISSUE TITLE
Two attributes never used in parsl/executors/high_throughput/interchange.py

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#765]
Seems the two attributes below are not used anywhere. https://github.com/Parsl/parsl/blob/6701688f6d9bfe8e5a4d1ef9183f8fec930db5de/parsl/executors/high_throughput/interchange.py#L171 and https://github.com/Parsl/parsl/blob/6701688f6d9bfe8e5a4d1ef9183f8fec930db5de/parsl/executors/high_throughput/interchange.py#L173

**Comment by benclifford** [comment]
I think that is true.

It would be reasonable to submit a PR removing them.
