### ISSUE TITLE
Failing stageout does not cause any failure, and apps complete even with failed stageout

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#778]
AppFutures and DataFutures are marked as finished before output stage-out happens.

DataFutures marked as successfully should probably mean that stage-out has happened successfully.

Possibly AppFutures should not be marked as successfully complete until stage out has happened either.

I've tested this with the below code, running to my own Globus Connect Server installation, to demonstrate this - the code reports that the test has completed successfully, and then: in the case that stageout doesn't work due to permissions, hangs rather than exiting (see #762); or in the case of a successful transfer, performs the transfer after the test has reported successfully.

Stage out jobs are submitted as separate tasks at the point that an app completes. Probably all of the stage out jobs should be joined on, and that join point is when the App and DataFutures report themselves as complete.

If stageout fails, then this is not reported except in debug logs. In particular, the test suite does not detect failing stageouts.

**Comment by yadudoc** [comment]
Just for context, I think the thought process at the time was that, we planned two distinct types of data movement:
1. Wide-area transfers with globus, usually onto a persistent-node.
2. Data transfer between transient nodes (worker-login)

Globus and such transfer modes run from the parsl-client side and can be restarted/retried and data loss is unlikely. Here decoupling AppFutures and DataFutures made some sense.

In the second mode (which we don't support yet), staging in/out is packaged together with the task, and the task completely only when the data has been moved out. We assume data is not yet available until it is moved to client-side.
