### ISSUE TITLE
Simple Hello World script fails due to globus trying to mkdir in read-only space (/home/user/)

### ISSUE THREAD

**Issue by kevtree** [Parsl/parsl#780]
0: Traceback (most recent call last):
0:   File "/mnt/lustre_fs/users/kavotaw/apps/anaconda/anaconda3/envs/parsl_py36/bin/process_worker_pool.py", line 19, in <module>
0:     from parsl.version import VERSION as PARSL_VERSION
0:   File "/mnt/lustre_fs/users/kavotaw/apps/anaconda/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/parsl/__init__.py", line 35, in <module>
0:     from parsl.data_provider.files import File
0:   File "/mnt/lustre_fs/users/kavotaw/apps/anaconda/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/parsl/data_provider/files.py", line 12, in <module>
0:     from parsl.data_provider.data_manager import DataManager
0:   File "/mnt/lustre_fs/users/kavotaw/apps/anaconda/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/parsl/data_provider/data_manager.py", line 8, in <module>
0:     from parsl.data_provider.globus import get_globus
0:   File "/mnt/lustre_fs/users/kavotaw/apps/anaconda/anaconda3/envs/parsl_py36/lib/python3.6/site-packages/parsl/data_provider/globus.py", line 28, in <module>
0:     os.mkdir(token_pa
0: th)
0: OSError: [Errno 30] Read-only file system: '/home/kavotaw/.parsl'
srun: error: compute0: task 0: Exited with exit code 1

**Comment by benclifford** [comment]
This looks like `globus.py` is trying to write to the user home directory at the time it is imported, even if none of the other code from that file is used. As it is always imported, that means that the user home directory always needs to be writeable, even if globus transfers aren't used.

That initialisation code should probably move into an object initialiser or something like that.

**Comment by benclifford** [comment]
This should be fixed by #781 which is merged into master now.
