### ISSUE TITLE
Allow bash-app stdout and stderr to specify alternate open modes

### ISSUE THREAD

**Issue by mjwilde** [Parsl/parsl#795]
bash-apps currently open files specified for the stdout and stderr keywords in append mode.  This causes surprising behavior when the same script is run repeatedly (in particular in demo, learning or debugging modes).

It would be useful to let the script writer specify alternate modes, typically opening in truncate-and-write mode ("w").

This can be done without affecting the current semantics by accepting a 2-element tuple, (filename, mode) as an alternative to the simple string-filename option.

**Comment by yadudoc** [comment]
Fixed by #797
