### ISSUE TITLE
Feature request: dynamically re-partitioning blocks

### ISSUE THREAD

**Issue by joezuntz** [Parsl/parsl#798]
Our LSSTDESC workflows have specific structures that don't currently map very well to the parsl model, and @yadudoc has suggested I put this as a feature request.

In particular, we have pipelines that start with pure MPI jobs that use all the cores on a node with a small amount of memory each, but then later tasks require more memory per core to work and so should be run with fewer cores per node.  Right now doing this would involve two separate slurm jobs, because we can't reconfigure a block to change how it is divided later.

**Comment by TomGlanzman** [comment]
This is a really nice idea for a situation where there is an unacceptably large overhead associated with creating new batch jobs, as is presently the case with SLURM at NERSC.

A variation on this idea might be to allow a mix of tasks on a single node at the same time.  Assuming the user specifies the "footprint" of each task (#cores, memory and, maybe, wall clock time), the "manager" could start "workers" appropriately so as to not over-subscribe the node.

(I do not know how this might work if the user had a task that spanned multiple nodes, given that there is one "manager" per node.)

**Comment by benclifford** [comment]
@TomGlanzman and I have been using the Work Queue executor, with some support in `master` parsl and some more support in `desc` parsl, to achieve something like that: each task can have its own resource requirements which workqueue will try to fit into a worker node alongside other compatible tasks.

I'll keep this issue open until it's all merged to master, but this functionality is in use now within DESC.

**Comment by benclifford** [comment]
closing this as completed - the above functionality is available using the WorkQueueExecutor now
