### ISSUE TITLE
LSF Provider

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#806]
We do not currently have a provider that supports LSF clusters. So far we've not had access to cluster that uses this batch system, but a potential user (@erykoff) from SLAC offered to help in this regard.

I imagine most of the effort in adding a new provider would be in testing rather than development given the several providers (eg, slurm) that can be used as templates.

@mjwilde, would you know any LSF clusters that we could get access to?

**Comment by mjwilde** [comment]
No, I dont know of any LSF machines.  NCAR Yellowstone was LSF but was
decommissioned over a year ago.

**Comment by jmjwozniak** [comment]
Summit is LSF, I could try it there.

**Comment by dgasmith** [comment]
+1 for a LSF provider, we have several researchers who need this and are limited to something like dask-jobqueue at the moment.

**Comment by jmjwozniak** [comment]
I can look at this next week...

**Comment by yadudoc** [comment]
There's a PR over at #1175 that's ready for some testing. I was wondering if any of you could give this a try ? @Lnaden, @erykoff, @jmjwozniak 
There's an example config from testing on Summit here: https://github.com/Parsl/parsl/blob/lsf_provider_%23806/parsl/tests/configs/summit_local_htex.py

**Comment by Lnaden** [comment]
Can and will do
