### ISSUE TITLE
Update example configurations in docs with htex

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#813]
Currently, the example configurations in docs use IPP. We should update them to HTEX.

**Comment by yadudoc** [comment]
All the example configs for target resources in the [configuration](https://parsl.readthedocs.io/en/latest/userguide/configuring.html) section needs to be updated.

- [ ] Comet
- [ ] Cori
- [ ] Stampede2
- [ ] Theta
- [ ] Cooley
- [ ] Swan
- [ ] CC-IN2P3, french grid 
- [ ] Midway
- [ ] AWS
- [ ] Ad-hoc clusters 
- [ ] Bluewaters
- [ ] Update ad-hoc clusters documentation with note to #941

**Comment by yadudoc** [comment]
This issue is addressed by several different PR's that are linked above.
