### ISSUE TITLE
Broken doc: case-studies page

### ISSUE THREAD

**Issue by dpiparo** [Parsl/parsl#821]
Hi,
I was browsing the (nice) documentation of parsl and I stumbled on a broken link: http://parsl-project.org/case-studies.html
I thought you might have wanted to be aware of this.

**Comment by yadudoc** [comment]
Hi Danilo, Thanks for reporting this. I will fix this asap.

**Comment by ZhuozhaoLi** [comment]
Hi Danilo, where did you encounter this link?
I believe the correct one shall be: http://parsl-project.org/case_studies.html

**Comment by dpiparo** [comment]
Front page (http://parsl-project.org/), "Scalable interactive computing." frame in the animation on the top.

**Comment by yadudoc** [comment]
I believe this is now fixed.
