### ISSUE TITLE
Predict queue wait times

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#844]
When requesting machines from a batch system, we do not have any idea of how soon our request will be filled. If we could predict the start times given the number of nodes/resource requested and the the duration, using an oracle, we could shape our request to be more queue friendly. For eg, some queue might favor a large request of nodes over several requests for fewer nodes.

Another use-case if multi-site workflows, where tasks from the workflow could execute on multiple execution sites. To minimise queue wait times, it helps to know what sites are not busy and target those sites. 

With knowledge of queuing cost, application runtimes and the complete workflow DAGs some really smart resource scheduling strategies are possible.

**Comment by danielskatz** [comment]
This has been the subject of much research over a long time, including by Rich Wolski's group at UCSB.  I think the answer that has been determined is that useful queue wait time prediction is not practical.
