### ISSUE TITLE
bytes strings can result in unexpected string formatting

### ISSUE THREAD

**Issue by macintoshpie** [Parsl/parsl#855]
I ran into a case with HTEX executor where address was of type bytes rather than string and this resulted in some unexpected formatting errors when formatting launch commands and such. Not sure if it matters, but using bytes was working fine when working with IPP.

Here's an example of a config:
```python
public_ip = b'123.123.123.123'
Config(
    executors=[
        HighThroughputExecutor(
            label='htex_local',
            address=public_ip,
            cores_per_worker=1,
            max_workers=2,
            provider=AWSProvider(
                'ami-073e3f122e47832bf',
                region='us-east-2',
                key_name='mykey',
                profile="default",
                state_file='awsproviderstate.json',
                nodes_per_block=1,
                init_blocks=2,
                max_blocks=2,
                min_blocks=0,
                walltime='01:00:00',
            ),
        )
    ],
    strategy=None,
)
```
You can see in the logs on the server and worker that addresses were formatted incorrectly (a `b` is inserted)
```
// server parsl logs
...
2019-04-09 01:03:15.441 parsl.executors.high_throughput.executor:199 [DEBUG]  Launch command: process_worker_pool.py  --max_workers=2 -c 1 --task_url=tcp://b'123.123.123.123':54865 --result_url=tcp://b'123.123.123.123':54464 --logdir=/home/ubuntu/swag-service/runinfo/040/htex_local --hb_period=30 --hb_threshold=120 
...
```
```
// worker logs
...
2019-04-09 00:56:57 parsl:480 Rank:0 [INFO]  task_url: tcp://b123.123.123.123:54579
2019-04-09 00:56:57 parsl:481 Rank:0 [INFO]  result_url: tcp://b123.123.123.123:54313
...
```

**Comment by yadudoc** [comment]
@macintoshpie Byte strings are quite different from regular strings, so I'm a bit puzzled as to why the IPP worked with that. Either way, for all our new executors the options are explicit about the expected types, and in the case of `address` options we need a string. I can't think of any actionable fix for this besides additional type checking which we generally avoid since it isn't quite pythonic.

What you are seeing in the logs is Python trying to convert a byte string to a regular string and failing at it  without realizing it.

**Comment by annawoodard** [comment]
> additional type checking which we generally avoid since it isn't quite pythonic.

interested in @benclifford's take on that

duck typing is pythonic:
```
try:
    address.decode()
except AttributeError:
    pass
```

**Comment by benclifford** [comment]
Our code base isn't particularly consistent in its handling of wrong types being passed in so I don't think we have a consistent story about who should be detecting this type mismatch.

@macintoshpie Where did the byte string come from in the real situation that this issue reflects?

**Comment by annawoodard** [comment]
I think the beginning of the story could be "the config class does some basic validation"

**Comment by macintoshpie** [comment]
The byte string came from urllib. On EC2, was using instance metadata to retrieve public ip:
```python
import urllib.request

public_ip = urllib.request.urlopen("http://169.254.169.254/latest/meta-data/public-ipv4").read()
```

Yeah, I think this was a more of a mistake on my end, not parsl. I just found it very confusing to have it work with IPP then when changing to HTEX trying to figure out what was wrong.

Just to confirm, I just reran it again with IPP using bytes and it worked - not sure why, its still showing the bytes string but I guess ipcontroller doesn't care for some reason (ip substituted):
```
2019-04-11 21:33:03.862 parsl.executors.ipp_controller:99 [DEBUG]  Starting ipcontroller with 'ipcontroller --ipython-dir=/home/ubuntu/swag-service/runinfo/080 --ip=* --profile=ec2_single_node  --location=b'123.123.123.123' '
```

**Comment by benclifford** [comment]
@macintoshpie that seems a reasonable piece of code that might be expected to work or fail more gracefully.

**Comment by benclifford** [comment]
issue #873 is a way forward for detecting this: with the work in that issue done, you should be presented with a clearer error message at the point that you attempt to initialize the high throughput executor telling you that you should have supplied `str`, not `byte`.

I will close this issue in favour of #873

**Comment by annawoodard** [comment]
Thanks for the report, @macintoshpie! This has pushed us to actually start on implementing config validation which will be a big improvement for usability 😁
