### ISSUE TITLE
HTEX interchange check python version mismatch to the micro level

### ISSUE THREAD

**Issue by ZhuozhaoLi** [Parsl/parsl#857]
Currently HTEX interchange check python version mismatch between worker and interchange to a micro level: e.g., `3.6.6 != 3.6.8`. I think it should be enough to only check the minor level.

https://github.com/Parsl/parsl/blob/2bc571c0a51ff04632548605d44314be7a97c8d0/parsl/executors/high_throughput/interchange.py#L358

**Comment by benclifford** [comment]
@ZhuozhaoLi have you encountered a real life situation where this affects you?

**Comment by ZhuozhaoLi** [comment]
> @ZhuozhaoLi have you encountered a real life situation where this affects you?

Yes. This happened when I used kubernetes provider. Each deployment/pod has different python version from python 3.6.6 to 3.6.8. This is a bit weird because I think all the container images were built from python 3.6  base image.

**Comment by benclifford** [comment]
If you look at `kubectl get pods --output=yaml`, you should see for each pod pairs `image` and `imageID` - the first probably a text name and the second something like an SHA hash.

Are these both the same for all of your pods?

**Comment by ZhuozhaoLi** [comment]
Sorry. I think I did not make it clear. 
This is used in DLHub - a machine learning serving platform. Each executor corresponds to one deployment and one ML model. Each deployment uses different image. But they should be built from python 3.6 base image. I am confused because the deployments have different python versions from 3.6.6 to 3.6.8, and this prevents us from using HTEX. Hope its clearer
