### ISSUE TITLE
Remove travis branch test from CI for faster PR merging

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#864]
At present two CI builds are run for a PR:

first, there is a per-branch build, run on every push to every branch, whether a PR exists for that branch or not.

secondly, when a PR exists, travis makes a new commit, not on any branch, which is a merge of that PR and `master`, and tests that.

Having two tests is unnecessary.

This duplicate test doubles the load on the test infrastructure - which results in a much longer build queue (substantially longer than 2x) when there is a lot of branch/PR activity, and is an impediment to prompt PR merging.

- [ ] The travis option `Build pushed branches` should be switched off - see https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests

- [ ] The travis option `Auto cancel PR builds` should be switched on. This will remove some builds from the queue if later commits have been pushed to the relevant branch, which obsoletes the test results from older-but-not-yet-run builds  - see https://docs.travis-ci.com/user/web-ui/#auto-cancel-branch-builds

(My original version of this issue advocated turning off PR builds and keeping branch builds, but I've subsequently observed that means we would not be able to merge PRs from forked repos, where only a PR build is made. Using PR-only builds means that CI won't be run until someone opens a PR for that branch, rather than whenever the branch is pushed. This has both upsides (less CI load) and downsides (you can't see your CI status until you make a PR - but I don't know how many people use that?)

**Comment by benclifford** [comment]
turns out I can make these changes myself, and I have done so (in the settings tab https://travis-ci.com/Parsl/parsl/settings )

If they cause trouble, set them back

**Comment by annawoodard** [comment]
AWESOME!!!!
So can we close this for now?
