### ISSUE TITLE
max_blocks not respected in SlurmProvider

### ISSUE THREAD

**Issue by TomGlanzman** [Parsl/parsl#868]
By specifying the following in my config:
```
            max_blocks=1, 
            min_blocks=1, 
```
I am finding *two* slurm jobs being submitted rather than one.  User wilde pointed out that by adding in `parallelism = 0.1` the extra slurm job would not be submitted.  Still, it seems that max_blocks should be respected.

Parsl 0.7.2
executor = HighThroughputExecutor
provider = SlurmProvider

**Comment by annawoodard** [comment]
Thanks for the report, @TomGlanzman!

Looks like we were on the right track, but we never update `provisioned_blocks` anywhere:
[https://github.com/Parsl/parsl/blob/master/parsl/providers/slurm/slurm.py#L158](https://github.com/Parsl/parsl/blob/master/parsl/providers/slurm/slurm.py#L158)

**Comment by yadudoc** [comment]
Related to #921

**Comment by benclifford** [comment]
PR #907 claims to fix this
