### ISSUE TITLE
user app log file management

### ISSUE THREAD

**Issue by TomGlanzman** [Parsl/parsl#871]
To facilitate searching user app log files when chasing down problems, it would be good to have distinct log files for each *run* of the workflow.  This might mean either a distinctive name or a distinctive path for the logs.  One option that comes to mind is to allow the user to specify the appropriate *rundir*, e.g., `runinfo/NNN` to place the log file(s).

Thank you for your consideration.

**Comment by annawoodard** [comment]
I think this is a great idea.

I'd take it farther, and lobby for this naming scheme:
`runinfo/XXX/task_logs/YY_ZZ.log`
where XXX=run id, YY=app name, ZZ=task id. But in #538 @benclifford mentioned he preferred having an application-specific tag for logs. So maybe YY=user-provided tag (which would take the place of the user specifying the log path).

**Comment by annawoodard** [comment]
cross-referencing #849

**Comment by TomGlanzman** [comment]
@annawoodard, thanks, that would work well for me.  Perfect!

One could even have *both* the YY=app name and TT=user tag in the file name.

**Comment by annawoodard** [comment]
One subtlety here is that this isn't so straightforward in cases where there isn't a shared FS between where the parsl script is running and where the task is running (see #276). But we can keep that factorized out as a separate issue.

**Comment by TomGlanzman** [comment]
In such a case (non-shared FS), where would the user app log be written by default?  Maybe that area (wherever it is) could inherit all or part of your proposed structure, i.e., .../NNN/task_logs/...

**Comment by yadudoc** [comment]
@TomGlanzman Just so you have the full picture, we don't yet support the no shared filesystem case. That broad space is being designed and worked on now as part of the data management effort. We'll still have some sort of sandboxing and directory naming mechanisms in there that takes these issues into account as @annawoodard pointed out.

**Comment by annawoodard** [comment]
We need to decide how to handle keyword args and defaults. Here are some options which would be backwards compatible:
```
option A
stdout='auto' -> stdout written to 'runinfo/AAA/task_logs/BBBB/task_CCC_DDD_EEE.stdout'
stdout='test.stdout' -> stdout written to 'test.stdout'
stdout=None -> no stdout (default)

option B
stdout=None -> stdout written to 'runinfo/AAA/task_logs/BBBB/task_CCC_DDD_EEE.stdout' (default)
stdout='test.stdout' -> stdout written to 'test.stdout'
stdout=False -> no stdout

option C
stdout=None -> stdout written to 'runinfo/AAA/task_logs/BBBB/task_CCC_DDD_EEE.stdout' (default)
stdout='test.stdout' -> stdout written to 'test.stdout'
no stdout in signature -> no stdout

option D
global configuration option to toggle logging-- not sure if it should override task settings?
```
where
AAA = run number
BBBB = int(task id / 10000)  (so we have directories with 10k entries each)
CCC = task id
DDD = app name
EEE = optional task label

**Comment by annawoodard** [comment]
These are all problematic in different ways 😢

**Comment by TomGlanzman** [comment]
(Just back from travel and catching up...)
IMO, both stdout and stderr should appear *somewhere* by default, so am less enthusiastic about option "C".  It also would seem odd (to me) if "stdout=None" actually caused output to be preserved.  Would something like this work?

stdout=True [default] -> stdout written to 'runinfo/AAA/task_logs/BBBB/task_CCC_DDD_EEE.stdout'
stdout='auto' -> stdout written to 'runinfo/AAA/task_logs/BBBB/task_CCC_DDD_EEE.stdout'
stdout='myStdout.log' -> stdout written to $PWD/myStdout.log
stdout='/a/b/c/myStdout.log' -> stdout written to /a/b/c/myStdout.log
stdout=None   -> no output
stdout=False   -> no output

And an equivalent set defined for stderr.

**Comment by benclifford** [comment]
I dislike use of `None`/`True`/`False` to create a multiway choice. I think I'd prefer to make an explicit [Enum](https://docs.python.org/3/library/enum.html) giving sensible symbolic names.

**Comment by yadudoc** [comment]
I vote for Option A with some minor changes. Like @benclifford said, we should use an enum instead of a magic string. I think the task label 'EEE' in the string is a bit overkill, and we should be covering most cases with the name of the app and the task_id. When composing the app dynamically, I prefer renaming the function and then wrapping with the decorator to embed labels into the app name, so I believe there's a reasonable way around the label issue.

@TomGlanzman is right that having these logs by default is convenient in production. Parsl is not quite a workflow management system but a scripting library and I believe that as a library we should defer choices like these to the user.

**Comment by TomGlanzman** [comment]
Why the task label is important.

I've been using a generic app to run different processes.  The task label is the only way I have to differentiate.  It is not redundant.  I will place my vote (if I even have a vote) to retain the "EEE" task label.

I will also place my vote to make stdout/stderr produce output default.  Are there really cases in production (of any size) where one would not wish to have a log?

**Comment by annawoodard** [comment]
@TomGlanzman: Thanks for your feedback! I've implemented your request and added a label (details [here](https://github.com/Parsl/parsl/commit/e18394e37b9ab3e2f1185122cb01c807fd329c94). Give it a whirl at your convenience and let us know what you think.

**Comment by TomGlanzman** [comment]
Hi @annawoodard , this all looks great!  Many thanks!

I made an weak attempt to try out the code, but failed due to my inability to get 'pip' to install it.  Maybe I should wait until it appears in a tagged release?

**Comment by annawoodard** [comment]
Hi @TomGlanzman! Thanks for having a look! You can install the 0.8 alpha release, which picks up this change, with: `pip install parsl==0.8.0a0`

**Comment by TomGlanzman** [comment]
I have now tried this new feature in Parsl 0.8.0a0.  Both the auto log file naming, and the 'label' parameter.  All features seem to be working exactly as advertised.  Many thanks!

One question about the task ID.  I am getting file names like: `.../runinfo/049/task_logs/0000/task_0019_genBF_makeBF.stderr`, which is fine.  Note that if both stdout and stderr are directed to this directory, the maximum number off files is 20k rather than 10k.  My question is whether the task_id in the file name, "0019" is the full task_id or mod(task_id,10000)?  That is, will the number of digits in the file name grow, as needed?

**Comment by annawoodard** [comment]
> the maximum number off files is 20k rather than 10k

Great point-- noted. Checking [here](https://unix.stackexchange.com/questions/239146/linux-folder-size-limit) it looks like the worst-case-scenario is a limit of 65k files per directory, so we should still be ok. We can adjust this down if we run into problems.

> My question is whether the task_id in the file name, "0019" is the full task_id or mod(task_id,10000)? 

The string is just padded with zeros, so the number of digits will grow as needed. I just picked a hard-coded padding I thought would keep the names tidy for the majority of workflow sizes. As we're a library and tasks could be being dispatched interactively in a jupyter notebook, there's no way to know the total number of tasks in order to programatically pick the appropriate padding length.

**Comment by annawoodard** [comment]
I forgot to mention-- thanks for testing this @TomGlanzman!
