### ISSUE TITLE
Merge relevant bits from `funcx_singularity_updates` branch

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#872]
There are significant improvements on the `funcx_singularity_branch` that need to be folded back into master, but they need to be factorized out from the container/etc stuff.

Among other things, this will fix #854 as it removes the call to multiprocessing.Queue.qsize()

**Comment by benclifford** [comment]
From a quick browse of this branch, it looks like this aims to do some stuff that I also have interest in (although it is not critical) for a workflow that I'm working on which uses shifter/singularity.

**Comment by benclifford** [comment]
Merging funcx stuff into parsl doesn't make sense any more - closing
