### ISSUE TITLE
Condor provider should set default channel

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#889]
When running the condor provider without explicitly setting the channel:
```
  File "/afs/hep.wisc.edu/home/awoodard/.local/lib/python3.6/site-packages/parsl-0.7.2-py3.6.egg/parsl/dataflow/dflow.py", line 762, in add_executors
    if executor.provider.channel.script_dir is None:
AttributeError: 'NoneType' object has no attribute 'script_dir'
```

**Comment by ZhuozhaoLi** [comment]
This reminds me that Condor provider has a hard-coded `cmd_timeout`. 
https://github.com/Parsl/parsl/blob/1d8c9e35752274af6ae2ce2f07107474ece4561c/parsl/providers/condor/condor.py#L225
Probably it can be fixed in the same PR?

**Comment by benclifford** [comment]
This is the class of bug we could be finding with mypy in the longer term
