### ISSUE TITLE
Condor provider has a hard-coded `cmd_timeout`. 

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#891]
This timeout should be configurable and probably default to something much longer.

https://github.com/Parsl/parsl/blob/1d8c9e35752274af6ae2ce2f07107474ece4561c/parsl/providers/condor/condor.py#L225

cc @ZhuozhaoLi who noted this in a comment to #889

**Comment by annawoodard** [comment]
Also reported by @lgray
