### ISSUE TITLE
Error checkpointing when no cache enabled

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#92]
We should catch the following error when running without any app caching and throw a helpful error

KeyError                                  Traceback (most recent call last)
<ipython-input-72-905a0ecb63d4> in <module>()
     12 [d[i].result() for i in range(5)]
     13 
---> 14 checkpoint_file = dfk.checkpoint()
     15 #print(checkpoint_file) # Prints the checkpoint dir
     16 #To load the checkpoint from a previous run specify the runinfo/RUNID directory:

/usr/local/lib/python3.5/dist-packages/parsl/dataflow/dflow.py in checkpoint(self)
    504                 if self.tasks[task_id]['app_fu'].done() and \
    505                    not self.tasks[task_id]['checkpoint']:
--> 506                     hashsum = self.tasks[task_id]['hashsum']
    507                     if not hashsum:
    508                         continue

KeyError: 'hashsum'

**Comment by yadudoc** [comment]
@kylechard Were you able to resolve what was happening here ? I had suspicions that you might have messed up you ipp kernel running different configs in the same notebook ?

**Comment by kylechard** [comment]
I think this was the error when no apps had cache=True set. In anycase I think we should catch this error and show a useful error.

**Comment by yadudoc** [comment]
I'm able to reproduce this. 

Should we raise an warning when checkpoint is called and no apps were checkpointed ? That would notify the user of the two possible cases : 
1. There are no apps that are cache-able
2. There are no new apps since the last checkpoint

**Comment by kylechard** [comment]
Yes, I think that would be useful.

**Comment by yadudoc** [comment]
Now the user gets a more reasonable warning from the logger: 
parsl.dataflow.dflow [WARNING]  No tasks checkpointed, please ensure caching is enabled

If the user has not enabled logging all of this info would not get to the screen, and the user will miss it unless they enable logging.
