### ISSUE TITLE
Logger continues after cleanup called

### ISSUE THREAD

**Issue by kylechard** [Parsl/parsl#93]
Even after calling dfk.cleanup() the logger continues with log statements like the following: 

2018-02-09 19:16:29,500 parsl.dataflow.strategy [DEBUG]  Site:Local_Threads Status:STATIC

**Comment by yadudoc** [comment]
The timer thread used by strategy needs more logic to auto shutdown. I'm thinking this is an easy enhancement to release along with 0.5.0, but if we decide this is a bug we could potentially release this earlier (@kylechard ?)
