### ISSUE TITLE
All workflows are called 'typeguard.py' in monitoring

### ISSUE THREAD

**Issue by annawoodard** [Parsl/parsl#973]

**Comment by ZhuozhaoLi** [comment]
Seems duplicated as #924

**Comment by benclifford** [comment]
There is stack-walking code like this to pick names, in `parsl/dataflow/dflow.py`. Without digging into this, my immediate suspicion is that this bit of code is walking up the call stack and immediately finding the typeguard decorator. Adding `"typeguard.py"` to `parsl_file_names` might fix this.

```
        self.workflow_name = None
        if self.monitoring is not None and self.monitoring.workflow_name is not None:
            self.workflow_name = self.monitoring.workflow_name
        else:
            for frame in inspect.stack():
                fname = os.path.basename(str(frame.filename))
                parsl_file_names = ['dflow.py']
                # Find first file name not considered a parsl file
                if fname not in parsl_file_names:
                    self.workflow_name = fname
                    break
```

**Comment by ZhuozhaoLi** [comment]
PR #959 is fixing this.

**Comment by yadudoc** [comment]
Isn't this already fixed ?

**Comment by benclifford** [comment]
@yadudoc the change in #959 looks like it would fix this yeah. it's not fixed till that PR is merged to master though and there seems some unrelated controversy.

**Comment by annawoodard** [comment]
sorry about that, closing as a dupe
