### ISSUE TITLE
Documentation for label, parsl.auto functionality

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#988]
We need documentation and examples to cover the new `label` special kwarg and the `parsl.auto` functionality.

**Comment by yadudoc** [comment]
Remember to tag commits with `[skip travis]`!

**Comment by annawoodard** [comment]
Documentation was added in the original PR [here](https://github.com/Parsl/parsl/pull/970/files#diff-a362036ab9b42a44473af85108cf173fR101). Can you clarify what further documentation is needed? I suppose we could switch over some of the examples like [this](https://parsl.readthedocs.io/en/latest/parsl-introduction.html)?

```
@bash_app
def echo_hello(stdout='echo-hello.stdout', stderr='echo-hello.stderr'):
    return 'echo "Hello World!"'

echo_hello().result()

with open('echo-hello.stdout', 'r') as f:
     print(f.read())
```

to

```
@bash_app
def echo_hello(stdout=parsl.AUTO_LOGNAME, stderr=parsl.AUTO_LOGNAME):
    return 'echo "Hello World!"'

future = echo_hello()
future.result()

with open(future.stdout, 'r') as f:
     print(f.read())
```

But maybe that's adding too much complication for early in the tutorial?

**Comment by yadudoc** [comment]
I'd add both of these. Having these two examples would be useful to users. I remember @mjwilde mention that our App doc section could be fleshed out more.
