### ISSUE TITLE
Method for apps to determine their target site

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#99]
Currently we don't have a method to indicate to the app the site it has been assigned to. If we do this with env variables it will be consistent across both `python` and `bash` apps. It would be simple to have this be set via the worker env.
Alternatively we could just push out a solution for #40 and reuse the same methods for site specific env variables as well.

I believe the data management ( #9, #71, #38 ) issues are dependent on this.

**Comment by lukaszlacinski** [comment]
Env as #40 suggest or some kind of 'context' that includes dfk.config, current site, etc. would be useful to pass to File.stage_in(context), File.stage_out(context), so File instance methods know what site (Globus endpoint, directory for staging) they deal with.

**Comment by yadudoc** [comment]
Mechanism is #1327 should work here as well.
