### ISSUE TITLE
Remove keyword substitution from bash apps

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#992]
The value returned from a bash app passes through some keyword substitution for being evaluated.

This is rarely used, and means that the string returned by a bash app has slightly different syntax from raw bash - `{` cannot be used in the same way in the two contexts.

Remove this implicit formatting.

Any substitutions that can be done this way can be done more directly in the user supplied user code (although with increased complexity) - as well as any other style of dynamic generation of bash code.

**Comment by annawoodard** [comment]
:+1: * 1000000

**Comment by benclifford** [comment]
Fix in #1034
