### ISSUE TITLE
sqlalchemy 1.3.4 spews warning message at import time

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#997]
On master, sqlalchemy spews this warning message : 
> /home/yadu/miniconda3/envs/parsl_0.8.0_py36_testing/lib/python3.6/site-packages/sqlalchemy/sql/functions.py:68: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier))

This happens only when using `sqlalchemy==1.3.4` and goes away when the version is downgraded to `1.3.3`

**Comment by yadudoc** [comment]
@ZhuozhaoLi Can you tack this onto one of the monitoring PRs ?

**Comment by benclifford** [comment]
In the longer term, it can be ugly to pin exact dependency library versions in code that is intended to be used as a library alongside other library code: two exact version pins from different places can't be resolved, I think.

**Comment by yadudoc** [comment]
@benclifford  As you pointed out this has caused a version conflict with the DESC stack at NERSC. We should've done something like `sqlalchemy>=1.3.0 ,<1.3.4`.
I'll make a new issue.
